### ISSUE TITLE
Contact by email not found

### ISSUE THREAD

**Issue by cyberaleks** [mailjet/mailjet-apiv3-php#103]
API: v3.1
When call get method on 
https://api.mailjet.com/v3.1/REST/contact/some@mail.com
It doesn't found any contacts.

**Comment by Zhivko-Mailjet** [comment]
@cyberaleks 
The /contact endpoint is running on version 3, not 3.1. The correct URL you should query is:
https://api.mailjet.com/v3/REST/contact/some@mail.com
as shown [here](https://dev.mailjet.com/email-api/v3/contact/)

**Comment by mskochev** [comment]
I am closing this issue as it has been answered already. Please feel free to reopen it in case further help is needed.
