### ISSUE TITLE
Can't retrieve statistics

### ISSUE THREAD

**Issue by gbredif** [mailjet/mailjet-apiv3-php#104]
Hi.

I use the 3.1 API to send my messages like described in the guide (https://dev.mailjet.com/guides/#grouping-into-a-campaign). I group my messages into a campaign (CustomCampaign => unique UUID).

Emails are sent correctly. My problem is when I want to get statistics.

I want to use /messagesentstatistics. First I can't specify the version of the API. If I use 3.1 I always get 404 error.

`$client = new \Mailjet\Client(
            Configure::read('Mailjet.public_key'),
            Configure::read('Mailjet.private_key'),
            true,
            ['version' => 'v3.1']
        );

        $filters = [
           // 'CustomID' => $id,
            'CustomCampaign' => $id,
            'AllMessages' => true
        ];

        $response = $client->get(Resources::$Messagesentstatistics, ['filters' => $filters]);
        if ($response->success()) {
            $data = [
                'success' => true,
                'total' => $response->getCount(),
                'data' => $response->getData()
            ];
        } else {
            $data = [
                'success' => false,
                'error' => $response->getReasonPhrase()
            ];
        }`

If I try without version parameters, I get a response but no data at all. 
Same thing if I removed filters.

I am not sure what I am doing wrong. I can access my statistics on my mailjet account but I can't retrieve those with API. My mailjet account was created in June.

Any help will be appreciate :)

**Comment by Zhivko-Mailjet** [comment]
@gbredif 
The $Messagesentstatistics endpoint is on  version 3, not on 3.1, regardless of the SendAPI version used.

By default, it returns results for the last 24 hours only. To display all messages in specific custom campaign, you should use the filter `AllMessages` set to true -> https://dev.mailjet.com/email-api/v3/messagesentstatistics/

Please note that if you put a unique ID for each message, you should not use the property `CustomCampaign `  but `CustomID` instead -> https://dev.mailjet.com/guides/?php#sending-an-email-with-a-custom-id

If you still have troubles, please[ reach out to our support ](https://app.mailjet.com/support/ticket)as there is no problem with the PHP wrapper, but more a general API usage issue.

Thank you for the understanding.

**Comment by gbredif** [comment]
@Zhivko-Mailjet 
Thx for your answer.

I am not using CustomID.
I want to group all my messages into a single campaign and use CustomCampaign to filters my data.

My problem occurs when I set CustomCampaign + AllMessages filters together on $Messagesentstatistics.
If I am not using CustomCampaign filter I get all my data (but that not what I want). 

I send messages in bulk. Each message has the same unique CustomCampaign.

`
    $message = [
                'From' => [
                    'Email' => $entity->get('from'),
                    'Name' => ''
                ],
                'To' => [
                    [
                        'Email' => $recipient->get('email'),
                        'Name' => ''
                    ]
                ],
                'Subject' => $entity->get('subject'),
                'HTMLPart' => $mailContents,
                'CustomCampaign' => $entity->get('id'),
            ];
`

I am going to open a ticket on mailjet. I maybe missunderstanding something.
Thx for your help.

**Comment by gbredif** [comment]
CustomCampaign filter need to be in lower case. My problem is solved.
