### ISSUE TITLE
Problème avec ContactslistManagemanycontacts

### ISSUE THREAD

**Issue by Atypix** [mailjet/mailjet-apiv3-php#105]
Bonjour,

J'utilise votre API pour synchroniser une liste de contact avec ma base de données.

Voici ma méthode : 

`
function synchronisation_mailjet($result, $listID) {

    $apiKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
    $apiSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

     if ($result) {
            $contacts=[];
            while ($row = $result->fetch_object()) {
                $a = [];
                $b = [];
                
                foreach ($row as $key => $value) {
                   
                    $b[$key] = trim($value);
                    if ($key == "email") $a['Email'] = trim($value);
                    if ($key == "nom") $a['Nom'] = trim($value);
                }
                $a['Properties'] = $b;
                $contacts[] = $a;
            }
            
        } else {
            echo 'pas de resultat\n';
        }
        
        $mj = new \Mailjet\Client($apiKey, $apiSecret);
        $body = [
            'Action' => "addnoforce",
            'Contacts' => $contacts
        ];

        var_dump($body);

        $response = $mj->post(Resources::$ContactslistManagemanycontacts, ['id'=>$listID, 'body' => $body]);
        $response->success() && var_dump($response->getData());

        
}
`

Lorsque je lance mon script, j'ai une réponse de l'api : 
`
array(1) {
  [0]=>
  array(1) {
    ["JobID"]=>
    int(62957652)
  }
}
`

Pourtant mes données dans ma liste de contact ne sont pas modifiées.
Pouvez vous m'aider svp ?

Bien cordialement,

**Comment by eboisgon** [comment]
Bonjour Atypix, 

Je vous conseillerais tout d'abord de jeter un œil a la partie concernant le monitoring de votre job  décrite ici : 
https://dev.mailjet.com/guides/?php#monitoring-the-upload-of-multiple-contacts-2  .
Vous devriez voir le statut de votre job qui est probablement en erreur. 

Si celui ci est en erreur vous trouverez la raison exacte en consultant le fichier d'erreur comme décrit un peu plus bas dans la même section de la documentation : 

$response = $mj->get(Resources::$BatchjobJsonerror, ['id' => $JobID]);

Cependant dans votre cas précis, je suspecte, sans avoir teste,  que le probleme vienne de cette ligne : 

if ($key == "nom") $a['Nom'] = trim($value);

qui devrait etre 

if ($key == "nom") $a['Name'] = trim($value);

Bien cordialement

**Comment by Atypix** [comment]
Merci pour votre réponse rapide.
En effet, j'ai un probleme de format de date : Property type does not match definition

Y a t-il un format particulier ?

**Comment by Atypix** [comment]
Bon, je m'en suis sorti en faisant : 
`$date = new DateTime($value);
                            $b[$key] = $date->format('Y-m-d H:i:sP'); `

Merci pour votre aide 👍
