### ISSUE TITLE
Segmentation de ma liste de contact

### ISSUE THREAD

**Issue by Atypix** [mailjet/mailjet-apiv3-php#106]
Bonjour,

Je souhaiterai savoir quelle est la meilleur méthode pour envoyer depuis l'api un email a un segment d'une liste de contact.

Pour être plus précis, j'ai des listes de contact qui sont segmentées en fonction de mes newsletters.
Chaque contact a une propriété [nom_de_la_newsletter] = 0 ou 1;

Je souhaite envoyer mes mails en fonction de ces paramètres.

Ce que j'ai cru comprendre, c'est qu'il faut que je créé une campagne sur le site et que je clique sur envoyer à un segment.

Ensuite depuis mon code j'utilise le paramètre Mj-campagn mais pas Mj-deduplicatecampaign car ces newsletters sont envoyées régulièrement.

c'est la propriété Recipients que je ne comprend pas. Dois je mettre le mail de la liste de contact ?

Bien cordialement,

**Comment by Atypix** [comment]
Re bonjour,

Mon code pour le moment : 
```
<?php

require 'vendor/autoload.php';
use \Mailjet\Resources;

$apiKey = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
$apiSecret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";

$mj = new \Mailjet\Client($apiKey, $apiSecret);
$body = [
    'Locale' => "fr_FR",
    'Sender' => "xxxxxxxxxxx",
    'SenderEmail' => "xxxxx@xxxxxxxx.com",
    'Subject' => "Test sur un segment",
    'ContactsListID' => "ID de ma liste de contact",
    'Title' => "Sur le segment de Test",
    'SegmentationID' => "???????"
];
$response = $mj->post(Resources::$Campaigndraft, ['body' => $body]);
$response->success() && var_dump($response->getData());

$id = $response->getData()[0]["ID"];

echo $id."\n";

$body = [
    'Html-part' => "Hello <strong>world</strong> Ceci est un email envoyé sur le Segment Test!",
    'Text-part' => "Hello world! Ceci est un email envoyé sur le Segment Test"
];
$response = $mj->post(Resources::$CampaigndraftDetailcontent, ['id' => $id, 'body' => $body]);
$response->success() && var_dump($response->getData());


$body = [
    'Recipients' => [
        [
            'Email' => "xxxxxxxxxxx@xxxxxxxxx.com",
            'Name' => "xxxxxx"
        ]
    ]
];
$response = $mj->post(Resources::$CampaigndraftTest, ['id' => $id, 'body' => $body]);
$response->success() && var_dump($response->getData());

$response = $mj->post(Resources::$CampaigndraftSend, ['id' => $id]);
$response->success() && var_dump($response->getData());
```

Ma question est comment je peux récupérer l'ID du segment qui a été créé sur le site ?

`'SegmentationID' => "???????"`

Bien cordialement,

**Comment by eboisgon** [comment]
Bonjour Atypix,

Cette section de la documentation pourra vous aider a comprendre le fonctionnement de la segmentation : [https://dev.mailjet.com/guides/?php#segmentation](https://dev.mailjet.com/guides/?php#segmentation)

Pour resumer , vous pourrez trouver vos filtres de segmentation en utilisant ceci:

$response = $mj->get(Resources::$Contactfilter);

Bien cordialement

**Comment by Atypix** [comment]
Merci pour votre réponse, ma situation est presque débloquée.
Lorsque j 'envoi ma campagne (sur le bon segment) le mail de test arrive, 

en revanche la campagne est mise en attente (dans l'interface) et aucun mail n'est envoyé

voici la fin de mon code : 

```
echo $id."\n";

$body = [
    'Html-part' => "Hello <strong>world</strong> Ceci est un email envoyé sur le Segment Test pour la seconde fois !"
];
$response = $mj->post(Resources::$CampaigndraftDetailcontent, ['id' => $id, 'body' => $body]);
$response->success() && var_dump($response->getData());


$body = [
    'Recipients' => [
        [
            'Email' => "xxxx@xxxx.com",
            'Name' => "xxxxx"
        ]
    ]
];
$response = $mj->post(Resources::$CampaigndraftTest, ['id' => $id, 'body' => $body]);
$response->success() && var_dump($response->getData());

$response = $mj->post(Resources::$CampaigndraftSend, ['id' => $id]);
$response->success() && var_dump($response->getData());
```

**Comment by Atypix** [comment]
Ok, en fait ma liste de contact segmentée ne comportait qu'un seul contact. Donc c'est ok pour moi :)

Merci beaucoup !
