### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by jimblue** [mailjet/mailjet-apiv3-php#107]
Hi,

I'm following the Mailchimp doc but I can't get it work.

I just need to subscribe and unsubscribe method.

**Here is the raw response error I get:**

<img width="445" alt="screen shot 2018-01-12 at 10 22 40" src="https://user-images.githubusercontent.com/10623367/34868099-00e3e96e-f783-11e7-9c96-7ce8e1d75377.png">

**Here is my code:**

```php
    $public_key = '########################';
    $private_key = ''########################';
    $list_id = '######';
    $email = 'saratest@gmail.com';

    $mailjet = new \Mailjet\Client($public_key, $private_key);

    $body = [
      'Email' => $email,
      'Name' => "MrSmith",
      'Action' => "addnoforce",
      'Properties' => [
        'property1' => "value",
        'propertyN' => "valueN"
      ]
    ];

    $response = $mailjet->post(\Mailjet\Resources::$ContactslistManagecontact, [
      'id' => $list_id,
      'body' => $body
    ]);

    if ($response->success()) {

      // if the call succed, data will go here
      $result = $response->getData();

      dump($result);
    }

    $result = $response->getStatus();

    dump($result);
```

**Comment by jimblue** [comment]
I've check hundred time my API keys (public and private)...
I've even try to reset them...

Still getting error with code 401, I don't get it.

**Comment by TomTheRock** [comment]
Do you solved this? I have the same problem...

**Comment by TomTheRock** [comment]
be sure that you do not missmatch the parameters(which was my fault):
new \Mailjet\Client($apikey, $apisecret,true,['version' => 'v3.1']);
FIRST: APIKEY
SECOND: SECRET

**Comment by jimblue** [comment]
I'm sorry @TomTheRock t was more than a month ago, I don't remember what was the problem and how I fixed it.

**Comment by remydragyn** [comment]
If someone is passing by with the same error.

Stack : 
- Symfony (symfony/mailjet-mailer)
- Supervisor

In my case, I'm using Supervisor and had to kill the process that had the old API keys in cache :
1. `ps -ef | grep supervisord` to see the processes
2. `sudo kill -s SIGTERM #{PID}` to kill the old one

Might not be related but I had to change the permissions on `/tmp/supervisord.log` too.
