### ISSUE TITLE
Check if a contact has subsrcibed a contact list

### ISSUE THREAD

**Issue by BalleyWarson** [mailjet/mailjet-apiv3-php#108]
I want to check if an email is in a contact list
I try this ( because ContactsList is in the filters of Contact : https://dev.mailjet.com/email-api/v3/contact/ )

`<?php
$email = 'mail@domain.com';
$listID = 123456;
$mj = new \Mailjet\Client($key, $secret);
$response = $mj -> get(Resources::$Contact, ['ID' => $email, 'filters' => ['ContactList' => $listID ]] );

?>
`
In my idea, if $email is not in $listID, I should get a 404 error, instead I've a response with all contact:ID infos

**Comment by jimblue** [comment]
Agree actually handle subscription with the API is not ideal.

You should add a isSubscribed method.

Or return different kind of response code and message if someone is already subscribed.

**Comment by jimblue** [comment]
It was a pain in the ass to found the following solution with actual documentation.
Please Mailjet team make the documentation more clear or add plug and play method for basic function into the wrapper.

For the seek:

```for 
public function isSubscribed(string $email)
  {
    $listID = $this->listID;

    $request = $this->mailjet->get(Resources::$Listrecipient, [
      'filters' => [
        'ContactsList' => $listID,
        'ContactEmail' => $email
      ]
    ]);

    $response = false;

    if ($request->success()) {
      $data = $request->getData();

      if (empty($data)) {
        $response = false;
      } else {
        $response = $data[0]['IsUnsubscribed'];
      }
    }

    return $response;
  }
```

**Comment by BalleyWarson** [comment]
This seems to work like a charm, many thanks Jim !

My bad, I did not see the listRecipient method !
I also think there is to much methods undocomuented or bad documented. The doc needs more exemple.

**Comment by SafaaFX** [comment]
Thank you jimblue  :+1:
