### ISSUE TITLE
Transactionnal Email Send Issue

### ISSUE THREAD

**Issue by bamboolix** [mailjet/mailjet-apiv3-php#109]
Hello,

I can no longer send transactional emails. I'm getting this message when I vardump the response from mallet :

```
array(3)
{ ["ErrorIdentifier"]=> string(36) "df8e6965-fac8-467b-a5a2-b8c450e0664e" ["StatusCode"]=> int(401) ["ErrorMessage"]=> string(173) "API key authentication/authorization failure. You may be unauthorized to access the API or your API key may be expired. Visit API keys management section to check your keys."
 }
```

I tried to renew my Key in the back-office in vain 

Could ou advise me on this point ?

Regards

**Comment by TomTheRock** [comment]
be sure that you do not missmatch the parameters(which was my fault):
new \Mailjet\Client($apikey, $apisecret,true,['version' => 'v3.1']);
FIRST: APIKEY
SECOND: SECRET
