### ISSUE TITLE
Search, Create, Move a contact

### ISSUE THREAD

**Issue by RiderFx3** [mailjet/mailjet-apiv3-php#110]
Bonjour,

J'utilise le nouveau wrapper PHP et je dois dire que j'ai beaucopu de mal à trouver les infos concernant le PHP dans la doc. Les exemples pour ce que je cherche à faire n'y sont pas.

Je souhaite faire quelque chose de très basique, chercher si un contact existe, trouver son ID, pour pouvoir le supprimer d'une liste et l'ajouter dans une autre.

J'arrive à ajouter un contact dans une liste (ça créé le contact, puis le déplace dans la liste automatiquement à priori) : 
`function mj_add_contact( $contact = null, $list_id = 1704204 ){ //Fonctionnel
	$mj = new \Mailjet\Client( 'xxxxx', 'xxxxx' );
	$body = [
	    'Email' => "mrsmith@mailjet.com",
	    'Name' => "MrSmith",
	    'Action' => "addforce"
	];
	$response = $mj->post(Resources::$ContactslistManagecontact, ['id' => $list_id, 'body' => $body]);
	if ($response->success())
	  	return var_dump($response->getData());
	else
	  	return var_dump($response->getStatus());
}`

J'arrive également à le supprimer de la liste : 
`function mj_remove_contact( $list_id = xxxxxx ){ //Fonctionnel
	$mj = new \Mailjet\Client( 'xxxxx', 'xxxxx' );
	$body = [
	    'Email' => "mrsmith@mailjet.com",
	    'Action' => "remove"
	];
	$response = $mj->post(Resources::$ContactslistManagecontact, ['id' => $list_id, 'body' => $body]);
	if ($response->success())
	  	return var_dump($response->getData());
	else
	  	return var_dump($response->getStatus());
}`
Mais vu que le contact est supprimé de la liste mais pas de mon compte, je ne peux donc pas le rajouter dans une autre liste juste avec son email. Il me faut retrouver son ID pour ça je pense.

Et c'est là que ça foire, l'API me retourne en fait une liste de 10 contacts mais pas le contact en question avec ce code : 
`function mj_find_contact( $list_id = xxxxx ){
 	$mj = new \Mailjet\Client( 'xxxxx', 'xxxxx' );
	$filters = [
	    'Email' => "mrsmith@mailjet.com"
	];
	$response = $mj->get(Resources::$Contact, ['filters' => $filters] );
	if ($response->success())
	  	return var_dump($response->getData());
	else
	  	return var_dump($response->getStatus());
}`

Quelle est la bonne façon de procéder ? Y a t'il une façon plus simple que ce que j'essaie de faire pour déplacer un contact d'une liste à une autre ? 

Merci pour votre aide.

Du coup, je trouve que la documentation PHP manque cruellement d'infos.

**Comment by SafaaFX** [comment]
Bonjour, j'ai le même problème que vous, merci de me dire si vous avez arriver à trouver une solution? Merci par avance.

**Comment by simondebn** [comment]
Bonjour, je me suis confronté au même problème. J'ai donc directement fait la requête via Curl (je pense que cette fonction peut servir de modèle à différents types de requêtes.)
J'espère que cette solution pourra vous aider même si votre question date un peu.
PS : je débute dans le développement alors n'hésitez pas à faire des corrections/critiques.

Hello, I encountered the same problem. So I made the request directly withCurl (I think this function can be used as a template for different types of requests.)
I hope this solution will help you even if your question is a little old.
PS: I'm a junior dev so suggestions and comments are welcome.

``` php
function mailjet_get_contact_from_email($public_key, $private_key,  $email){
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api.mailjet.com/v3/REST/contact/' .$email );
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_USERPWD, $public_key . ':' . $private_key);
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    $output = curl_exec($ch);
    $info = curl_getinfo($ch); // Optional : Infos about HTTP status etc.
    curl_close($ch);
    return  json_decode($output);
}
```

**Comment by harkor** [comment]
Je suis d'accord avec vous la documentation est trop légère.
Le code dans cette issue à l'air de fonctionner.

https://github.com/mailjet/mailjet-apiv3-php/issues/156#issuecomment-437359432

I'm agree with you the documentation is too weak.
Code in this issue seems to work

https://github.com/mailjet/mailjet-apiv3-php/issues/156#issuecomment-437359432

**Comment by abambova** [comment]
Hello @RiderFx3 ,
As the issue is answered and there is a proposed solution I'll close the ticket. Please open a new ticket if needed.

**Comment by Marc-oO** [comment]
Hello,

"As the issue is answered", realy?

Documentation is really WEAK, open randomly some issues here: https://github.com/mailjet/mailjet-apiv3-php/issues?q=documentation

Mailjet should make a poll, or a newsletter (:D) in order to get developpers feedbacks, mailjet api documentation is incomplete and poorly organized.

Mailjet should take care about developers needs, like Stripe does per example.

I will recommend other mailing solutions to my customers i think, except those with very very basic usage may be.

Regards

**Comment by Slayvin** [comment]
La question date un peu, mais étant confronté au même problème, je poste ici une solution.
I know the question is old, but I encountered the same problem, so here is a solution:
```php
 $mj    = new Client('mailjet.apikey_public', 'mailjet.apikey_private', true, ['version' => 'v3']);
 $args = [
   "id" => 'email@address.com',
];
$response = $mj->get(Resources::$Contact, $args);
echo  var_dump($response->success());
echo  var_dump($response->getData());
```
