### ISSUE TITLE
vendor/autoload.php is missing 

### ISSUE THREAD

**Issue by MarineLohezic** [mailjet/mailjet-apiv3-php#112]
I'm trying to use the api with php and without composer but it seems like the "vendor/autoload.php" is missing on github. (.gitignore contains vendor/*"). 

Thank you for your help

**Comment by deenlord** [comment]
I have been searching for it all day! I have no idea where to find this file. I get that composer is supposed to handle it, but I don't know what that is, or care. I just want to send an email. Any insight as to where to get this file is appreciated.

**Comment by deenlord** [comment]
Hey @MarineLohezic look what I just found: https://github.com/mailjet/mailjet-apiv3-php-no-composer/tree/master/vendor I think the omission was intentional. Feel free to close this issue, but an admin should provide this link somewhere on this repo for clarity.

**Comment by MarineLohezic** [comment]
Thank you, I'll closed the subject
