### ISSUE TITLE
Wrong min php version

### ISSUE THREAD

**Issue by ernestas-convertize** [mailjet/mailjet-apiv3-php#114]
Hello,
In your `readme.md` it says that minimum required PHP version is `v5.4` which is not true as you this API package requires `guzzlehttp` package whom PHP minimum required version is `v5.5` which makes some `json_encode` functions fail.

**Comment by Benoit-amo** [comment]
Last year, we backported the lib on PHP 5.3 : [AMOSoft/mailjet-apiv3-php](https://github.com/AMOSoft/mailjet-apiv3-php)
It works in production.

**Comment by ernestas-convertize** [comment]
Thank you for this one I will replace on my project, but still an issue was regarding  [mailjet/mailjet-apiv3-php](https://github.com/mailjet/mailjet-apiv3-php)
 :)

**Comment by ernestas-convertize** [comment]
@Benoit-amo  https://packagist.org/packages/amosoft/mailjet-apiv3-php#v1.1.2
This package have same requirements as this one... had to manually download from github and write my own composer installs...

As well cannot make any issues in https://github.com/AMOSoft/mailjet-apiv3-php repo.

**Comment by Benoit-amo** [comment]
Sorry, I missed that.
Fixed : https://packagist.org/packages/amosoft/mailjet-apiv3-php#v1.2.0

Not sure we have enough time for that, but : https://github.com/AMOSoft/mailjet-apiv3-php/issues

**Comment by Thoradin89** [comment]
Hello @ernestas-convertize,

It seems the ticket is now resolved and will be closed.

Regards,
T.
