### ISSUE TITLE
Aucune requête ne passe.

### ISSUE THREAD

**Issue by quentingosset** [mailjet/mailjet-apiv3-php#118]
Bonjour tous le monde, je suis sur un problème assez gênant.
J'essaye une simple requête de récupération d'information de mon profile et ma requête ne renvoie rien.
J'ai reset mon API KEY et rien n'y fait.
Si quelqu'un à une solution je suis preneur.

````
$mj = new \Mailjet\Client("PUBLIC",
    "PRIVATE", true, ['version' => 'v3']
);

// API call with specific options. The options passed in the call will only be used for this call.
$response = $mj->get(Resources::$Myprofile, []);

var_dump($response->request->getUrl());
var_dump($response->request->getFilters());
var_dump($response->request->getBody());
````

`string(41) "https://api.mailjet.com/v3/REST/myprofile" array(0) { } NULL`

**Comment by kachar** [comment]
Try to dump the response body instead of the request body.
As the request is GET there's no body attached to it.

```php
var_dump($response->request->getBody());
var_dump($response->getBody());
```

**Comment by quentingosset** [comment]
Not working, continu to say "NULL" :( 
It's not because i have a old version on my account like this issues? 
https://github.com/mailjet/mailjet-apiv3-php/issues/24
