### ISSUE TITLE
Aucune requêtes ne passe.

### ISSUE THREAD

**Issue by quentingosset** [mailjet/mailjet-apiv3-php#119]
Bonjour tous le monde, je suis sur un problème assez gênant.
J'essaye une simple requête de récupération d'information de mon profile et ma requête ne renvoie rien.
J'ai reset mon API KEY et rien n'y fait.
Si quelqu'un à une solution je suis preneur.

````
$mj = new \Mailjet\Client("PUBLIC",
    "PRIVATE", true, ['version' => 'v3']
);

// API call with specific options. The options passed in the call will only be used for this call.
$response = $mj->get(Resources::$Myprofile, []);

var_dump($response->request->getUrl());
var_dump($response->request->getFilters());
var_dump($response->request->getBody());
var_dump($response->getBody());
````

`string(41) "https://api.mailjet.com/v3/REST/myprofile" array(0) { } NULL NULL`

Ps : don't close the issues if it's not solved ...

**Comment by kachar** [comment]
You can check for the following to find out the api response details:

```php
var_dump($response->getReasonPhrase());
var_dump($response->success());
```

You can also open a ticket to the support team and provide the ID so we can track the requests.

**Comment by quentingosset** [comment]
@kachar 
`NULL string(2) "OK" bool(true)`

he tells me that the request is correct however I have no feedback with any information from my account.

**Comment by kachar** [comment]
Do you receive good data for different api calls like

```php
$response = $mj->get(Resources::$Sender, []);
var_dump($response->getBody());

$response = $mj->get(Resources::$User, []);
var_dump($response->getBody());
```

Please drop me an email at ikacharov@mailjet.com with your account email so I can check if everything is ok technically.

**Comment by latanasov** [comment]
@quentingosset  you just need to do:
`var_dump($response->getBody());`
not
`var_dump($response->request->getBody());`

The `$mj->get(..)` already returns the Response object itself.

**Comment by quentingosset** [comment]
@kachar  @latanasov ,
```
// API call with specific options. The options passed in the call will only be used for this call.
$response = $mj->get(Resources::$Myprofile, [], ['version' => 'v3']);

var_dump($response->getBody());
var_dump($response->request->getBody());

$response = $mj->get(Resources::$Sender, []);
var_dump($response->getBody());
var_dump($response->request->getBody());

$response = $mj->get(Resources::$User, []);
var_dump($response->getBody());
var_dump($response->request->getBody());

```
result : 

`NULL NULL NULL NULL NULL NULL`

@kachar i send you a mail :-)

**Comment by kachar** [comment]
Hey @quentingosset 
It seems your issue is with the setup of the php file.
Having the following works in all cases with many accounts including yours:

```php
<?php
require 'vendor/autoload.php';
$mailjetApi = new \Mailjet\Client(getenv('MJ_APIKEY'), getenv('MJ_SECRET'), true, ['version' => 'v3']);
$response = $mailjetApi->get(\Mailjet\Resources::$Myprofile);
var_dump($response->getBody());
var_dump($response->getReasonPhrase());
```

**Comment by quentingosset** [comment]
@kachar,
ok, my problem was that inside getenv () I included my identification key but also my MJ constructor was too much information wrong.

Thanks for your help.
