### ISSUE TITLE
Private static method ? 0ô 

### ISSUE THREAD

**Issue by flug** [mailjet/mailjet-apiv3-php#12]
In Endpoint file you call a method "call" why not. But she is private and not static. I wonder if it is functional, at least if this is the case it is odd and not normal https://github.com/mailjet/mailjet-apiv3-php/blob/master/src/Mailjet/Endpoint.php#L65

**Comment by GuillaumeBadi** [comment]
Old file actually. It shouldnt be here. It wouldnt work you're right
