### ISSUE TITLE
Send SMS with your API

### ISSUE THREAD

**Issue by PierreAmmeloot** [mailjet/mailjet-apiv3-php#120]
Hello, we can't send SMS (https://dev.mailjet.com/guides-sms/) at this time with your wrapper.
Can you update this code to support this feature?

**Comment by kmanchikov** [comment]
Hi Pierre, 

We are currently working on updating the PHP Wrapper and not only, to reflect the newly released SMS Feature, as we will soon let you know when this becomes available.  

Best,

Krasimir

**Comment by PierreAmmeloot** [comment]
Hi Krasimir, thanks for your reply. 
Do you have ETA for this PHP Wrapper ?

Best,
Pierre

**Comment by kmanchikov** [comment]
You're most welcome Pierre. Currently we do not have an exact ETA on that but I will be sure to let you know once that is available. 

Best, 
Krasimir

**Comment by mskochev** [comment]
The SMS feature is now available in the latest version of the wrapper (v1.4.1).

**Comment by PierreAmmeloot** [comment]
@mskochev thank you, do have a link for documentation?

**Comment by mskochev** [comment]
Hello Pierre,

There is a short explanation in the readme: https://github.com/mailjet/mailjet-apiv3-php#version-140-of-the-php-wrapper
