### ISSUE TITLE
Usage of MJMLContent in /campaigndraft/:id/detailcontent inconsitent

### ISSUE THREAD

**Issue by toovy** [mailjet/mailjet-apiv3-php#121]
Hi there,

this ticket is a follow up to #76 which was - at least in my eyes - not completely solved. When using Resources::$CampaigndraftDetailcontent in combination with the parameter MJMLContent I would expect that the MJML is used to render the final HTML-Email that is sent when sending the campaign **via API**. This is not the case.

#76 states that in order to use **MJMLContent** you also need to set **Html-part** parameter, which is kind of strange an makes no sense to me. We are trying to automate sending of a dynamically built newsletter campaign based on wordpress posts. In my code below I'm trying to automatically create a campaign, set the detailcontent and to send it. **The resulting email contains the HTML-part, but not the MJMLContent as expected.**

When I don't execute the last step of my code (e.g. comment it out) and login via web-ui I can edit the campaign and I can confirm that the MJML editor can be used to edit the campaigns content. So setting the content worked. When sending the campaign from the web-ui the MJML is used as basis for the HTML email. **So sending the campaign out manually would work.**

**But we need to have this process fully automated.**

I know that the transactional email API could be used like in @eboisgon (we recently had a call about this topic) example with the RSS feed (https://github.com/mailjet/mailjet-apiv3-templating-samples/tree/master/samples/rss_to_email). But we decided that we want the campaign analytics and stuff. And I know that I could render the HTML on my server, but as my server is limited to PHP I cannot properly render the MJML.

Could you please help?

Thanks a lot,
Kind regards,
Tobias

```
<?php

require 'vendor/autoload.php';

use \Mailjet\Resources;

# sample post data
$posts = [
  [
    "title" => 'Consetetur sadipscing elitr, sed',
    "subtitle" => 'Dolore magna aliquyam',
    "excerpt" => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.',
    "permalink" => 'http://www.something.com'
  ],
  [
    "title" => 'Accusam et justo duo dolores',
    "excerpt" => 'Lorem  eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.',
    "permalink" => 'http://www.somethingelse.com'
  ]
];

# render PHP template that results in MJML
function render_php($path, array $data){
    ob_start();
    include($path);
    $var=ob_get_contents();
    ob_end_clean();
    return $var;
}

$config = [
  'key' => '***',
  'secret' => '***',
  'campaign' => [
    'Locale' => "en_US",
    'Sender' => '***',
    'SenderName' => '***',
    'SenderEmail' => '***@***.**',
    'Subject' => 'Greetings',
    'ContactsListID' => '***',
    'Title' => 'API driven Campaign',
    'EditMode' => 'mjml'
  ],
  'detailcontent' => [
    'Html-part' => 'Hello Html-part',
    'MJMLContent' => render_php('./mjml-template.php', ['posts' => $posts])
  ]
];

$mj = new \Mailjet\Client($config['key'], $config['secret']);

# Step 1: Create Campaign
$response = $mj->post(Resources::$Campaigndraft, ['body' => $config['campaign']]);

$campaignId = $response->getData()[0]['ID'];

# Step 2: Set Detail Content
$response = $mj->post(Resources::$CampaigndraftDetailcontent, ['id' => $campaignId, 'body' => $config['detailcontent']]);

# Step 3: Send the campaign
$response = $mj->post(Resources::$CampaigndraftSend, ['id' => $campaignId]);
```

**Comment by ngarnier** [comment]
Hey @toovy, indeed it's not possible to render MJML to HTML via the Mailjet API at the moment. 

A possible workaround would be to use the MJML API: https://mjml.io/api to render MJML to HTML, so you don't have to run MJML on your server. How about that?

We're also planning to add RSS support in our builder, would that be useful to you?

This is not a wrapper issue, so I'll close it. Feel free to ping me directly on ngarnier@mailjet.com.

**Comment by toovy** [comment]
@ngarnier thank your for the quick reply and thanks for pointing the mjml-API out, I didn't know it and probably I'll use it. RSS driven campaigns that could be scheduled e.g. monthly would be awesome. Great support!

**Comment by tolik505** [comment]
Is it still not possible to render MJML to HTML via the Mailjet API?

**Comment by saidluis** [comment]
So, why the `detailContent` structure has a `MJMLContent` attribute?

```
$body = [
  'Headers' => "object",
  'Html-part' => "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
  'MJMLContent' => "",
  'Text-part' => "Dear passenger, welcome to Mailjet! May the delivery force be with you!"
];
```

**Comment by tolik505** [comment]
The world is not perfect @saidluis 😀
