### ISSUE TITLE
contacthistorydata always returning an empty array

### ISSUE THREAD

**Issue by aureliusm** [mailjet/mailjet-apiv3-php#122]
Hi,

I am having issues getting contact history data. Whatever I try I get an empty array back. My current solution is like so:

```
$response = $mj->get(Resources::$Contacthistorydata, ['filters' => [
                    'Contact' => 12345
                ]]);
```
* 12345 is an existing contact ID. 

I also tried without contact, and using ID as unique id or email as unique id and always it's an empty array?

**Comment by mskochev** [comment]
Hello @aureliusm, please can you tell me what are you trying to achieve with that. Using contacthistorydata is a bit tricky, so we need to see how to approach your use case in the best possible way.

**Comment by aureliusm** [comment]
@mskochev Hi, I have already solved this issue by using a different resource in the end. My mistake. Closing the issue. Thanks for helping ouy!
