### ISSUE TITLE
Missing $statcounters

### ISSUE THREAD

**Issue by romainthiberville** [mailjet/mailjet-apiv3-php#125]
Hello,

The new endpoint $statcounters seems to be missing.

/statcounters

API Message-based or Event-based statistics per API key, Campaign or List grouped over intervals. This is a new endpoint. Only available for campaigns sent after April 3rd, 2018. 

https://dev.mailjet.com/email-api/v3/statcounters/

Best regards,

Romain

**Comment by kmanchikov** [comment]
Hi Romain, 

The new resources ( like /statcounters ) are yet to be released for the PHP Wrapper as well as the reset of the Wrappers, as its currently under development. 

Best, 

Krassimir

**Comment by JoanIzquierdo** [comment]
Hi, we need call to resource "statcounter" of REST API MailJet via PHP but it isn't developed. Do you know when it will be implemented? .. Thanks.

**Comment by kachar** [comment]
StatCounters endpoint been implemented with https://github.com/mailjet/mailjet-apiv3-php/pull/129 almost a month ago

**Comment by JoanIzquierdo** [comment]
Thanks and perfect. Do you have an example how should we call this resource "statcounter"?
```
$response = $mj->get(Resources::$Statcounters, ...);
if ($response->success()) {
}
```

**Comment by kachar** [comment]
You can check the official documentation at https://dev.mailjet.com/email-api/v3/statcounters/

and Dev guides at https://dev.mailjet.com/guides/#key-performance-statistics

```php
$filters = [
  'SourceId' => '$Campaign_ID',
  'CounterSource' => 'Campaign',
  'CounterTiming' => 'Message',
  'CounterResolution' => 'Lifetime'
];
$response = $mj->get(Resources::$Statcounters, ['filters' => $filters]);
$response->success() && var_dump($response->getData());
```
