### ISSUE TITLE
GET /campaignstatistics with MinLastActivityAt \ MaxLastActivityAt is the other way around

### ISSUE THREAD

**Issue by idoelad** [mailjet/mailjet-apiv3-php#127]
My guess is that this is not a PHP issue but a general API issue but in any case:

When using the `/campaignstatistics` endpoint with the `MinLastActivityAt`  \ `MaxLastActivityAt` filters, there's a confusion between the two.

MinLastActivityAt - will only retrieve campaigns that have LastActivityAt less than this value.
MaxLastActivityAt - will only retrieve campaigns that have LastActivityAt larger than this value.

According to the [documentation ](https://dev.mailjet.com/email-api/v3/campaignstatistics/)(and logic...), this should be the other way around.

**Comment by kmanchikov** [comment]
Hi Ido, 

Thank you for pointing that one out. It's seems to work property when done through curl, but haven't yet tested the resource for this wrapper. 

Do keep in mind however that this resource will be deprecated and no longer supported, as there is an better alternative which is $Statcounters and I would recommend switching to it, as I have already used it multiple times and works like a charm

**Comment by abambova** [comment]
Hi @idoelad,

Did you have time to test the solution proposed by @kmanchikov? If yes, does the issue persist?
Looking forward to your reply,

Regards,
Aneliya

**Comment by abambova** [comment]
Hi @idoelad 
I'll close the issue but if you need please feel free to open a new one. Thanks!
