### ISSUE TITLE
Client picking the wrong Content-type

### ISSUE THREAD

**Issue by nturato** [mailjet/mailjet-apiv3-php#13]
fix that condition.
```php
$contentType = $action ==
            ('csvdata/text:plain' || $action == 'csverror/text:csv') ?
                'text/plain' : 'application/json';
```
https://github.com/mailjet/mailjet-apiv3-php/blob/master/src/Mailjet/Client.php#L71

I've found that error while trying to send a newsletter. The Client is creating a Request with content-type text/plain, APIs don't like that.

**Comment by GuillaumeBadi** [comment]
Hey @nturato !
Thanks for using Mailjet!

it shouldn't set it to `text/plain` except with `ContactslistCsvdata` or `BatchjobCsverror`, can you paste your code, or be more specific about that ?

Best,
Guillaume

**Comment by nturato** [comment]
Please take a closer look at the condition, the first opening parenthesis is in the wrong place!

if $action is "" than 'text/plain' will be used, because "" == false .

BTW, that's what I'm trying to do.
```
      $response = $this->client()->post(Mailjet\Resources::$NewsletterSend, ["id" => $newsletterId]);
```

**Comment by GuillaumeBadi** [comment]
My bad, It's now fixed! Thanks for the bug review!

Best,
Guillaume
