### ISSUE TITLE
Sender confirmation email problem

### ISSUE THREAD

**Issue by JYw2m** [mailjet/mailjet-apiv3-php#132]
Hello,

when I add new sender address with api , I received the response success and the sender is added in the BO .
And I take the id to validate the email address. Like this
$response = $mj->post(Resources::$SenderValidate,['id'=> $idSender]);
I don't received the email confirmation but the response is success .The answer is like this :
array(3) {
["ValidationMethod"]=>
string(15) "ActivationEmail"
["Errors"]=>
array(2) {
["FileValidationError"]=>
string(0) ""
["DNSValidationError"]=>
string(0) ""
}
["GlobalError"]=>
string(0) ""
}

Could you help me please ?
Thx,

**Comment by kmanchikov** [comment]
Hey there, 

Thank you for reporting this issue to us. We have been aware of that behavior since some days back, and we are currently working on it's resolution, as we do understand that this is an important part of how you are using our API. 

As a workaround and ones this issue has been resolved, you could do the validation through the front-end which would trigger the Validation Email. 

Let us know if you do have any further questions or concerns, as I would be happy to revert back. 

Best, 
Krassimir

**Comment by ymilhahn** [comment]
I can confirm that this issue still exists.

My CURL request:
```
curl -X POST \
  https://api.mailjet.com/v3/REST/sender/XXXXX/validate \
  -H 'Authorization: Basic YYYYY' \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{}'
```
(Authorization and ID changed)

The response:
```
{
    "ValidationMethod": "ActivationEmail",
    "Errors": {
        "FileValidationError": "",
        "DNSValidationError": ""
    },
    "GlobalError": ""
}
```
Any news on the resolution?
Thank you very much!

**Comment by kmanchikov** [comment]
Hey Yannick, 

I am sorry to inform you that the issue is still persisting, and the only workaround would be through the front-end for now. Once this one is resolved, I would let you know right away. 

Best,
Krassimir

**Comment by flanagansshenanigans** [comment]
I'm still having this issue. Is there any idea of a time frame of getting this fixed?

**Comment by flanagansshenanigans** [comment]
Do any of the developers actually use github? not being able to sending validation emails via the api should be a big issue... without sending validation emails is kind of a big issue, especially if your client's are sending email on behalf of their clients. I get doing it manually still works... but shouldn't that mean it should be easier to fix?

**Comment by adamyanliev** [comment]
Hello,

Apologies for the delayed response. This issue has been resolved, I'll explain what's the current workflow below:

 - when you do a POST on `/sender` , once the new sender is created the validation email is automatically sent out. there is no need to use the `/sender/{ID}/validate` endpoint. 
- if you have a sender email that has not been validated, or you have a deleted sender email that you want to activate, do a POST on `/sender/{ID}/validate` and the validation email will be sent out.

I hope this helps.

Regards,
Atanas
