### ISSUE TITLE
ContactManagemanycontacts 404 Status

### ISSUE THREAD

**Issue by nadar** [mailjet/mailjet-apiv3-php#133]
We are building a Mailjet component for LUYA (luya.io) and Yii Framework => https://github.com/luyadev/luya-mailjet

One of the features should be an easy integration of sync contacts inside on or multiple lists. So we followed the example https://dev.mailjet.com/guides/?php#managecontactslists

But what ever we do, $response->getStatus() always returns a 404. 

This is a var_dump of $body:

```
array(2) {
  ["Contacts"]=>
  array(2) {
    [0]=>
    array(1) {
      ["Email"]=>
      string(16) "basil+1@nadar.io"
    }
    [1]=>
    array(1) {
      ["Email"]=>
      string(16) "basil+2@nadar.io"
    }
  }
  ["Action"]=>
  string(8) "addforce"
}
```
Assuming this code ($this->client holds the mailjet client instance).

```php
$response = $this->client->post(Resources::$ContactManagemanycontacts, ['body' => $body]);
```

We tryed to change the body in several ways, but a 404 status code say to me the enpoint is not found (as far as i understand http status codes).

Is there any known issue about this, or we made something complet wrong?

(The used key and secret works, cause we also implemented transactional mails which works perfect, also with templates)

**Comment by nadar** [comment]
I got the problem. For everyone else: 

**do not use version 3.1 in singleton client instance** - observe the version 3.1 only for send mail in the specific request.

**Comment by FedericoBiccheddu** [comment]
I have the same problem without changing the code in the last weeks.

This is the snippet:
```php
<?php

use Mailjet\Client;
use Mailjet\Resources;

final class Subscribe
{
    /**
     * @var \Mailjet\Client
     */
    private $mailjet;

    public function __construct()
    {
        $this->mailjet = new Client(env('MAILJET_KEY_PUBLIC'), env('MAILJET_KEY_SECRET'));
    }

    public function __invoke(Request $request)
    {
        if ($request->has(['email', 'game'])) {
            $response = $this->mailjet->post(Resources::$ContactslistManagemanycontacts, [
                'id' => 'LIST_ID',
                'body' => [
                    'Action' => 'addnoforce',
                    'Contacts' => [
                        [
                            'Email' => $request->input('email'),
                            'Properties' => [
                                'property' => 'Property'
                            ]
                        ]
                    ]
                ],
            ]);
        }

        var_dump($response); exit;
    }
}
```

And this is the dump:
```
object(Mailjet\Response)#204 (5) {
  ["status":"Mailjet\Response":private]=>
  int(404)
  ["success":"Mailjet\Response":private]=>
  bool(false)
  ["body":"Mailjet\Response":private]=>
  array(3) {
    ["ErrorInfo"]=>
    string(0) ""
    ["ErrorMessage"]=>
    string(16) "Object not found"
    ["StatusCode"]=>
    int(404)
  }
}
```

Config for the installed package:
```php
class Config
{
    const WRAPPER_VERSION = 'v1.4.1';
    const USER_AGENT = 'mailjet-apiv3-php/';
    const MAIN_VERSION = 'v3';
    const MAIN_URL = "api.mailjet.com";
    const SECURED = true;
    const SMS_VERSION = 'v4';
}
```

**Comment by FedericoBiccheddu** [comment]
In the real code is my contact list id and is numeric, like **1234567**. The code was working something like one week ago.
