### ISSUE TITLE
How can I delete a Contact?

### ISSUE THREAD

**Issue by HimmelsW** [mailjet/mailjet-apiv3-php#135]
I've tried the following code with a list which worked fine,
but why is it not possible to delete a contact?
As per GDPR this option should be given. 

```php
$mj = new \Mailjet\Client('xxx', 'xxx');
$params = array(
        "ID" => 'xxx'
    );
$mj_send = $mj->delete(Resources::$Contact, $params);
```

**Comment by kmanchikov** [comment]
Hey there, 

As we speak we are developing a solution that would allow you to delete a contact via our API, however this is currently not available since this functionality hasn't been pushed to production yet. As a workaround I would recommend contacting our Support channel were such requests would be handled and completed with priority by them, until we release the solution. 

Best, 
Krassimir

**Comment by HimmelsW** [comment]
Thanks @kmanchikov !

**Comment by LrntL** [comment]
To maximize your chance with GDPR, you only can unsubscribe or remove a contact from a list, not delete it.

**Comment by abambova** [comment]
Closing this issue as it has been answered. Please feel free to post a new issue if needed.

**Comment by Cyrille37** [comment]
This php framework does not implements contact deletion, but from the [api doc](https://dev.mailjet.com/email/guides/contact-management/#gdpr-delete-contacts) using the API v4 it's possible.

So u need to create a MjClient with `$version=>'v4'` then pass resource `['contacts', '']` to client delete command.

**Comment by LrntL** [comment]
> This php framework does not implements contact deletion, but from the [api doc](https://dev.mailjet.com/email/guides/contact-management/#gdpr-delete-contacts) using the API v4 it's possible.
> 
> So u need to create a MjClient with `$version=>'v4'` then pass resource `['contacts', '']` to client delete command.

Thank you! For those who want more information on how to deal with this with PHP (assuming you found your contact ID before):

```
$ch = curl_init();
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "DELETE");
curl_setopt($ch, CURLOPT_URL, "https://api.mailjet.com/v4/contacts/".$MyContactID);
curl_setopt($ch, CURLOPT_USERPWD, MJ_APIKEY_PUBLIC.":".MJ_APIKEY_PRIVATE);  

$options = array(
	  CURLOPT_RETURNTRANSFER  => true,
	  CURLOPT_HEADER => false,
	  CURLOPT_FAILONERROR => true,
	  CURLOPT_SSL_VERIFYHOST => false,
	  CURLOPT_SSL_VERIFYPEER  => false
);

curl_setopt_array($ch, $options);

// Execute
$result = curl_exec($ch);
```
