### ISSUE TITLE
Mailjet Sub-Account does not work for given API

### ISSUE THREAD

**Issue by nadar** [mailjet/mailjet-apiv3-php#137]
We have made a client library to add Sections trough API (https://github.com/luyadev/luya-mailjet/blob/master/src/Sections.php#L29-L63) This works perfect (even we had to reverse engineer how passport accepts mjml, but thats another topic [mjml to json parser => https://github.com/luyadev/luya-mailjet/blob/master/src/Mjml.php]).

Now have created a *SUB account in the mailjet UI*, but it seems that those API keys are not allowed to make calls to the `Resources::$Template` endpoint. Can someone confirm this behavior?

We where already asking the the mailjet support, but they just give us "none sense" answers like `remove the if statement` ....  so we are trying to get some answers here from the devs.

Again in short form:
- **creating sections if with a main account works perfect**
- **creating sections trough the same code with a SUB ACCOUNT does not work**

regards,
basil

**Comment by kmanchikov** [comment]
Hey Basil, 

Could you let me know if I understood correctly. You do have a template containing an conditional statement, which apparently seems to be working for the main account but when having the same condition for the sub-account you receive an error message that you are not allowed to make calls to our /template resource ? 

Let me know if that is correct or not. Also it would be a good idea if you could provide me with the ticket number, perhaps I could find more information from the ticket as well. 

Best, 
Krassimir

**Comment by nadar** [comment]
Hi @kmanchikov 

No, its not about conditions. We figured out that sub accounts are not able to create sections.

You can even try out by yourself: 

1. git clone https://github.com/luyadev/luya-mailjet
2. run `composer install`
3. add your credentials with main account (https://github.com/luyadev/luya-mailjet/blob/master/tests/MailjetTestCase.php#L18-L19)
4. run `./vendor/bin/phpunit tests/SectionsTest.php` **this will successfull create the section in your templates sections.
5. change the credentials from a sub account (in step 3)
6. run tests from step 4 again and you will see the exception.

```
array (
 'ErrorIdentifier' => '902437f5-8375-46a3-8caa-c73c6046835e',
 'StatusCode' => 401,
 'ErrorMessage' => 'API key authentication/authorization failure. You may be unauthorized to access the API or your API key may be expired. Visit API keys management section to check your keys.',
```

**Comment by nadar** [comment]
@kmanchikov ah and i forgot: ticket number is 956652

**Comment by ngarnier** [comment]
Hey, you can create sections with a subaccount. The issue here is that you set `OwnerType` to be `user`. This is valid for the Master API Key but invalid for a subaccount. Please try again by setting `OwnerType` to `apikey` when creating a section on a subaccount.

**Comment by nadar** [comment]
Thanks! This works perfect

**Comment by ngarnier** [comment]
Indeed when creating a template via API, the MJMLContent must be in JSON format. You can also find a node lib to translate XML syntax into JSON syntax here: https://github.com/mjmlio/mjml2json. 

I don't think the version attribute is necessary though.

About the preview, it is generated when the template/section is opened in Passport, the API doesn't create the previews, so it will be empty until the template/section has been opened in Passport.
