### ISSUE TITLE
Cannot install package for 

### ISSUE THREAD

**Issue by saimiris** [mailjet/mailjet-apiv3-php#138]
Hi there,

I am using Laravel 5.6 and I cannot install your package. Here is log:

> Your requirements could not be resolved to an installable set of packages.

>   Problem 1
>     - Can only install one of: laravel/framework[v5.6.38, 5.4.x-dev].
>     - Can only install one of: laravel/framework[5.4.x-dev, v5.6.38].
>     - Can only install one of: laravel/framework[5.4.x-dev, v5.6.38].
>     - mailjet/laravel-mailjet 1.1.0 requires laravel/framework 5.4.* -> satisfiable by laravel/framework[5.4.x-dev].
>     - Installation request for mailjet/laravel-mailjet ^1.1 -> satisfiable by mailjet/laravel-mailjet[1.1.0].
>     - Installation request for laravel/framework == 5.6.38.0 -> satisfiable by laravel/framework[v5.6.38].

> Installation failed, reverting ./composer.json to its original content.

**Comment by todorDim** [comment]
Hello @saimiris,

There is another package for Laravel - https://github.com/mailjet/laravel-mailjet. 
We're currently working on updating the version to 5.6. Please check it out and let us know if you have any questions.

Regards,
T.

**Comment by abambova** [comment]
Hello @saimiris,

The new version is available so I'll close the issue. Please feel free to open a new one if you need it. Thanks, Aneliya
