### ISSUE TITLE
Add contact, Error 500

### ISSUE THREAD

**Issue by DevHeaven** [mailjet/mailjet-apiv3-php#156]
When I simply try to add a contact it returns "An Unexpected Error occurred during API request" with a status code 500. This is my code, what am I doing wrong here ?

`	use \Mailjet\Resources;
	$apikey = "myapikey";
	$apisecret = "myapisecret";

	$mj = new \Mailjet\Client($apikey, $apisecret);
	
	$params = array(
		"id" => "10168",
		"Email" => "me@example.com",
		"Name" => "My Name",
		"Action" => "addforce"
		);
	
	$response = $mj->post(\Mailjet\Resources::$ContactslistManagecontact, $params);
`

**Comment by mskochev** [comment]
Hi DevHeaven,

The ID and body should be added separately like that:
```php
$params = array(
	"Email" => "me@example.com",
	"Name" => "My Name",
	"Action" => "addforce"
	);

$response = $mj->post(\Mailjet\Resources::$ContactslistManagecontact, ['id' => 123456, 'body' => $params]);
```

**Comment by DevHeaven** [comment]
@mskochev and apparantly I wasn't smart enough to figure that one out myself :-p
