### ISSUE TITLE
Dist directory not nessecary 

### ISSUE THREAD

**Issue by flug** [mailjet/mailjet-apiv3-php#16]
The dist directory is not necessary in repository . You have an Release section for not composer package and Packagist for composer. 
Having a zip which regularly changes will overload the repository for nothing, and in addition the zip is not usable in the state. We must decompress and eventually stop using the repository. :-/

**Comment by Narno** [comment]
:+1:

**Comment by GuillaumeBadi** [comment]
This folder was originally meant for people on shared hosting services. We had complains from people begining with php programming, who couldn't fetch the dependencies with composer on shared hosting servers. We might upload it in a side branch to still make it available.

**Comment by flug** [comment]
You made of releases suddenly the zip of these releases replaces the dist folder. If in case it is necessary to exclude at least in the composer.json

**Comment by GuillaumeBadi** [comment]
I think we can ignore it with a `.gitattribute` file. Don't know if it will work with composer

**Comment by flug** [comment]
I explain to you:
Is deployed, during deployment we do a "composer install", you install the dependencies and then we come to your repository and there saw that your repository will be polluted with the zip that you will add to every update of the forward stroke it going take a time not possible and as a place on the server that ultimately will serve nothing. While there is the release that are made for it and is even a "download zip" button that finally did the same job as your file and you do not even need to handle it. And if you really have ben user complaints you put it in your README to finish not know if there be one or the other needs to exchange business

**Comment by flug** [comment]
Like I said the zip is 14MB each 14mb + 14mb etc ... change the repository will explode in size
