### ISSUE TITLE
Easily get error when sending v3.1

### ISSUE THREAD

**Issue by LrntL** [mailjet/mailjet-apiv3-php#162]
Hi,

I use the following code to send a mail via API 3.1.

```
$body = [...];

$response = $mj->post(Resources::$Email, ['body' => $body]);

if ($response->success())
{
	return $response->getData();
}
return false;
```

I would like, instead of `$response->success()` and `return false`, to get the error code and message (Recipient malformed, templte ID not existing, etc) and store it in my log.

Can somebody give me a short example on how to do that?
I am lost in documentation... and found no example.

Just like if sending is ok return data, if not return the error code and the error details.
Thanks in advance

**Comment by LrntL** [comment]
I added that at the end of my function.
Not sure if it is the best way...

```
$response = $mj->post(Resources::$Email, ['body' => $body]);
$dataResponse = $response->getData();
	
$result = array(
	'Status' => $dataResponse['Messages'][0]['Status'],
	'MessageUUID' => $dataResponse['Messages'][0]['To'][0]['MessageUUID'],
	'MessageID' => $dataResponse['Messages'][0]['To'][0]['MessageID'],
	'MessageHref' => $dataResponse['Messages'][0]['To'][0]['MessageHref'],
	'ErrorIdentifier' => $dataResponse['Messages'][0]['Errors'][0]['ErrorIdentifier'], 
	'ErrorCode' => $dataResponse['Messages'][0]['Errors'][0]['ErrorCode'], 
	'StatusCode' => $dataResponse['Messages'][0]['Errors'][0]['StatusCode'], 
	'ErrorMessage' => $dataResponse['Messages'][0]['Errors'][0]['ErrorMessage'], 
	'ErrorRelatedTo' => json_encode($dataResponse['Messages'][0]['Errors'][0]['ErrorRelatedTo'])
);	
	
return $result;
```

Then I get $result and perform action using if/else on `$result['Status']`

If someone has got better, I will take a look!

**Comment by FerhanGit** [comment]
Hi, you can use `$response->getReasonPhrase()` to get the error message and $response->getStatusCode() - for http status code.

**Comment by LrntL** [comment]
Thank you for your reply :)

Unfortunately, get with v3.1 API, I have `getStatusCode()` is undefined and `getReasonPhrase()` only give me `OK` or `bad request`.

For now, I'm going to keep my method but it's a little risky to reach the information in the arrays with a key equal to zero Example: `$dataResponse['Messages'][0]['Errors'][0]['ErrorCode'])`, this does not look like clear code, I don't really like it but it works...

I keep this issue opened a little while to see if somebody has a different approach but thank you for answering so quickly!

**Comment by FerhanGit** [comment]
In fact the correct way to get the http code is `$response->getStatus()`, as it seems to be a wrapper of Guzzle`s `getStatusCode()` - https://github.com/mailjet/mailjet-apiv3-php/blob/master/src/Mailjet/Response.php#L35

**Comment by LrntL** [comment]
Thank you FerhanGit!

I choose to make a mix with all my `$dataResponse` and `$response->getStatus()` to mark my message as sent or not with the details.
