### ISSUE TITLE
Any solution to schedule two campaigns with same contact email and different contact properties ?

### ISSUE THREAD

**Issue by dbyzero** [mailjet/mailjet-apiv3-php#165]
I use MJML to send mail with mailjet and I populate the body of my mail with contact properties. My problem is if I have the same contact on both campaign, I cannot split contact properties... any suggestion to fix it ?

I think about :
- store the whole mail information as contact properties and inject in mail template body the information
- dupplicate contact properties by compaign

... no nice solutions there.

**Comment by ngarnier** [comment]
Hey @dbyzero, 

Could you please give more info on your use case? I struggle understanding what "both campaigns" are (what is their relationship), and why you need to "split contact properties"?

**Comment by uavn** [comment]
Closing, because this issue has no answer from requester for a while and can not be investigated without requested details.
