### ISSUE TITLE
How to get a variable into a template during the campaign-sending process?

### ISSUE THREAD

**Issue by patrickmaynard** [mailjet/mailjet-apiv3-php#166]
I have the following function:

    public function sendCampaign($listName, $config, $vars) {
        //First we need to set up a draft of the campaign.
        $listId = $this->config['lists'][$listName];
        $title = $config['subject'] . "_" . time();
        $requestBodyOne = [
            'Locale' => 'de_DE',
            'Sender' => $config['fromName'],
            'SenderEmail' => $config['fromEmail'],
            'Subject' => $config['subject'],
            'ContactsListID' => $listId,
            'TemplateID' => $config['template'],
            'Title' => $title,
            'IsTextPartIncluded' => false
        ];
        $responseOne = $this->client->post(Resources::$Campaigndraft, ['body' => $requestBodyOne]);

        dump($responseOne);

        if(!$responseOne->success()) {
            $responseOne->getStatus();
        }

        $data = $responseOne->getData();
        $draftId = $data[0]['ID'];

        //Now we add our body to the draft
        $requestBodyTwo = [
            'Vars' => ['body' => $vars['body']] //Both capitalized and lowercase results in 400 error: "Properties not supported in JSON payload"
        ];
        $responseTwo = $this->client->post(Resources::$CampaigndraftDetailcontent, ['id' => $draftId, 'body' => $requestBodyTwo]);
        if(!$responseTwo->success()) {
            $responseTwo->getStatus();
        }

        dump($responseTwo);

        //Now we can send the campaign
        $responseThree = $this->client->post(Resources::$CampaigndraftSend, [
            'id' => $draftId
        ]);

        die(dump($responseThree));
    }

... but it gives me a 400 error. Clearly the 'Vars' key is not supported. Is there an alternative that will allow me to include template variables in my template?

**Comment by patrickmaynard** [comment]
Closing the loop on this: We ended up using the /send endpoint and feeding in a value for `MJ-campaign`. That did the trick.

https://dev.mailjet.com/reference/email/send-emails/

**Comment by Colir** [comment]
+1 .
Just want to know if it's possible or not.
The idea is to use a template stored on Mailjet , to keep header and footer, and inject variables to define content for a campaign. The main idea is also to not use the send API, to keep mailjet's feaure like, image hosting, text part generation,etc.
Thank you
