### ISSUE TITLE
MessageID type is Double

### ISSUE THREAD

**Issue by raffismartpadpro** [mailjet/mailjet-apiv3-php#167]
Hi, good day. I would like to ask if it is really normal when sending email, the value of MessageID is string.

`"MessageID" => "576460753067090994"`

But in the Events API, I am getting a double.

`"MessageID":1.152921505370435e+18`

PHP is converting it automatically to exponent.

What should I do to get the actual ID? Thanks.

**Comment by kmanchikov** [comment]
Hi @raffismartpadpro, 

In regards to this one, I would suggest you the "message_guid" value and not the "messageID" one as it's a more reliable source. To be honest I haven't seen that behavior within my PHP env when it comes to accepting events, but I will be happy to look into this one if you have any real examples.
