### ISSUE TITLE
SSL_ERROR_SYSCALL in connection to api.mailjet.com:443

### ISSUE THREAD

**Issue by danieldimit** [mailjet/mailjet-apiv3-php#169]
Hello I get the following error when trying to send email and sms: 

`request.CRITICAL: Uncaught PHP Exception GuzzleHttp\Exception\ConnectException: "cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.mailjet.com:443  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)" at /.../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 185 {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.mailjet.com:443  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at /.../vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185)"} []`

It happens from time to time even though I don't change the code. Do you know what might be the cause of it?

**Comment by abambova** [comment]
Hello @danieldimit,

Could you please precise how you are trying to send an email, via the API? A code snippet will be really helpful.

Thanks,

Aneliya

**Comment by cabotiau** [comment]
Hello @danieldimit,

I had exactly the same error, and I solve the problem with Mailjet support. When you fail to authenticate to the Mailjet API, your server IP is blocked during 1 hour. I didn't do any error, but someone on the same shared hosting did. I think the error was run with a CRON repeated every hour. So my two separate hosting accounts (on the same IP) using Mailjet API were blocked. Juste after changing hosting (and IP) for the first and bought an option to have a dedicated IP for the second one, everything was working like a charm.

**Comment by danieldimit** [comment]
@cabotiau thank you. It only happened during the integration tests on my local machine and on the jenkins server. I guess they happened because during testing we use a non-existent SMS API token, which gets the IP of the executing computer blocked for an hour. Now we've created a Mock class, which doesn't do any calls to the Mailjet API at all. On production we've never had those problems, so this explains it.

@abambova I've provided the code below. On production it never failed. Just locally after executing tests with an SMS API token which is not valid (so that we wouldn't waste money on test SMSs).
````
<?php
namespace App\Service;
use Mailjet\Client;
use Mailjet\Resources;
use Psr\Log\LoggerInterface;
class MailjetService
{
    const RETRIES = 5;
    const DELAY = 3;
    private $mailer;
    private $senderName;
    private $senderAddress;
    private $logger;
    private $smsToken;
    private $smsSenderName;
    private $client;
    public function __construct(string $senderName, string $senderAddress, string $smsSenderName, string $smsToken, Client $mailer, LoggerInterface $logger)
    {
        $this->mailer = $mailer;
        $this->senderName = $senderName;
        $this->senderAddress = $senderAddress;
        $this->logger = $logger;
        $this->smsToken = $smsToken;
        $this->smsSenderName = $smsSenderName;
        $this->client = new Client($this->smsToken,
            NULL, true,
            ['url' => "api.mailjet.com", 'version' => 'v4', 'call' => false]
        );
    }
    public function sendMail($subject, $recipientAddress, $recipientName, $html = '', $text = '')
    {
        $message = [
            'FromEmail' => $this->senderAddress,
            'FromName' => $this->senderName,
            'Subject' => $subject,
            'Text-part' => $text,
            'Html-part' => $html,
            'Recipients' => [
                [
                    'Email' => $recipientAddress,
                    'Name' => $recipientName
                ]
            ]
        ];
        $response = $this->mailer->post(Resources::$Email, ['body' => $message]);
        if (!$response->success()) {
            $this->logger->critical('Could not send mail to: ' . $this->senderAddress . '.  Message: ' . json_encode($message),
                $response->getBody());
        }
        return $response->success();
    }
    public function sendSMS($to, $text) {
        $counter = 0;
        do {
            try {
                $this->sms($to, $text);
                return true;
            } catch (\Exception $e) {
                sleep(static::DELAY);
            }
        } while (++$counter < static::RETRIES);
        $this->logger->critical('Could not send confirmation sms to: ' . $to);
        return false;
    }
    private function sms($to, $text) {
        $postPayload = [
            'Text' => $text,
            'To' => $to,
            'From' => $this->smsSenderName,
        ];
        $response =$this->client->post(Resources::$SmsSend, ['body' => $postPayload]);
        if (!$response->success()) {
            $this->logger->critical('Could not send SMS, error: ' . $to . '.  Message: ' . $text,
                $response->getBody());
            throw new \UnexpectedValueException('Unexpected HTTP status code ' . $response->getStatus() . ' while sending a SMS.');
        }
    }
}
`````

**Comment by uavn** [comment]
Closing because already answered
