### ISSUE TITLE
Remove PHP end tag

### ISSUE THREAD

**Issue by flug** [mailjet/mailjet-apiv3-php#17]
On you php classes remove end tag php, is not necessary and it avoids some problems with carriage returns
https://github.com/mailjet/mailjet-apiv3-php/blob/master/src/Mailjet/Request.php#L140

**Comment by Narno** [comment]
http://www.php-fig.org/psr/psr-2/#2-general

**Comment by flug** [comment]
This is exactly what I say: The closing ```?>``` tag MUST be omitted from files containing only PHP.

**Comment by GuillaumeBadi** [comment]
I didn't know that! Thanks !
