### ISSUE TITLE
Fatal error: Class 'GuzzleHttp\Handler\Proxy' not found (non-composer)

### ISSUE THREAD

**Issue by Starystars67** [mailjet/mailjet-apiv3-php#170]
Hi guys, as the title suggests I am getting the error Fatal error: Class 'GuzzleHttp\Handler\Proxy' not found. Here is a screenshot of the full error:
![image](https://user-images.githubusercontent.com/15389482/58360960-81805e80-7e83-11e9-892e-9b5d8908db70.png)

Does anyone have any ideas how to resolve this? 
Here is my file/folder structure:
![image](https://user-images.githubusercontent.com/15389482/58360991-9d840000-7e83-11e9-8463-21bb6dc6152e.png)
As im sure you can tell, the rest of the system is loading just fine except this.
Any help much appreciated.

I do not have access to composer unfortunately so that is not an option for any suggestions.

Original post as i felt that it was more a correct place for it but there seems to be no support there so fair enough it does kind of say that. https://github.com/mailjet/mailjet-apiv3-php-no-composer/issues/4

**Comment by uavn** [comment]
@Starystars67, check if this file exists:
......./vendor/guzzlehttp/guzzle/src/Handler/Proxy.php

seems like no and the issue it with your vendor directory, it is not complete enough

**Comment by Starystars67** [comment]
Hi there, Thank you for the reply however this was over a year ago now. The issue was resolved by moving host in the end. Sorry for the lack in update.

Thank you for your reply anyway.
