### ISSUE TITLE
Unable to filter status of template when retrieving list of template

### ISSUE THREAD

**Issue by anthonytdev** [mailjet/mailjet-apiv3-php#174]
Hi,

I'd like to filter (or at least to know) the status of template when retrieving list of template
https://dev.mailjet.com/reference/email/templates/#v3_get_template

When using the mailjet API GET ``\template``, the list return all template without status
Actual possible status of template are draft or published

Using the ``Mj-TemplateID`` when sending email with draft template work (reponse status 200) but are blocked by mailjet

**Comment by kmanchikov** [comment]
Hi, 

When it comes through the API and the `/template` endpoint there the content presented on the API `/template/$ID/detailcontent` would always be the published one, thus implying that the API currently cannot differentiate between Draft and Published so it would always choose what is Published. 

Here it's a perfect place to mention that when doing a POST to update or publish a new content to the template through the API this content would always be a Published one.

**Comment by uavn** [comment]
Answered, closing.
