### ISSUE TITLE
BCC field is added to TO

### ISSUE THREAD

**Issue by de-raaf-media** [mailjet/mailjet-apiv3-php#175]
Hi,

Great work on this package. I just noticed one severe issue. The BCC value is added to the TO
value. The mail that is sent had info@example, test@example.com in the TO field. Is there a workaround for this?

Mail::to('info@example.com')
            ->bcc('test@example.com')
            ->send(new SendToken());

Regards,
Mark

**Comment by kmanchikov** [comment]
Hi, 

That one is an interesting finding to be honest. 

Would you be that kind to post the example API Call or SMTP along with the Headers of the message so we could investigate this a bit further and indeed check were the issue might be coming from. 

You could open a Support ticket through here ( https://www.mailjet.com/feature/support/ ) with all the details included.

**Comment by uavn** [comment]
```
$mj = new \Mailjet\Client($key, $secret, true, ['version' => 'v3.1']);

$body = [
    'Messages' => [
        [
            'From' => [
                'Email' => $from,
                'Name' => "Mailjet Pilot"
            ],
            'To' => [
                [
                    'Email' => $to,
                    'Name' => "passenger 1"
                ]
            ],
            'Bcc' => [
                [
                    'Email' => $to,
                    'Name' => "passenger 2"
                ]
            ],
            'TemplateID' => 1720107,
            'TemplateLanguage' => true,
            'Subject' => "Your email flight plan!",
            'Variables' => [
                'body' => "Body test",
                'subject' => "Subject test"
            ]
        ]
    ]
];

$response = $mj->post(\Mailjet\Resources::$Email, ['body' => $body]);
```

this works as expected without *bcc* near the *to*
