### ISSUE TITLE
Sorting get contact endpoint

### ISSUE THREAD

**Issue by kpitn** [mailjet/mailjet-apiv3-php#178]
Hi,

In your documentation you said :

> Specify a property name for this query parameter to sort the objects in Data. By default the sorting is ascending. When a property name is postfixed with DESC (i.e. property_name+DESC), the sort order will be descending.
> 
> Note: Both the Sort query parameter and the option to select a descending order are not available for every property.

I have tried to sort like this
```php
            $body = [
                'ContactsLists' => $this->config->getContactList(),
                'filters' => [
                    'Limit' => 100,
                    'IsExcludedFromCampaigns' => true,
                    'Sort' => 'ExclusionFromCampaignsUpdatedAt Desc'
                ]
            ];
            $response = $api->get(Resources::$Contact, $body);
```

I try 
* ExclusionFromCampaignsUpdatedAt
* LastActivityAt
* CreatedAt

Can we use sort filter ?
All i got is :

> Unexpected error during GET: Invalid sort specification: Cannot sort on field lastactivityat

**Comment by uavn** [comment]
Here is working example of sorting by CreatedAt for example:
```
$mj = new \Mailjet\Client($key, $secret, true, ['version' => 'v3']);

$body = [
    'ContactsLists' => 41819,
    'filters' => [
        'Limit' => 100,
        'Sort' => 'CreatedAt DESC'
    ]
];
$response = $mj->get(Resources::$Contact, $body);

print_r($response->getStatus());
echo ':';
print_r($response->getReasonPhrase());
echo ':';
print_r($response->getData());
```

works fine

**Comment by liamcharmer** [comment]
Out of curiosity, how are we able to get an individual Contact based on just the email address (as the ID is not available at that current point) 


I've tried
```
$ContactResponse = $mj->get(Resources::$Contact, ['contact_email' => urlencode($user->email)]);
```

But it just returns an array of all the contacts.

**Comment by liamcharmer** [comment]
> Out of curiosity, how are we able to get an individual Contact based on just the email address (as the ID is not available at that current point)
> 
> I've tried
> 
> ```
> $ContactResponse = $mj->get(Resources::$Contact, ['contact_email' => urlencode($user->email)]);
> ```
> 
> But it just returns an array of all the contacts.

Sorry, discovered it needed to be 

```
$ContactResponse = $mj->get(Resources::$Contact, ['id' => urlencode($user->email)]);

```
