### ISSUE TITLE
Can I include html in transactional templates?

### ISSUE THREAD

**Issue by NeftaliAcosta** [mailjet/mailjet-apiv3-php#180]
I have a predesigned template for transactional coordinates. In it I have 2 variables: Name and html

In the viable html I want to send dynamic content to be incorporated into the template. How can I do this?

Thank you.

![image](https://user-images.githubusercontent.com/15948880/67154766-2a15db80-f2c7-11e9-81e2-1fa1af9f3af9.png)

![image](https://user-images.githubusercontent.com/15948880/67154771-3732ca80-f2c7-11e9-9ddb-1a5ba015ee64.png)

![image](https://user-images.githubusercontent.com/15948880/67154773-40bc3280-f2c7-11e9-817f-b1854e42942d.png)

![image](https://user-images.githubusercontent.com/15948880/67154783-752fee80-f2c7-11e9-9702-02704538079c.png)

**Comment by uavn** [comment]
@NeftaliAcosta 

Here is working example:

```
$mj = new \Mailjet\Client($key, $secret, true, ['version' => 'v3.1']);

$body = [
    'Messages' => [
        [
            'From' => [
                'Email' => $from,
                'Name' => "Template Sample"
            ],
            'To' => [
                [
                    'Email' => $to,
                    'Name' => "passenger 1"
                ]
            ],
            'TemplateID' => 1720107,
            'TemplateLanguage' => true,
            'Subject' => "Subject Test 3 {{var:subject}}",
            'Variables' => [
                "subject" => "Subject test",
                "test" => "<h1>Body test</h1>"
            ]
        ]
    ]
];

$response = $mj->post(\Mailjet\Resources::$Email, ['body' => $body]);
$response->success();
```

![Screenshot from 2020-09-24 23-51-14](https://user-images.githubusercontent.com/315338/94199070-f07b2680-fec0-11ea-8b32-af4ac91ee08b.png)

**Comment by uavn** [comment]
![Screenshot from 2020-09-24 21-37-40](https://user-images.githubusercontent.com/315338/94199139-07217d80-fec1-11ea-9b92-4f0c09bce929.png)

**Comment by NeftaliAcosta** [comment]
> @NeftaliAcosta
> 
> Here is working example:
> 
> ```
> $mj = new \Mailjet\Client($key, $secret, true, ['version' => 'v3.1']);
> 
> $body = [
>     'Messages' => [
>         [
>             'From' => [
>                 'Email' => $from,
>                 'Name' => "Template Sample"
>             ],
>             'To' => [
>                 [
>                     'Email' => $to,
>                     'Name' => "passenger 1"
>                 ]
>             ],
>             'TemplateID' => 1720107,
>             'TemplateLanguage' => true,
>             'Subject' => "Subject Test 3 {{var:subject}}",
>             'Variables' => [
>                 "subject" => "Subject test",
>                 "test" => "<h1>Body test</h1>"
>             ]
>         ]
>     ]
> ];
> 
> $response = $mj->post(\Mailjet\Resources::$Email, ['body' => $body]);
> $response->success();
> ```
> 
> ![Screenshot from 2020-09-24 23-51-14](https://user-images.githubusercontent.com/315338/94199070-f07b2680-fec0-11ea-8b32-af4ac91ee08b.png)

Thanks.
