### ISSUE TITLE
I want to send mailjet templates and stored the emails in an contact list

### ISSUE THREAD

**Issue by dinesh10000** [mailjet/mailjet-apiv3-php#184]
I want to send mailjet templates to an user when bootstrap form submit and stored their emails in an contact list using php

**Comment by uavn** [comment]
@dinesh10000 
First, get your contacts using API endpoint https://dev.mailjet.com/email/reference/contacts/contact#v3_get_contact
Then send them email with TemplateID using this endpoint:
https://dev.mailjet.com/email/reference/send-emails#v3_1_post_send
