### ISSUE TITLE
Bulk Emails not Sending

### ISSUE THREAD

**Issue by lwaters5** [mailjet/mailjet-apiv3-php#185]
I am trying to send bulk emails from a web form. The email list is gathered from a recordset and equal to $emailaddress3. If I enter only one email in the To, Email field then it sends the email but, if I make the To, Email equal to $emailaddress3 then nothing works. 

Here is my code below. $emailaddress3 has the format of email1,email2,email3 Any help would be appreciated. Thank you. 

`<?php $subscription_users = new WA_MySQLi_RS("subscription_users",$sdpc_i,0); $subscription_users->setQuery("SELECT *, GROUP_CONCAT(email_address) as email_list FROM subscription left join users on subscription.userID = users.userID WHERE dataID = ?"); $subscription_users->bindParam("i", "".(isset($_GET['dataID'])?$_GET['dataID']:"") ."", "-1"); //colname $subscription_users->execute(); ?> <?php /* This call sends 2 messages to 2 different recipients. */ $email_address3 = $subscription_users->getColumnVal("email_list"); $notes2 = $data_admin->getColumnVal("notes"); $progress = $progress->getColumnVal("progress_email"); $declined = $data_admin->getColumnVal("declined_reasoning"); require 'mailjet/vendor/autoload.php'; use Mailjet\Resources; $apikey = 'my key'; $apisecret = 'my secret code'; $mj = new Mailjet\Client($apikey, $apisecret,true,['version' => 'v3.1']); $body = [ 'Messages' => [ [ 'From' => [ 'Email' => "no-reply@sdpc.a4l.org", 'Name' => "SDPC Registry" ], 'To' => [ [ 'Email' => $email_address3, ] ], 'Subject' => "Resource Request Progress Update for $software", 'TextPart' => "You are subscribed to receive updates on the New Request submitted for $software, by $district. The progress to date is listed below. Thank you.
$progress

$declined", 'HTMLPart' => "You are subscribed to receive updates on the New Request submitted for $software by $district. The progress to date is listed below. Thank you.
$progress

$declined" ] ] ]; $response = $mj->post(Resources::$Email, ['body' => $body]); $response->success() && var_dump($response->getData()); ?>`

**Comment by uavn** [comment]
Your problem that $email_address3 is getting list of emails from the database using GROUP_CONTACT MySQL function, which will give you list of emails joined by comma, something like that:
```
email1@mail.com, email2@mail.com, email3@mail.com
```

and then when you try to send this you will receive an error:
```
400:Bad Request:Array
(
    [Messages] => Array
        (
            [0] => Array
                (
                    [Status] => error
                    [Errors] => Array
                        (
                            [0] => Array
                                (
                                    [ErrorIdentifier] => 6355b669-d95b-4db0-9ae0-f0d422b02117
                                    [ErrorCode] => mj-0013
                                    [StatusCode] => 400
                                    [ErrorMessage] => "email1@mail.com, email2@mail.com, email3@mail.com" is an invalid email address.
                                    [ErrorRelatedTo] => Array
                                        (
                                            [0] => To[0].Email
                                        )
                                )
                        )
                )
        )
)
```

and to make your code work, you need to pass an array of emails to the "To" param, so change 
```
 'To' => [ [ 'Email' => $email_address3, ] ]
```
to the:
```
'To' => array_map(function($email) {
    return [
        'Email' => trim($email)
    ];
}, explode(',', $email_address3))
```

this will generate array of emails with correct key:
```
Array
(
    [0] => Array
        (
            [Email] => abonda@softserveinc.com
        )

    [1] => Array
        (
            [Email] => abonda@softserveinc.com
        )

)
````
