### ISSUE TITLE
Using Transactional Template with HTML Email Form

### ISSUE THREAD

**Issue by lwaters5** [mailjet/mailjet-apiv3-php#187]
I have a dymanic form on my website that uses the API to send the message to multiple emails. It works great. If I want to add a template header and footer to the design, how do I do this. I already created a transactional template with the header and footer but, how do I carry over the text of the body message entered on the website for the email to the template? Also the subject is dynamic. How can I carry this over to the template. What do I use for the transactional code to pull it from the website? Thank you.

**Comment by uavn** [comment]
Here is how:

```
$body = [
    'Messages' => [
        [
            'From' => [
                'Email' => $from,
                'Name' => "Template Sample"
            ],
            'To' => [
                [
                    'Email' => $to,
                    'Name' => "passenger 1"
                ]
            ],
            'TemplateID' => 1720107,
            'TemplateLanguage' => true,
            'Subject' => "Subject Test 3 {{var:subject}}",
            'Variables' => [
                "subject" => "Subject test",
                "test" => "Body test"
            ]
        ]
    ]
];

$response = $mj->post(\Mailjet\Resources::$Email, ['body' => $body]);
$response->success();

print_r($response->getStatus());
echo ':';
print_r($response->getReasonPhrase());
echo ':';
print_r($response->getData());
die;
```

![image](https://user-images.githubusercontent.com/315338/94185664-40042700-feae-11ea-8093-5e1409fd3862.png)
![image](https://user-images.githubusercontent.com/315338/94185682-44304480-feae-11ea-97e8-136f18f85fd3.png)
