### ISSUE TITLE
Endpoint '/contact/managemanycontacts/{job_ID}' implementation is incorrect

### ISSUE THREAD

**Issue by siminicam** [mailjet/mailjet-apiv3-php#189]
The cURL example in the documentation ([here](https://dev.mailjet.com/email/reference/contacts/bulk-contact-management#v3_get_contact_managemanycontacts_job_ID)) is incorrect:
`curl -s \
	-X GET \
	--user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
	https://api.mailjet.com/v3/REST/contact/$job_ID/managemanycontacts \`

Also the PHP implementation is incorrect. Bellow is an extract from the dump of the request object, part of the $response object, after testing the PHP example (which returns a 404 response code):
`object(Mailjet\Request)#2 (8) {
    ["method":"Mailjet\Request":private]=>
    string(3) "GET"
    ["url":"Mailjet\Request":private]=>
    string(68) "https://api.mailjet.com/v3/REST/contact/123456789/managemanycontacts"
    ["filters":"Mailjet\Request":private]=>
    array(0) {
    }
    ["body":"Mailjet\Request":private]=>
    NULL
`
As you can see, the Job ID parameter is incorrectly placed (same as in the cURL example).

Testing the endpoint '/contact/managemanycontacts/{job_ID}' in Postman works fine and returns the correct results

**Comment by Progression** [comment]
Encountered this same issue which still is rectified in the API documentation.
https://dev.mailjet.com/email/reference/contacts/bulk-contact-management#v3_get_contact_managemanycontacts_job_ID

The PHP library is working fine but MailJet needs to update the PHP code example (as well as the cURL example).
For the PHP call it should change from this on line 5:
`$response = $mj->get(Resources::$ContactManagemanycontacts, ['id' => $id]);`
To:
`$response = $mj->get(Resources::$ContactManagemanycontacts, ['actionid' => $id]);`

This ensures the job_id passed is placed correctly at the end of the request URL.

**Comment by uavn** [comment]
Answered, closing.
