### ISSUE TITLE
Endpoint '/contactslist/{list_ID or list_address}/managemanycontacts/{job_ID}' examples are missing a second parameter

### ISSUE THREAD

**Issue by siminicam** [mailjet/mailjet-apiv3-php#190]
The GET request examples  for the endpoint '/contactslist/{list_ID or list_address}/managemanycontacts/{job_ID}' ([link](https://dev.mailjet.com/email/reference/contacts/bulk-contact-management#v3_get_contactslist_list_ID_managemanycontacts_job_ID)) are incorrect. They are missing the second parameter accordingly to the source code (actionid)
Current incorrect cURL example:
`curl -s \
	-X GET \
	--user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
	https://api.mailjet.com/v3/REST/contactslist/$list_ID/managemanycontacts \`
Correct cURL example:
'curl -s \
	-X GET \
	--user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
	https://api.mailjet.com/v3/REST/contactslist/$list_ID/managemanycontacts/$job_id \'

Current incorrect PHP example:
`<?php
require 'vendor/autoload.php';
use \Mailjet\Resources;
$mj = new \Mailjet\Client(getenv('MJ_APIKEY_PUBLIC'), getenv('MJ_APIKEY_PRIVATE'),true,['version' => 'v3']);
$response = $mj->get(Resources::$ContactslistManagemanycontacts, ['id' => $id]);
$response->success() && var_dump($response->getData());
?>`

Correct PHP example:
`<?php
require 'vendor/autoload.php';
use \Mailjet\Resources;
$mj = new \Mailjet\Client(getenv('MJ_APIKEY_PUBLIC'), getenv('MJ_APIKEY_PRIVATE'),true,['version' => 'v3']);
$response = $mj->get(Resources::$ContactslistManagemanycontacts, ['id' => $id, 'actionid' => $job_id]);
$response->success() && var_dump($response->getData());
?>`

The same applies for the other examples.

**Comment by uavn** [comment]
Closing as it is not about SDK, its about documentation

**Comment by moulmandev** [comment]
It's been more than 2 years and still nothing changed ! Come on guys !
