### ISSUE TITLE
[[PERMALINK]] tag don't works

### ISSUE THREAD

**Issue by AndresAsprilla** [mailjet/mailjet-apiv3-php#193]
Hi, how are you?

I can send my email. But the permalink tag [[PERMALINK]] is don't interpreted 
When I look the email that I received I can see <a href="[[PERMALINK]]"> view in browser</a>

can you help me please?
Thanks you.

**Comment by lognav** [comment]
Hi, 
I have the same problem. Have anyone got the solution for it ?

Thanks
