### ISSUE TITLE
StatePermanent

### ISSUE THREAD

**Issue by nadar** [mailjet/mailjet-apiv3-php#195]
Is there any documentation on when the state of a message receives permanent status? (field StatePermanent) If its blocked for example, it quickly receives permanent, but when sending was "successful" it should receive permanent status sometime too

**Comment by nadar** [comment]
https://dev.mailjet.com/email/reference/messages#v3_get_message_message_ID

**Comment by Cyrille37** [comment]
Hello,
Another tips about `StatePermanent` : when loading messages with endpoint "/message" aka `Resources::$Message ` the property `StatePermanent` is presents but empty.
(*I have loaded 560.000 messages that all have this property empty*)

**Comment by nadar** [comment]
No response from mailjet dev's regarding this. sadly. but at least the behavior is consistent with the mailjet support - no answers....
