### ISSUE TITLE
How to set a variables into a template during the campaign-sending process?

### ISSUE THREAD

**Issue by Colir** [mailjet/mailjet-apiv3-php#196]
Hello. 
I would like to know how i can pass variables to a choosen template associated to a campaign. 

The idea is to use a template stored on Mailjet, to keep header and footer, and inject variables to define the body of a newsletter using the API.

The main idea is also to not use the send API, to keep mailjet's feaures like, image hosting, text part generation,etc.

Thank you

**Comment by ngarnier** [comment]
Hi @Colir, like discussed on the MJML Slack, please contact the Mailjet support via your account for this type of questions.

**Comment by Colir** [comment]
ok Nicolas, but community and guys like you on slack or github answer a lot faster than the support...Did you know if i can have a direct support by phone ? Thank again
