### ISSUE TITLE
Unable to SET email subject

### ISSUE THREAD

**Issue by aa-aahmed** [mailjet/mailjet-apiv3-php#197]
$mj = new \Mailjet\Client(MJPK, MJSK);
        $body = [
            'FromEmail' => $sendFrom,
            'FromName' => "ABC",
            'Subject' => $subject,
            'Html-part' => $msg,
            'Recipients' => [['Email' => $sendTo]],
            'Attachments' => [
                $attachment
            ]
        ];

$subject variable is set but for some reason mailjet client does not SET it when email hits the inbox Subject is blank. If I set the subject as STRING then it works very odd I did the print before setting subject but still no luck.

**Comment by uavn** [comment]
Just tried your example, and it works fine for me:
```
$mj = new \Mailjet\Client($key, $secret, true, ['version' => 'v3']);

$sendFrom = 'abonda@s.com';
$subject = 'Subject set with variable';
$msg = '<h1>Hey</h1>';
$sendTo = 'abonda@s.com';
$attachment = [
    'Content-type' => "text/plain",
    'Filename' => "test.txt",
    'content' => "VGhpcyBpcyB5b3VyIGF0dGFjaGVkIGZpbGUhISEK"
];

$body = [
    'FromEmail' => $sendFrom,
    'FromName' => "ABC",
    'Subject' => $subject,
    'Html-part' => $msg,
    'Recipients' => [['Email' => $sendTo]],
    'Attachments' => [
        $attachment
    ]
];

$response = $mj->post(\Mailjet\Resources::$Email, ['body' => $body]);
$response->success();

print_r($response->getStatus());
echo ':';
print_r($response->getReasonPhrase());
echo ':';
print_r($response->getData());
die;
```

![image](https://user-images.githubusercontent.com/315338/94168173-04f5f980-fe96-11ea-9cd7-1ba4930203a4.png)


Do you still have any issues?
