### ISSUE TITLE
[[PERMALINK]] not interpreted 

### ISSUE THREAD

**Issue by lognav** [mailjet/mailjet-apiv3-php#199]
Hello,
The variable [[PERMALINK]] is not interpreted when I send an email with mailjet API V3.1.
However, UNSUB_LINK_FR and EMAIL_TO work.

Anyone got a solution for it ?
Thanks

**Comment by ngarnier** [comment]
Hi, permalinks are not supported in transactional messages but only in campaigns.

**Comment by lognav** [comment]
Hi,
Thanks you for your replay.

**Comment by cattoo** [comment]
@ngarnier can we send campaigns with PERMALINK via API?

**Comment by bezin** [comment]
> @ngarnier can we send campaigns with PERMALINK via API?

I second this question: is it possible to send a campaign via the API and have a online version of this email available via `[[PERMALINK]]`?
