### ISSUE TITLE
I don't see the implementation for /contactdata + Bad Doc

### ISSUE THREAD

**Issue by Jolg42** [mailjet/mailjet-apiv3-php#2]
Hi !

The implementation of /contactdata documented here [http://dev.mailjet.com/guides/personalisation-guide/](http://dev.mailjet.com/guides/personalisation-guide/) is not implemented yet ?

Also, the documentation is not good on some points, the worst is when you want to add custom fields, it was just a PITA…

The 'Name' & 'Value' fields are not documented here -> [http://dev.mailjet.com/email-api/v3/contactdata/](http://dev.mailjet.com/email-api/v3/contactdata/)

And this is not cool in an open source repo :
```
@see http://mjdemo.poxx.net/~shubham/apikey.html
```
1.  It's password protected
2.  It seems it's your personal server @madflo ? 

My code for future users, I'm using Guzzle in Symfony 2
```php
$body = json_encode([
              'Data' => [
                        ['Name' => 'firstname', 'value' => $user->getFirstName()],
                        ['Name' => 'lastname', 'value' => $user->getLastName()],
                    ]
              ]);
$request = $client->createRequest('PUT', 'https://api.mailjet.com/v3/REST/contactdata/'.$user->getEmail(), [
                    'auth'=> ['api_key','api_secret'],
                    'body' => $body
                ]);
                $request->setHeader('Content-Type', 'application/json');
                $response = $client->send($request);
                $code = $response->getStatusCode();
                echo "--->".$code;
```

**Comment by roadster31** [comment]
> The 'Name' & 'Value' fields are not documented here -> http://dev.mailjet.com/email-api/v3/contactdata/
Still not documented 2 year ago.

Generally speaking, types are not documented at all, and example are just simplistic.

**Comment by arnaudbreton** [comment]
@roadster31 I believe what you're looking for is our API Guides, which provide the level of information you need to get things right. In your case, I believe [this guide](https://dev.mailjet.com/guides/?shell#personalisation-add-contact-properties) is what you're looking for.

Hope it helps,
Best.

**Comment by roadster31** [comment]
Thanks for this reply, this guide is fine.

However, more examples in the API references would be fine too.

**Comment by arnaudbreton** [comment]
Thanks @roadster31, glad to hear the guide was what you were looking for.

We definitely plan to improve our API reference over the coming months.

You should subscribe to our [API Newsletter](https://dev.mailjet.com/#newsletter) or follow us [on Twitter](https://twitter.com/mailjetdev) to follow our progress there.

Best
