### ISSUE TITLE
Adding user to a list takes 11 seconds or more, tried many options

### ISSUE THREAD

**Issue by andyEal** [mailjet/mailjet-apiv3-php#200]
Hello there. I am using the vanilla PHP (no Composer) and trying to get a script going. Got a few requests and one of them is taking forever to happen. It´s the action of adding a user to a list. 

I was using the "https://dev.mailjet.com/email/reference/contacts/subscriptions#v3_post_contact_contact_ID_managecontactslists" endpoint, when I saw delays in the 10-14 seconds. So I switched to the "listrecipient" endpoint:
https://dev.mailjet.com/email/reference/contacts/subscriptions#v3_post_listrecipient. Same thing there, and then lastly I used the endpoint "https://dev.mailjet.com/email/reference/contacts/subscriptions#v3_post_contactslist_list_ID_managecontact". Same thing there. 

Is there an issue with delays that is known? or is this script of mine doing something wrong?
(got a long script and this is the only thing doing something really off) (the whole script was hashed down here to the vitals)

```php
    /////////////////////// 
    $user_id = 038000577; 
    $list_id = 1230500; 

    require "mailjet-apiv3/vendor/autoload.php";
    use \Mailjet\Resources;

    require "api-credentials.php"; // my credentials
    $mj = new \Mailjet\Client($apikey, $apisecret,true,['version' => 'v3']); 
    ///////////////////////////////////////////////////////////////////////////////////

    $body = [
        'Name' => "",
        'Action' => "addnoforce",
        'Email' => "user@example.com"
    ];
    $response = $mj->post(Resources::$ContactslistManagecontact, ['id' => $list_id, 'body' => $body]);
```

Tried ContactID and ContactAlt (user´s email), no dice. Same thing. It works, just takes too long.

Extras: I am using a MAMP server on my local machine, and initially thought that might have something to do with it, as the up-speed is not perfect. I tested the same on a virtual machine on Linode, same thing there, perhaps a second less. But still deal-breaker for any customer.

Any help will be greatly appreciated.

/Andy.

**Comment by andyEal** [comment]
Update, next day: I have found another endpoint, the "Bulk Contact Management" endpoint "/contact/managemanycontacts":
https://dev.mailjet.com/email/reference/contacts/bulk-contact-management#v3_post_contact_managemanycontacts

This one takes care of every aspect of adding a user at just in between 1-2 secs. That includes flipping the previous "IsExcludedFromCampaigns = true" to "false", another request and wait time slashed right there :).

1-2 secs was what I was hoping for.  

The code for this:

```php
$my_vars = json_decode('{
  "my_custom_field_name": "new_custom_value"
}', true);

$body = [
    'Contacts' => [
      [
        'Email' => "user@example.com",
        'IsExcludedFromCampaigns' => "false",
        'Name' => "",
        'Properties' => $my_vars
      ]
    ],
    'ContactsLists' => [
        [
        'Action' => "addforce",
        'ListID' => "12121212"
        ]
    ]
];
$response = $mj->post(Resources::$ContactManagemanycontacts, ['body' => $body]);
```

So my particular need here is met but the issue of the delays on the endpoint "listrecipient" is still a question mark. 

Temporary delays?

**Comment by uavn** [comment]
Resolved, closing
