### ISSUE TITLE
Can't get specific list of messages when specifying paramaters

### ISSUE THREAD

**Issue by rodolamule** [mailjet/mailjet-apiv3-php#201]
Hello support
I set a "CustomID" and a campaign ID while sending emails with SMTP.
I use for that "X-MAILJET-CAMPAIGN" and "X-MJ-CustomID" as seen in documentation.

When i try to GET messages based on campaign ID, or custom ID, i always retrieve last 10 emails sent, excluding the ones in blocked status (and this is specially those ones i want to retrieve).
i also tried a different parameter "FromTS", not applied, i always get last 10 emails.
What am i doing wrong ? it seems all my parameters are not taken into account.
Thanks for your help

my code :
```
$mj = new \Mailjet\Client(MY_USER, MY_PASSWORD, true,['version' => 'v3']);
$response = $mj->get(Resources::$Message, ['CustomID' => $id]);
print_r($response->getData());
$response = $mj->get(Resources::$Message, ['Campaign' => $id2]);
print_r($response->getData());
$response = $mj->get(Resources::$Message, ['FromTS' => '2020-05-30T00:00:00']);
print_r($response->getData());
// all calls tried (tested other parameters) return last 10 messages sent...

```

**Comment by uavn** [comment]
@rodolamule
Try that way with 'filters' key:
```
$mj = new \Mailjet\Client($key, $secret, true);


$response = $mj->get(Resources::$Message, [
    'filters' => [
        'ContactID' => 207971034
    ]
]);
print_r($response->getStatus());
echo ':';
print_r($response->getReasonPhrase());
echo ':';
print_r($response->getData());
```
works for me
