### ISSUE TITLE
Can't get templates error management to work

### ISSUE THREAD

**Issue by stefanschindler** [mailjet/mailjet-apiv3-php#202]
Hi!

I am using Send API v3 for sending mails with the template language.

Sending and parsing works as expected, but I can't get the error management to work. I set the headers as described in the docs (https://dev.mailjet.com/email/template-language/sendapi/#templates-error-management). I want to receive a mail when a parsing error occurs, and don't want the mail to be delivered:

```
$body = [
   ...
   'TemplateErrorReporting'  => 'email@example.com',
   'TemplateErrorDeliver'        => false,
   ...
];

$this->mailjet->post(Resources::$Email, ['body' => $body]);
```

As I found other Header names in the docs (`Mj-TemplateErrorReporting`, `MJ-TemplateErrorReporting`, `X-Mj-TemplateErrorReporting`), I tried all of them, but still, I just did not get any Error reporting E-Mail when sending a mail with an invalid template (and I still received a blocked state in my webhooks, although `TemplateErrorDeliver` should prevent sending the mail, so this also doesn't seem to work)

Could anyone tell me, what I'm doing wrong?

**Comment by uavn** [comment]
@stefanschindler, try this:
```
$mj = new \Mailjet\Client($key, $secret, true, ['version' => 'v3.1']);

$body = [
    'Messages' => [
        [
            'From' => [
                'Email' => "abonda@softserveinc.com",
                'Name' => "Me"
            ],
            'To' => [
                [
                    'Email' => "abonda@softserveinc.com",
                    'Name' => "Artem"
                ]
            ],
            'Subject' => "Test.",
            "TemplateLanguage" => true,
            'TextPart' => "{% if test %}My first Mailjet email {{hello}}",
            'HTMLPart' => "{% if test %}<h3>My first Mailjet email {{hello2-}</h3>",
            'Variables' => [
                'hello' => "hello",
            ],
            'TemplateErrorReporting' => [
                'Email' => 'artbonvic@gmail.com',
            ],
            'TemplateErrorDeliver' => false,
        ]
    ],
];

$response = $mj->post(\Mailjet\Resources::$Email, ['body' => $body]);
$response->success();
```

works for me:
![Screenshot from 2020-09-23 23-28-19](https://user-images.githubusercontent.com/315338/94066048-9a40b180-fdf4-11ea-92b6-8d07967f4a40.png)

**Comment by stefanschindler** [comment]
Thanks for your response @uavn, but I needed to use the API v3.0.

After a lot playing around, I got it working with the following keys:

```
$body = [
   ...
   'Mj-TemplateErrorReporting'  => 'email@example.com',
   'Mj-TemplateErrorDeliver'    => 0,
   ...
];

$this->mailjet->post(Resources::$Email, ['body' => $body]);
```
