### ISSUE TITLE
Composer require does'nt install package

### ISSUE THREAD

**Issue by darkiron** [mailjet/mailjet-apiv3-php#204]
Hi, I try to get package, composer do nothing.

I try to get some informations with `show mailjet/mailjet-apiv3-php`
return to me :
> [InvalidArgumentException]                   
  Package mailjet/mailjet-apiv3-php not found

**Comment by uavn** [comment]
Composer command

`composer show mailjet/mailjet-apiv3-php`
can be run only in a folder when this package already installed, if to run from other folder it will give that error:

abonda@lv3411:~/mailgun/mailjet-apiv3-php$ composer show mailjet/mailjet-apiv3-php

```
In ShowCommand.php line 190:
                                               
  Package mailjet/mailjet-apiv3-php not found  
```
but

```
abonda@lv3411:~/mailgun/test2$ composer show mailjet/mailjet-apiv3-php
name     : mailjet/mailjet-apiv3-php
descrip. : PHP wrapper for the Mailjet API
keywords : Mailjet, api, email, php, v3
versions : * v1.5.0
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
source   : [git] https://github.com/mailjet/mailjet-apiv3-php.git ad940462b59e0fc06f6fbe2d9e7a40679f604f95
dist     : [zip] https://api.github.com/repos/mailjet/mailjet-apiv3-php/zipball/ad940462b59e0fc06f6fbe2d9e7a40679f604f95 ad940462b59e0fc06f6fbe2d9e7a40679f604f95
names    : mailjet/mailjet-apiv3-php

autoload
psr-0
Mailjet => src/

requires
guzzlehttp/guzzle ~7.0|~6.0|~5.3
php >=5.4.0

requires (dev)
php-coveralls/php-coveralls ^1.0
phpunit/phpunit ^4.8.36|^5.7
```
this will work.

The original require command works just fine:

`composer require mailjet/mailjet-apiv3-php`
sometimes composer itself is going down or request timeout exceeded and it gives errors, but all that is needed to do - is try again in a few minutes and everything should work fine. Can you try to run require command again?
