### ISSUE TITLE
Documentation for disable API call is incorrect

### ISSUE THREAD

**Issue by micmath** [mailjet/mailjet-apiv3-php#208]
The [README for `\Mailjet\Cllient`](https://github.com/mailjet/mailjet-apiv3-php/blob/master/README.md#disable-api-call)  says:

> ...you may want to disable it during testing to prevent unnecessary calls to the Mailjet API. This is done by setting the call parameter to false:
>
> `$mj = new \Mailjet\Client(getenv('MJ_APIKEY_PUBLIC'), getenv('MJ_APIKEY_PRIVATE'),true,['call' => 'false']);`

But that example does work in practice. As I read [the source code](https://github.com/mailjet/mailjet-apiv3-php/blob/24511ade8c28cabed4257fa919bfa751037b81c8/src/Mailjet/Client.php#L70) the actual method signature for disabling the call should be:
`$mj = new \Mailjet\Client(getenv('MJ_APIKEY_PUBLIC'), getenv('MJ_APIKEY_PRIVATE'),false);`

**Comment by uavn** [comment]
fixed now
