### ISSUE TITLE
Email not send

### ISSUE THREAD

**Issue by roukmoute** [mailjet/mailjet-apiv3-php#21]
Hi,

We have updated our composer with your new repository, but it doesn't work.
Our dump from `Mailjet\Response` return this : https://gist.github.com/roukmoute/35d4f2288048dae979c1

Where is the problem?

Thanks

**Comment by GuillaumeBadi** [comment]
Hey @roukmoute !

Thanks for using Mailjet! We love your nickname! :+1: 

The default template to send an email is :

``` php
<?php

require 'vendor/autoload.php';
use \Mailjet\Resources;

$mj = new \Mailjet\Client(getenv('MJ_APIKEY_PUBLIC'), getenv('MJ_APIKEY_PRIVATE'));

$body = [
    'FromEmail' => "pilot@mailjet.com",
    'FromName' => "Mailjet Pilot",
    'Subject' => "Your email flight plan!",
    'Text-part' => "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
    'Html-part' => "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
    'Recipients' => [[ 'Email' => "passenger@mailjet.com" ]]
];

$response = $mj->post(Resources::$Email, ['body' => $body]);

$response->success() && var_dump($response->getData());
?>
```

Can you paste your code to send the email so I can reproduce your error ? 

Best,
Guillaume.

**Comment by GuillaumeBadi** [comment]
Hey @roukmoute !

Does it work on your side ? 

Best,
Guillaume

**Comment by roukmoute** [comment]
Oh !
Sorry, I've completely forgotten this Issue.
I've realized that keys of Body doesn't the same with your example.
So I just fix-it.
