### ISSUE TITLE
Do not extends from GuzzleHttp\Client in Mailjet\Request

### ISSUE THREAD

**Issue by MinDBreaK** [mailjet/mailjet-apiv3-php#221]
The class `GuzzleHttp\Client` is marked as `final`. 
However, the `Mailjet\Request` extends from it. 

This leads for example in a Symfony project a deprecation warning as any major upgrade from Guzzle will break it. 

## Suggested fix
`Mailjet\Request` could rely on the decorated pattern and forward all calls to the original `GuzzleHttp\Client` except the ones you customize. Fixing this would also remove one required step to upgrade or support the next major version of Guzzle

**Comment by Pavlico** [comment]
#227 that will do the job

**Comment by Pavlico** [comment]
@MinDBreaK repository has beed updated, thank you for your valid point :)
