### ISSUE TITLE
$response->success() is false when $response->getStatus() is 201

### ISSUE THREAD

**Issue by chessterfi3ld** [mailjet/mailjet-apiv3-php#222]
When adding a contact to a list with ContactslistManagecontact, `$response->success()` is false but the contact is successfuly added as I can see it in the mailjet panel and `$response->getStatus()` is 201, why ?

**Comment by anthonyivol** [comment]
Actually in Response.php $this->success is set like this : 
```$this->success = 2 === floor($this->status / 100);```
And should be :
```$this->success = 2 == floor($this->status / 100);```
or
```$this->success = 2. === floor($this->status / 100);```
as `floor($this->status / 100);` is a float

**Comment by anthonyivol** [comment]
I've made a pull request : https://github.com/mailjet/mailjet-apiv3-php/pull/223

**Comment by Pavlico** [comment]
@chessterfi3ld thank you
