### ISSUE TITLE
Authentication issue when using SMS API

### ISSUE THREAD

**Issue by paulchartres** [mailjet/mailjet-apiv3-php#225]
Hi there,

I've been trying to use the SMS API with my PHP application, but it seems like I'm getting an error because of the NULL parameter that has to be sent when initializing the client:

`Argument 2 passed to Mailjet\Client::setAuthentication() must be of the type string, null given`

I am using the latest version of the Client on this repository, and I'm using the autoload.php file from the mirror repository.

**Comment by Pavlico** [comment]
Hi @paulchartres what is your php code that creates Client object? is your second param your secret key string?

**Comment by Pavlico** [comment]
Looking at code i found some issue that will be fixed with #228

**Comment by Pavlico** [comment]
@paulchartres can you update module and see if error is still present if no plz also give a heads up

**Comment by Pavlico** [comment]
No response, closing
