### ISSUE TITLE
How to use this api to get mails of all unsub contacts in my mailjet account ?

### ISSUE THREAD

**Issue by msitruk** [mailjet/mailjet-apiv3-php#23]
Hi,

I like mailjet, but i need to find a way to retrieve mails of all people ask for unsub in all my different contact list on my mailjet account ? Is it possible ?

Thank in advance

Maxime

**Comment by GuillaumeBadi** [comment]
Hey @msitruk :airplane: 

The `contact` resource accepts an `IsUnsubscribed ` filter. wich takes a boolean.

``` php
$filters = ['IsUnsubscribed' => true];
client->get(Resources::$Contact, ['filters' => $filters]);
```

Does it work on your side ? 

Best,
Guillaume

**Comment by msitruk** [comment]
Hello / Bonjour Guillaume,

Thank / Merci for your answer  ;)

To be honest I need trying to implement all the code but I will try today.
Just one question that will work on all my contacts on all my contact lists
?

Best,
Maxime

2015-12-04 10:38 GMT+01:00 Guillaume Badi <notifications@github.com>:

**Comment by GuillaumeBadi** [comment]
Actually, with a little more investigation, it might be trickier than that.. Can you explain your use case, so I can try to implement the call ? 

Merci Maxime!.
Guillaume :)

**Comment by msitruk** [comment]
I just want to get all unsub contact's mails in all existing list in my
mailjet account. With that I can make update in my sql base. then i will
use this script before making a new campaign to avoid send email at wrong
people. Or maybe I will do a crontab to update everyday.

Merci d'avance cordialement.

Maxime

2015-12-04 12:02 GMT+01:00 Guillaume Badi <notifications@github.com>:

**Comment by GuillaumeBadi** [comment]
Ow ! Mailjet's got your back Maxime! When you create a new Campaign, it won't be sent to unsubscribed contacts, automatically :)

**Comment by msitruk** [comment]
even if I do I new campaign for a new list of contact ..if i put in the new
list some contact who ask for unsub mailjet will detect them .. it's not
what I m seeing now.. it's why I want to remove in my side all unsub
contact from my contact

2015-12-04 13:55 GMT+01:00 Guillaume Badi <notifications@github.com>:

**Comment by msitruk** [comment]
Hello Guillaume I do a try and get : 
<font size='1'><table class='xdebug-error xe-uncaught-exception' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Uncaught exception 'GuzzleHttp\Ring\Exception\RingException' with message 'cURL error 60: SSL certificate problem: self signed certificate in certificate chain' in C:\wamp\www\pige\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line <i>51</i></th></tr>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain in C:\wamp\www\pige\vendor\guzzlehttp\guzzle\src\Exception\RequestException.php on line <i>51</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0000</td><td bgcolor='#eeeeec' align='right'>241600</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='C:\wamp\www\pige\mailjet.php' bgcolor='#eeeeec'>..\mailjet.php<b>:</b>0</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0260</td><td bgcolor='#eeeeec' align='right'>680496</td><td bgcolor='#eeeeec'>Mailjet\Client->get(  )</td><td title='C:\wamp\www\pige\mailjet.php' bgcolor='#eeeeec'>..\mailjet.php<b>:</b>26</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>3</td><td bgcolor='#eeeeec' align='center'>0.0260</td><td bgcolor='#eeeeec' align='right'>680696</td><td bgcolor='#eeeeec'>Mailjet\Client->call(  )</td><td title='C:\wamp\www\pige\vendor\mailjet\mailjet-apiv3-php\src\Mailjet\Client.php' bgcolor='#eeeeec'>..\Client.php<b>:</b>114</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>4</td><td bgcolor='#eeeeec' align='center'>0.0620</td><td bgcolor='#eeeeec' align='right'>1612664</td><td bgcolor='#eeeeec'>Mailjet\Request->call(  )</td><td title='C:\wamp\www\pige\vendor\mailjet\mailjet-apiv3-php\src\Mailjet\Client.php' bgcolor='#eeeeec'>..\Client.php<b>:</b>81</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>5</td><td bgcolor='#eeeeec' align='center'>0.0620</td><td bgcolor='#eeeeec' align='right'>1614440</td><td bgcolor='#eeeeec'><a href='http://www.php.net/function.call-user-func-array:{C:\wamp\www\pige\vendor\mailjet\mailjet-apiv3-php\src\Mailjet\Request.php:84}' target='_new'>call_user_func_array:{C:\wamp\www\pige\vendor\mailjet\mailjet-apiv3-php\src\Mailjet\Request.php:84}</a>
(  )</td><td title='C:\wamp\www\pige\vendor\mailjet\mailjet-apiv3-php\src\Mailjet\Request.php' bgcolor='#eeeeec'>..\Request.php<b>:</b>84</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>6</td><td bgcolor='#eeeeec' align='center'>0.0620</td><td bgcolor='#eeeeec' align='right'>1614520</td><td bgcolor='#eeeeec'>GuzzleHttp\Client->get(  )</td><td title='C:\wamp\www\pige\vendor\mailjet\mailjet-apiv3-php\src\Mailjet\Request.php' bgcolor='#eeeeec'>..\Request.php<b>:</b>84</td></tr>
<tr><td bgcolor='#eeeeec' align='center'>7</td><td bgcolor='#eeeeec' align='center'>0.0860</td><td bgcolor='#eeeeec' align='right'>2050272</td><td bgcolor='#eeeeec'>GuzzleHttp\Client->send(  )</td><td title='C:\wamp\www\pige\vendor\guzzlehttp\guzzle\src\Client.php' bgcolor='#eeeeec'>..\Client.php<b>:</b>125</td></tr>
</table></font>

My code : 

<?
require './vendor/autoload.php';
use \Mailjet\Resources;

$apikey = getenv('XXXXX');
$apisecret = getenv('YYYYY');

$client = new \Mailjet\Client($apikey, $apisecret);

$filters = ['IsUnsubscribed' => true];
$client->get(Resources::$Contact, ['filters' => $filters]);
?>

**Comment by msitruk** [comment]
I suppose it's my wamp install the problem .. so i try to install  php api with composer in my 1&1 webhost and I get : Fatal error: Out of memory (allocated 81002496) (tried to allocate 13 bytes) in phar:///homepages/5/d527976761/htdocs/composer.phar/src/Composer/Json/JsonFile.php on line 259

**Comment by msitruk** [comment]
Hello William,
I managed to install the api- php on my webhost 1&1 , this is what I get with this code:
<?

require './vendor/autoload.php';
use \Mailjet\Resources;
$apikey = 'XXX';
$apisecret = 'YYY';
$client = new \Mailjet\Client($apikey, $apisecret);
$filters = ['IsUnsubscribed' => true];
$ntm = $client->get(Resources::$Contact, ['filters' => $filters]);
print_r ($ntm);
echo '</br>';
print_r ($ntm->getData());
echo '</br>';
print_r ($ntm->success());
echo '</br>';
print_r ($ntm->getCount());
echo '</br>';
print_r ($ntm->getTotal());
?>

RESULT in Chrome : 
Mailjet\Response Object ( [status:Mailjet\Response:private] => 200 [success:Mailjet\Response:private] => 1 [body:Mailjet\Response:private] => Array ( [Count] => 0 [Data] => Array ( ) [Total] => 0 ) [request] => Mailjet\Request Object ( [method:Mailjet\Request:private] => GET [url:Mailjet\Request:private] => https://api.mailjet.com/v3/REST/contact [filters:Mailjet\Request:private] => Array ( [IsUnsubscribed] => 1 ) [body:Mailjet\Request:private] => {} [auth:Mailjet\Request:private] => Array ( [0] => 65d5f56fd9eb55b9e54a777a191bc3e4 [1] => 14f92df58d8c8c5202bc5512ed2e6990 ) [messageFactory:GuzzleHttp\Client:private] => GuzzleHttp\Message\MessageFactory Object ( [errorPlugin:GuzzleHttp\Message\MessageFactory:private] => GuzzleHttp\Subscriber\HttpError Object ( ) [redirectPlugin:GuzzleHttp\Message\MessageFactory:private] => GuzzleHttp\Subscriber\Redirect Object ( ) [customOptions:GuzzleHttp\Message\MessageFactory:private] => Array ( ) ) [baseUrl:GuzzleHttp\Client:private] => GuzzleHttp\Url Object ( [scheme:GuzzleHttp\Url:private] => [host:GuzzleHttp\Url:private] => [port:GuzzleHttp\Url:private] => [username:GuzzleHttp\Url:private] => [password:GuzzleHttp\Url:private] => [path:GuzzleHttp\Url:private] => [fragment:GuzzleHttp\Url:private] => [query:GuzzleHttp\Url:private] => ) [defaults:GuzzleHttp\Client:private] => Array ( [allow_redirects] => 1 [exceptions] => 1 [decode_content] => 1 [verify] => 1 [headers] => Array ( [user-agent] => mailjet-apiv3-php/5.5.30/v1.0.1 ) ) [fsm:GuzzleHttp\Client:private] => GuzzleHttp\RequestFsm Object ( [handler:GuzzleHttp\RequestFsm:private] => Closure Object ( [static] => Array ( [default] => Closure Object ( [static] => Array ( [default] => GuzzleHttp\Ring\Client\CurlHandler Object ( [factory:GuzzleHttp\Ring\Client\CurlHandler:private] => GuzzleHttp\Ring\Client\CurlFactory Object ( ) [handles:GuzzleHttp\Ring\Client\CurlHandler:private] => Array ( [66] => Resource id #66 ) [ownedHandles:GuzzleHttp\Ring\Client\CurlHandler:private] => Array ( [66] => ) [maxHandles:GuzzleHttp\Ring\Client\CurlHandler:private] => 5 ) [streaming] => GuzzleHttp\Ring\Client\StreamHandler Object ( [options:GuzzleHttp\Ring\Client\StreamHandler:private] => Array ( ) [lastHeaders:GuzzleHttp\Ring\Client\StreamHandler:private] => ) ) [parameter] => Array ( [$request] => ) ) [future] => GuzzleHttp\Ring\Client\CurlMultiHandler Object ( [factory:GuzzleHttp\Ring\Client\CurlMultiHandler:private] => GuzzleHttp\Ring\Client\CurlFactory Object ( ) [selectTimeout:GuzzleHttp\Ring\Client\CurlMultiHandler:private] => 1 [active:GuzzleHttp\Ring\Client\CurlMultiHandler:private] => [handles:GuzzleHttp\Ring\Client\CurlMultiHandler:private] => Array ( ) [delays:GuzzleHttp\Ring\Client\CurlMultiHandler:private] => Array ( ) [maxHandles:GuzzleHttp\Ring\Client\CurlMultiHandler:private] => 100 ) ) [parameter] => Array ( [$request] => ) ) [mf:GuzzleHttp\RequestFsm:private] => GuzzleHttp\Message\MessageFactory Object ( [errorPlugin:GuzzleHttp\Message\MessageFactory:private] => GuzzleHttp\Subscriber\HttpError Object ( ) [redirectPlugin:GuzzleHttp\Message\MessageFactory:private] => GuzzleHttp\Subscriber\Redirect Object ( ) [customOptions:GuzzleHttp\Message\MessageFactory:private] => Array ( ) ) [maxTransitions:GuzzleHttp\RequestFsm:private] => 200 ) [emitter:GuzzleHttp\Client:private] => GuzzleHttp\Event\Emitter Object ( [listeners:GuzzleHttp\Event\Emitter:private] => Array ( ) [sorted:GuzzleHttp\Event\Emitter:private] => Array ( ) ) [type] => application/json ) ) 



Array ( ) 
1
0
0

If you can help me to display all unsub contacts in all my contact list in my mailjet account thank !

**Comment by msitruk** [comment]
at this moment the onli way i found to do my job is to scann all email adresse I add in my mailjet account with api Contactstatistic to see if UnsubscribedCount is more than 0 ...
It's like cutting a wire with a chainsaw .. multiple request from my server to yours for 1 information I m sure possible to get in 1 request .. help me please !

**Comment by GuillaumeBadi** [comment]
Can you try that and tell me what the result is ? 
``` php
<?php

require 'vendor/autoload.php';

use \Mailjet\Resources;

$client = new \Mailjet\Client(getenv('MJ_APIKEY_PUBLIC'), getenv('MJ_APIKEY_PRIVATE'));

$filters = [
    'isUnsubscribed' => true
];

$response = $client->get(Resources::$Listrecipient, ['filters' => $filters]);

var_dump($response->getData());

?>
```

:)

**Comment by GuillaumeBadi** [comment]
Did it work ? @msitruk :)
