### ISSUE TITLE
Problem to import CSV files

### ISSUE THREAD

**Issue by Milooz** [mailjet/mailjet-apiv3-php#234]
Impossible to upload a csv since beginning of september , maybe because of the update of the Guzzle library

Request.php, Line 84, if you remove the type of $body (?array), it works.

**Comment by Pavlico** [comment]
Hi @Milooz , please update module version and check if error is fixed.

**Comment by Milooz** [comment]
Hi,
still the same error. 
Request.php line 84
If it's **?array $body**, the answer is he wait a string, so i try to replace with    **?string $body**, and the answer is he wait an array. 
I dont undersand how it's possible.

if i remove the type of variable and just put **$body** , it works

**Comment by Pavlico** [comment]
@Milooz 
version of mailjet plugin is  v1.5.4?

**Comment by Milooz** [comment]
yes i just update the module when you send me a message.
Even if i try with a csv file with file_get_contents, i have the same problem

**Comment by Pavlico** [comment]
Ok removed declaring type of body param.
Update and close if fixed :)
Thanky

**Comment by Pavlico** [comment]
I assume it is fixed since no answer

**Comment by Milooz** [comment]
@Pavlico 
Sorry , i was impossible for me the last days to have an internet access. 
Thanks a lot for the fix!
