### ISSUE TITLE
HTTP Error 400

### ISSUE THREAD

**Issue by supportA3WEB** [mailjet/mailjet-apiv3-php#24]
Hi,

I want to integrate your classes to call Mailjet and get my profile data, but I get a HTTP status 400 (and `getData()` is empty).
When I made a mistake in my secret key, I get a HTTP 401, which I suppose is normal.
I think I called your class by a wrong way but I did't found where is the problem.
Can you help me please?

Here is my code:
```php
require 'vendor/autoload.php';
use \Mailjet\Resources;

$apikey = 'aaaaaaaaaaaa';
$apisecret = 'bbbbbbbbbbbbbbbbbb';

$mjobj = new \Mailjet\Client($apikey, $apisecret);
$mjrep = $mjobj->get(Resources::$Myprofile);
echo('http_status='.$mjrep->getStatus());
```

Thanks a lot
Best regards
Jérôme

**Comment by GuillaumeBadi** [comment]
Hey @supportA3WEB !

Thanks for using Mailjet :airplane: 

Actually you code works in my case:
``` php
<?php

require 'vendor/autoload.php';
use \Mailjet\Resources;

$apikey = getenv('MJ_APIKEY_PUBLIC');
$apisecret = getenv('MJ_APIKEY_PRIVATE');

$mjobj = new \Mailjet\Client($apikey, $apisecret);
$mjrep = $mjobj->get(Resources::$Myprofile);
var_dump($mjrep->getData());

?>
```

``` php
array(1) {
  [0]=>
  array(21) {
    ["AddressCity"]=>
    string(0) ""
    ["AddressCountry"]=>
    string(2) ""
    ["AddressPostalCode"]=>
    string(0) ""
    ["AddressState"]=>
    string(0) ""
    ["AddressStreet"]=>
    string(0) ""
    ["BillingEmail"]=>
    string(0) ""
    ["BirthdayAt"]=>
    string(0) ""
    ["CompanyName"]=>
    string(14) "Guillaume Badi"
    ["CompanyNumOfEmployees"]=>
    string(1) "1"
    ["ContactPhone"]=>
    string(0) ""
    ["EstimatedVolume"]=>
    int(0)
    ["Features"]=>
    string(0) ""
    ["Firstname"]=>
    string(9) "Guillaume"
    ["ID"]=>
    int(_)
    ["Industry"]=>
    string(0) ""
    ["JobTitle"]=>
    string(0) ""
    ["Lastname"]=>
    string(4) "Badi"
    ["UserID"]=>
    int(_)
    ["VAT"]=>
    int(0)
    ["VATNumber"]=>
    string(0) ""
    ["Website"]=>
    string(0) ""
  }
}
```

Are you sure about your credentials ?

Best,
Guillaume

**Comment by GuillaumeBadi** [comment]
Is it still not working on your side @supportA3WEB  ? :)

**Comment by supportA3WEB** [comment]
Hi @GuillaumeBadi ,

Thank you for your answer. (I don't know if you speak french, but it will be easier for me!)
I tried to rewrite all the script and I'm still having the problem (HTTP 400).

My api codes seems to be correct. If a add a char in my secret key, the HTTP status in 401 and not 400.
In the Mailjet account, must I add the sender domain to allows api calls?

I saw that in the `$mjrep->request->getBody()` function, nothing returns to me? I don't know if it will contain something even if the call raises an HTTP error?

My configuration:
PHP 5.5.9
Nginx 1.4.6
Ubuntu 14.04.3 LTS

I continue to debug it!
Thank you
Jérôme

**Comment by GuillaumeBadi** [comment]
Salut ! @supportA3WEB !

Tu peux me coller les resultats de ces actions ? 
``` php
var_dump($mjrep->getData());
var_dump($mjrep->request->getUrl());
var_dump($mjrep->request->getFilters());
var_dump($mjrep->request->getBody());
```

Merci a toi,

Guillaume

**Comment by supportA3WEB** [comment]
Merci à toi @GuillaumeBadi !

En fait, je n'ai pas grand chose dans les var_dump :
`var_dump($mjrep->request->getBody());` renvoit `{}`
`var_dump($mjrep->request->getUrl());` renvoit `https://api.mailjet.com/v3/REST/myprofile`
`var_dump($mjrep->request->getFilters());` renvoit `Array ( )`
`var_dump($mjrep->getData());` renvoit rien du tout

Du coup, je me demande s'il n'y a pas un problème de configuration sur le serveur (droits, ...).
Je poursuis mes recherches

Merci beaucoup
Jérôme

**Comment by GuillaumeBadi** [comment]
Tu peux m'envoyer ton APIKEY et email d'utilisateur par email sur devrel@mailjet.com ? Je vais trouver ce qu'il se passe :)

**Comment by supportA3WEB** [comment]
C'est fait ! Merci encore !

**Comment by supportA3WEB** [comment]
En fait : non, le mail m'est revenu en erreur car la boite n'existe pas !

**Comment by GuillaumeBadi** [comment]
oups devrel-team@mailjet.com, desole :)

**Comment by supportA3WEB** [comment]
C'est fait :-D

**Comment by supportA3WEB** [comment]
Re-bonjour @GuillaumeBadi ,

J'ai pu tester le script avec le clés Mailjet de notre client et cela fonctionne nickel !
Du coup, le problème est sûrement lié à notre compte (forfait, option, ...).

Donc, je peux continuer à travailler :+1: 

Je ré-oriente donc ma question : qu'est-ce qui peut faire que le compte que l'on a, refuse les appels API ?
Merci par avance pour ta réponse et j'irai fermer l'issue par la suite :-)

Merci encore pour ta réactivité et tes réponses :-)
Jérôme

**Comment by supportA3WEB** [comment]
Bonjour @GuillaumeBadi ,

Merci pour les réponses.
Le problème était bien lié à mon compte et cela est résolu.
Je clos donc l'incident.

:v: 
Jérôme

**Comment by JoJoLV** [comment]
Bonjour,

@supportA3WEB j'ai le même problème que toi. Quel était le soucis sur ton compte stp ?
Pour info, j'ai l'option bronze.

Merci.
Jordan.

**Comment by GuillaumeBadi** [comment]
Salut @JoJoLV !

Il sagissait d'un compte sur l'api v1, ce wrapper utilise l'api v3, si tu veux plus de details, tu peux nous contacter at devrel-team@mailjet.com :airplane:

**Comment by JoJoLV** [comment]
D'accord @GuillaumeBadi, je t'envoi un e-mail dans l'heure. Merci.
