### ISSUE TITLE
API Timeout

### ISSUE THREAD

**Issue by BenjaminPorquet** [mailjet/mailjet-apiv3-php#241]
Hello,

We are using mailjet/mailjet-apiv3-php in a symfony4 project

We sometime get this error

![image](https://user-images.githubusercontent.com/12295662/150832093-3d8ab034-923d-4aa7-b43e-81ca3221a2fd.png)

2022-01-24 14:32:23
Uncaught PHP Exception GuzzleHttp\Exception\ConnectException: "cURL error 7: couldn't connect to host (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.mailjet.com/v3.1/send" at /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 210

and same at 2022-01-24 15:33:33

Does anyone have the same problem?

thanks a lot

**Comment by cbrianbet** [comment]
Getting the same problem as well

**Comment by oleksandr-mykhailenko** [comment]
Hello @BenjaminPorquet @cbrianbet 

Could please add more details?, maybe I will help you.
Does it happen only with `send` api endpoint and what payload do you have, as example maybe

**Comment by BenjaminPorquet** [comment]
Hello :) 

i'm really sorry but i don't understand your question

```
$body = [
            'Messages' => [
                [
                    'From' => [
                        'Email' => $mailFrom,
                        'Name' => $name,
                    ],
                    'To' => [
                        [
                            'Email' => $to,
                            'Name' => $to,
                        ],
                    ],
                    'TemplateID' => $templateID,
                    'TemplateLanguage' => true,
                    'Subject' => $subject,
                    'Variables' => $variables,
                ],
            ],
        ];

        $response = $this->mailjetClient->post(\Mailjet\Resources::$Email, ['body' => $body]);
```


where $this->mailjetClient = $mailjetClient; 


```
\Mailjet\Client $mailjetClient
```


i dont know what can i tell you more, 


thanks a lot !

**Comment by oleksandr-mykhailenko** [comment]
Hello @BenjaminPorquet 
Do yo have this issue for a while ?

**Comment by BenjaminPorquet** [comment]
Hello,

I have been having this problem for about 2 years

**Comment by oleksandr-mykhailenko** [comment]
> Hello,
> 
> I have been having this problem for about 2 years

Oh, I see. I think, this is something that happens sometimes, because we can't rely on 3rd party API for 100%.
Sometimes it's network issues, sometimes something on server.
So, there is no something in the SDK library that can resolve this issue. Even if we implement retry logic for Guzzle client

**Comment by oleksandr-mykhailenko** [comment]
Close issue due to inactivity
