### ISSUE TITLE
MessageID value issue

### ISSUE THREAD

**Issue by ariouche** [mailjet/mailjet-apiv3-php#25]
Hi,
I've been using the API to send transac emails.
Once I've sent a email though the api, I get the "messageId" form the response and store it to my own db. Notice that I also use the "MJ-CustomID" header field to affect this email to our own internal event called "email_campaign_7".

After that I used (though the API) the messagesentstatistics resource with the parameter CustomID=email_campaign_7 to get all the message sent on this event.

And here, I've noticed that the messsageId stored in the db is 19421798915720714 and the messsageId obtained form the messagesentstatistics is 19421798915720710 (the last digit is different).

Am I wrong somewhere?

**Comment by GuillaumeBadi** [comment]
Hey @ariouche !

Thanks for using Mailjet!

The process is working on my side, so I cannot reproduce your error.
Could you provide a part of your code, so I can investigate on the issue  ?

``` php
$email = [
    'FromEmail' => 'gbadi@student.42.fr',
    'Subject' => 'Hey!',
    'Text-Part' => 'Hello Humans!',
    'Recipients' => [['Email' => 'gbadi@mailjet.com', 'Name' => 'test recipient']],
    'Attachments' => [
        [
                'Content-type' => "application/pdf",
                'Filename' => "test.pdf",
                'Content' => base64_encode($content)
        ]
    ],
    'MJ-customID' => 'my_custom_id'
];
```

``` php
$filters = [
  'customID' => 'my_custom_id'
];

$response = $client->get(Resources::$Messagesentstatistics, ['filters' => $filters]);
```

Best,
guillaume

**Comment by ariouche** [comment]
I've been using a previous version of the php-mailjet-v3-simple.class.
```
include_once("php-mailjet-v3-simple.class.php");
$mj = new Mailjet( $this->apiKey, $this->secretKey );
$params = array(
	"method" => "POST",
	"from" => "sender@mydomain.com",
	"to" => "rec@mydomain.com",
	"subject" => "mysubject",
	"html"=>"bla bla",
	"Mj-CustomID"=>"custom_id"
);
$result = $mj->sendEmail($params);
if ($mj->_response_code == 200){
	$status = 1;
	$messageId = $mj->_response->Data[0]->ID;
}
...
```

**Comment by ariouche** [comment]
any news?

**Comment by GuillaumeBadi** [comment]
Hey sorry for the delay :)

Can you try this via cUrl ?

```
# This calls sends an email to one recipient.
curl -s \
    -X POST \
    --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
    https://api.mailjet.com/v3/send \
    -H 'Content-Type: application/json' \
    -d '{
        "FromEmail":"pilot@mailjet.com",
        "FromName":"Mailjet Pilot",
        "Subject":"Your email flight plan!",
        "Text-part":"Dear passenger, welcome to Mailjet! May the delivery force be with you!",
        "Html-part":"<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
        "Recipients":[{"Email":"passenger@mailjet.com"}],
        "Mj-CustomID":"PassengerEticket1234"
    }' 
```
and then get the ID back to see if they match:

```
# View : API Key Statistical campaign/message data.
curl -s \
    -X GET \
    --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
    https://api.mailjet.com/v3/REST/messagesentstatistics?CustomID=PassengerEticket1234 
```

It will let us see if this problem is wrapper-related :)

Best,
Guillaume

**Comment by ariouche** [comment]
have you got a php ready to use example code using curl?

**Comment by GuillaumeBadi** [comment]
You can paste the code in your termainal/cmd.exe and change it with your own data and it will output directly the result in a json format

**Comment by ariouche** [comment]
same ids!

**Comment by GuillaumeBadi** [comment]
The wrapper does not change that property. Are you sure your code to store and retrieve the ID within your database does not interfere with the actual value ?

**Comment by ariouche** [comment]
I had a look now and i'm 100% sure that the code is okay.
I've been comparing values from the messagesentstatistics and those on my db and sometimes ids are the same and sometimes not !!!! very strange....

**Comment by ariouche** [comment]
I've just sent you an picture where i make a comparison between values from the db and the resource messagesentstatistics

**Comment by ariouche** [comment]
hello, i've tried the following and still get differences between messageIds
```
$apiKey='....';
$secretKey = '.....';

include_once("php-mailjet-v3-simple.class.php");
$mj = new Mailjet( $apiKey, $secretKey );

$params = array(
	"method" => "POST",
	"from" => "...",
	"to" => "...",
	"subject" => 'TEST MESSAGEID',
);

$params["text"]="Dear passenger, welcome to Mailjet! May the delivery force be with you!";
	
$params["Mj-campaign"]='TEST MESSAGEID';
$params["Mj-CustomID"]='PassengerEticket1235';
$params["Mj-trackclick"]=1;
$params["Mj-trackopen"]=1;

for($i=0;$i<9;$i++){
	$result = $mj->sendEmail($params);
	echo $mj->_response->Data[0]->ID.'<br>';
}
exit;
```

**Comment by ariouche** [comment]
hi, sorry to push again but have you got any ideas?

**Comment by GuillaumeBadi** [comment]
Hey @ariouche !

Can you paste me the code you use to get the ID back from the API ?

**Comment by ariouche** [comment]
You can find it 3 posts above

**Comment by GuillaumeBadi** [comment]
I mean, if I get it right: 

 - you send the email
 - you get an ID from the send response
 - you store this ID into your database
 - you get back your message from `messagesentstatistics` <= Can you paste your code for this part ?

Best,
Guillaume

**Comment by GuillaumeBadi** [comment]
Hey @ariouche !

Are you using the same CustomID more than once in your code ?

Best,
Guillaume

**Comment by ariouche** [comment]
Ok, so I've identified the problem:
1- was using an old Google Chrome POSTMAN add-on (was wrongly displayed the datas)
2- the messageIds were converted to float somewhere in the code and that's why this nice issue give me (and you) to lost my day

Thanks a lot by the way for the support

**Comment by GuillaumeBadi** [comment]
Always happy to help ! :) :+1:
