### ISSUE TITLE
ContactslistManagecontact => Addforce not working

### ISSUE THREAD

**Issue by Exentriq** [mailjet/mailjet-apiv3-php#250]
Dear Sir/Madam,

we are using this code to add and subscribe the user to the list:
```
      $body = [
	  'Action' => "addforce",
	  'Email' => $user->user_email
	];
		$id = 99999999;
		$response = $mj->post(Resources::$ContactslistManagecontact, ['id' => $id, 'body' => $body]);
		$response->success() && var_dump($response->getData());
```

The user will be created but not subscribed to the list.

We also tried to repeat the operation after this function with an other one, the **ContactManagecontactslists**

```
               $body = [
		  'ContactsLists' => [
			[
			  'Action' => "addforce",
			  'ListID' => "9999999"
			]
		  ]
		];
		$response = $mj->post(Resources::$ContactManagecontactslists, ['id' => $user->user_email, 'body' => $body]);
		$response->success() && var_dump($response->getData());
```

but also this, doesn't work. Any suggestion? Help?

**Comment by oleksandr-mykhailenko** [comment]
> Dear Sir/Madam,
> 
> we are using this code to add and subscribe the user to the list:
> 
> ```
>       $body = [
> 	  'Action' => "addforce",
> 	  'Email' => $user->user_email
> 	];
> 		$id = 99999999;
> 		$response = $mj->post(Resources::$ContactslistManagecontact, ['id' => $id, 'body' => $body]);
> 		$response->success() && var_dump($response->getData());
> ```
> 
> The user will be created but not subscribed to the list.
> 
> We also tried to repeat the operation after this function with an other one, the **ContactManagecontactslists**
> 
> ```
>                $body = [
> 		  'ContactsLists' => [
> 			[
> 			  'Action' => "addforce",
> 			  'ListID' => "9999999"
> 			]
> 		  ]
> 		];
> 		$response = $mj->post(Resources::$ContactManagecontactslists, ['id' => $user->user_email, 'body' => $body]);
> 		$response->success() && var_dump($response->getData());
> ```
> 
> but also this, doesn't work. Any suggestion? Help?

Hello
I copied your code and tried locally. So here is my code

```
$body = [
    'Action' => 'addforce',
    'Email' => sprintf('testemail%s@gmail.com', time()),
];
$id = 26228;
$response = $mj->post(Resources::$ContactslistManagecontact, ['id' => $id, 'body' => $body]);
print_r($response->getData());
```

For me it worked well. All my test user were subscribed to the list. Here is screenshot as example

![image](https://user-images.githubusercontent.com/9269550/178116442-a6869dd8-83de-47ea-a786-d2dbd0c57da8.png)


I have only one idea, you can try. Maybe you should subscribe manually just one contact and other new will be subscribed automatically

**Comment by oleksandr-mykhailenko** [comment]
Due to inactive in this topic I close the issue
