### ISSUE TITLE
Blocks & Hard/Soft Bounces Statistics

### ISSUE THREAD

**Issue by pr0grammr** [mailjet/mailjet-apiv3-php#256]
Where can i get all contacts that are blocked, or hard/soft bounced, given an campaign ID oder contactlist ID? 
without using webhooks. 
i would like to receive a list of users, which are soft/gard bounced or blocked. 

i did the same with unsubscribed users. i want to do the same with blocked/bounces. 

```php
public function getUnsubscribedContactsFromContactList(int $contactListId)
{
    $response = Mailjet::get(Resources::$Listrecipient, [
	    'filters' => [
		    'ContactsList' => $contactListId,
		    'Unsub' => true
	    ]
    ]);

    return $response->getBody();
}
```

**Comment by oleksandr-mykhailenko** [comment]
Hello @pr0grammr 
Unfortunately, right now there is no way to get those contacts with such params
