### ISSUE TITLE
Issue with getting error log after uploadind CSV file

### ISSUE THREAD

**Issue by corina-coste** [mailjet/mailjet-apiv3-php#257]
I have an issue using the Resources::$BatchjobCsverror to see the errors after uploading a file. 
The error I keep getting is "Data Content type "text/plain" does not match URL content type "text/csv"." with a valid CSV file and errors showing fine in the frontend of Mailjet.
From what I tested in Postman the content-type of the request is set to text/plain instead of application/json which brings this error. 
So is the API changing somehow the content type or is there a way of setting the headers and content type of requests?

**Comment by oleksandr-mykhailenko** [comment]
Hello @corina-coste 
Could you provide more details here, please ?
This error you have only during Postman testing or in the API too ? And if you're using API request, please, post a code example that you're using

**Comment by oleksandr-mykhailenko** [comment]
Hello @corina-coste 
This issues was fixed. Please, update your library
