### ISSUE TITLE
API TIME OUT

### ISSUE THREAD

**Issue by DiegoInostroza** [mailjet/mailjet-apiv3-php#266]
Hi, I have been having problems with the mailjet API, and it is that situations occur where the image error occurs
```
  [GuzzleHttp\Exception\ConnectException]                                                                                                     
  cURL error 28: Operation timed out after 15001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) 
```
But, if I run it again everything works great.
This is the request that I make to the API
```
        $filters = array(
            'FromTS' => $from,
            'ToTS' => $to,
            'ShowCustomID' => true,
            'ShowContactAlt' => true,
            'Limit' => $limit,
            'Offset' => $offset,
            'Sort' => 'createdAt ASC'
        );
        $response = $this->mailjetClient->get(Resources::$Message, ['filters' => $filters]);
        
        if($response->success()) return $response->getData();
```
Has the same happened to anyone? how did they manage to solve it?

**Comment by oleksandr-mykhailenko** [comment]
Hello @DiegoInostroza 
Does it happen each time when you try to make a request ?

**Comment by oleksandr-mykhailenko** [comment]
Hello @DiegoInostroza 
I see that field `createdAt` is not supported for sorting

![image](https://user-images.githubusercontent.com/9269550/206522990-9c987234-74d9-4e10-9991-cbcdad330eac.png)

I tested your example, and for API worked well.
Do you have this each time or only with specific params ?

**Comment by oleksandr-mykhailenko** [comment]
I close the issue due to inactivity
