### ISSUE TITLE
How to set the interface used for requests (CURLOPT_INTERFACE) ?

### ISSUE THREAD

**Issue by Entretoize** [mailjet/mailjet-apiv3-php#267]
I have a hosting with a dedicated ip, but the mailjet api uses the server IP as php does.
It's possible with curl to user the dedicated ip by setting the CURLOPT_INTERFACE option.
How can I do it with your api ?

**Comment by oleksandr-mykhailenko** [comment]
You can use next settings

![image](https://github.com/mailjet/mailjet-apiv3-php/assets/9269550/2ab965ef-caa2-490c-b233-32b93cb4dd08)


Or use next

![image](https://github.com/mailjet/mailjet-apiv3-php/assets/9269550/c5d27f9f-c683-4a29-a051-1b194f3e8d5c)
