### ISSUE TITLE
Send API fails from time to time with error HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)

### ISSUE THREAD

**Issue by boboldehampsink** [mailjet/mailjet-apiv3-php#269]
Using PHP 8.1

**Comment by oleksandr-mykhailenko** [comment]
Hello @boboldehampsink 
Do you have maybe more detailed explanations of this error ? Or it's only this message that you see ?

**Comment by boboldehampsink** [comment]
@oleksandr-mykhailenko this is the only message I see

**Comment by oleksandr-mykhailenko** [comment]
Hello @boboldehampsink 

Here is additional info that can help you


The error message you mentioned, "HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)", is related to the HTTP/2 protocol and indicates that the server canceled the stream unexpectedly. There are a few possible causes for this error and some steps you can take to resolve them:

Network or Connectivity Issues: Check your network connection for any interruptions or connectivity problems. This error can occur if there are network disruptions between the client and the server. Ensure that both client and server have stable internet connections.

Server Configuration: The server may be misconfigured or experiencing issues with handling HTTP/2 streams. Ensure that the server is properly configured to support HTTP/2 and that it is running the latest version. Check the server logs for any relevant error messages that could provide more insight into the issue.

Guzzle Configuration: If you are using the Guzzle library, there might be an issue with its configuration. Verify that you are using the correct version of Guzzle that supports HTTP/2. Make sure you have the necessary dependencies installed and properly configured.

Load Balancer or Proxy Issues: If your application is behind a load balancer or proxy server, there might be issues with how these components handle HTTP/2 requests. Check the configuration of your load balancer or proxy to ensure it properly supports HTTP/2.

To troubleshoot and resolve this error, you can try the following steps:

Update Guzzle: Make sure you are using the latest version of Guzzle. Updating to the latest version may address any known issues related to HTTP/2.

Verify Server Compatibility: Check if the server you are communicating with fully supports HTTP/2. Ensure it is properly configured to handle HTTP/2 requests and is not experiencing any issues.

Check Network Connectivity: Ensure that your network connection is stable and not causing any disruptions. You can try testing your application on a different network to see if the issue persists.

Review Guzzle Configuration: Verify that your Guzzle configuration is correct and aligns with the server requirements. Double-check any relevant settings, such as timeouts, connection limits, or SSL certificates.

Enable Debugging: Enable debugging in Guzzle to get more detailed information about the requests and responses. This can help identify any specific issues or error messages that may provide further clues for troubleshooting.

Contact Server Administrator or Guzzle Support: If the issue persists after trying the above steps, it may be beneficial to reach out to the server administrator or the Guzzle library support team for further assistance. Provide them with any relevant error logs or additional details about your setup to help them diagnose the problem more effectively.

By following these steps, you should be able to identify and resolve the underlying issue causing the "HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)" error in your Guzzle application.

**Comment by boboldehampsink** [comment]
This issue is still occurring across multiple independent production applications.

We [forced HTTP/1.1 in March 2025](https://github.com/robuust/craft-mailjet/commit/7ac95ebdd1d9d57f5684f63f51c0e47ccb406ee7), but [reverted it in May 2025](https://github.com/robuust/craft-mailjet/commit/88d24f2dcd02a6ed5a6f5d671456f9920bd794e2) because it did not resolve the underlying reliability problem.

Recent failures now report:

`Recv failure: Connection reset by peer for "https://api.mailjet.com/v3.1/send"`

This happened on separate production applications on August 19 and August 31, 2026. In the latest case, two independent Send API requests during one form submission were both reset.

This therefore does not appear limited to HTTP/2 or a particular SDK. Could this issue be reopened and routed to the Send API infrastructure team?

Please also confirm the supported idempotency mechanism for retrying a Send API request when the connection is reset before a response is received. Clients cannot safely know whether such a POST was accepted.
