### ISSUE TITLE
Obtenir le statut des emails depuis une date

### ISSUE THREAD

**Issue by ariouche** [mailjet/mailjet-apiv3-php#27]
Bonjour,

je souhaite obtenir tous les emails envoyés depuis une date (13/12/2015 00:00:00 par ex) mais impossible d'obtenir toutes les données.
J'utilise cette requete :
```
https://api.mailjet.com/v3/REST/messagesentstatistics?Limit=1000&FromTS=1449961200
```
Merci

**Comment by GuillaumeBadi** [comment]
Salut! :airplane: !

Si tu utilises cUrl, tu peux essayer d'ajouter l'option `-i` pour afficher plus de details concernant la reponse et copier la reponse ici :)

``` bash
curl -i -X GET --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" https://api.mailjet.com/v3/REST/messagesentstatistics\?FromTS\=1449961200
```

Guillaume.

**Comment by ariouche** [comment]
en fait, j'obtiens des données mais elles sont incomplètes. En fait, je n'obtiens pas tous les emails envoyés depuis cette date mais seulement quelques uns.

voici la réponse
```
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 16 Dec 2015 16:06:14 GMT
Content-Type: application/json
Content-Length: 4615
Connection: keep-alive
```

**Comment by GuillaumeBadi** [comment]
Can you try with the `CountOnly` filter set to 1 ?

``` bash

curl -i -X GET --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
        https://api.mailjet.com/v3/REST/messagesentstatistics\?FromTS\=1449961200\&CountOnly=1

```

**Comment by ariouche** [comment]
{ "Count" : 236, "Data" : [], "Total" : 236 }

**Comment by GuillaumeBadi** [comment]
Je sais pas pourquoi je suis repasser en anglais, l'habitude.. 

Tu peux m'envoyer ton APIKEY et email a devrel-team@mailjet.com ? Je vais regarder ca plus en detail :)

**Comment by GuillaumeBadi** [comment]
Hey @ariouche ! 

De notre coté on voit un message en SMTP a 2300 contacts et non 2000 messages.

**Comment by ariouche** [comment]
oui, comme je le disais il y a plus de 2000-2500 emails envoyés depuis dimanche dernier.
le souci c'est que l'api ne retourne que 286 resultats

**Comment by GuillaumeBadi** [comment]
Oui mais tu as envoyer un seul message a plusieurs "Recipients" non ? Tu n'as pas fait 2000 call a l'API si ?

**Comment by ariouche** [comment]
si, plus de 2000 calls, un a un

**Comment by ariouche** [comment]
par contre, les emails sont tous affctes a la meme Mj-campaign et Mj-CustomID

**Comment by ariouche** [comment]
salut. des nouvelles ?

**Comment by ariouche** [comment]
hello, désolé si j'insiste mais as tu des news ?
Merci

**Comment by GuillaumeBadi** [comment]
Hey @ariouche !

Desolé du retard, on a du pas mal investiguer :) !

Essaye ca:
``` bash
curl -i -X GET --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
        https://api.mailjet.com/v3/REST/messagesentstatistics\?FromTS\=1449961200\&CountOnly=1\&AllMessages=1
```

Guillaume

**Comment by ariouche** [comment]
top merci
