### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by andrewteg** [mailjet/mailjet-apiv3-php#276]
I was testing this on a PHP 7.4 install and that is not currently compatible:

Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 7.4.13. in \mailjet\vendor\composer\platform_check.php on line 24

Recommend updating https://github.com/mailjet/mailjet-apiv3-php#compatibility

Is there anything saying where PHP 8.1 is needed?  I commented out and ran the getting started and got the basic stats, so just curious if 8.1 is indeed required and how likely it is to run into compatibility issues.

**Comment by oleksandr-mykhailenko** [comment]
Hello @andrewteg 
Thank you for reporting this. We will fix this issue soon and update requirements

**Comment by oleksandr-mykhailenko** [comment]
This one is fixed, thank you
