### ISSUE TITLE
Sender Validate

### ISSUE THREAD

**Issue by Jysui** [mailjet/mailjet-apiv3-php#28]
Bonjour,

Je veux utiliser Mailjet\Resources::$SenderValidate qui est présent dans votre documentation.
Mais lorsque je veux accéder à cette fonction, j'ai un message me disant : 
Access to undeclared static property: Mailjet\Resources::$SenderValidate.
Il semble bien que SenderValidate ne soit pas présent dans votre fichier "Ressources.php".

Pouvez-vous me dire comment utiliser cette fonction ?

Merci

**Comment by GuillaumeBadi** [comment]
Hey @Jysui !

Merci d'utiliser Mailjet! :+1: 

La resource n'etait pas dans la derniere release, uniquement sur Github. Je viens de faire le merge! 
Dis moi si tout fonctione de ton coté :)

Guillaume.

**Comment by Jysui** [comment]
Hello @GuillaumeBadi ,

Merci pour l'ajout ;). J'arrive bien à accéder à la fonction mais je pense ne pas bien l'utiliser.
Lorsque je passe une adresse email à valider dans le param "id" j'ai un retour 404 : 
```
[private] status => (int) 404
[private] success => false
[private] body => array(
	'ErrorInfo' => '',
	'ErrorMessage' => 'Object not found',
	'StatusCode' => (int) 404
)
```
Malheureusement, je n'ai pas plus d'information dans le retour me permettant de savoir ce qui ne fonctionne pas. Lorsque je lance l'appel avec une adresse déjà validée, j'ai un retour correcte me disant qu'elle existe déjà donc pas de souci de ce côté.

Merci d'avance :)

**Comment by GuillaumeBadi** [comment]
Salut @Jysui !

Tu peux me copier/coller ton code (sans les info confidentielles comme les clefs API ;) ). La resource fonctionne bien de mon coté!

Guillaume. :airplane:

**Comment by Jysui** [comment]
Salut @GuillaumeBadi ,

``` PHP
$id = 'mon@email.fr';
$response = $mailjet->post(Resources::$SenderValidate, ['id' => $id]);
```

Merci :)

**Comment by GuillaumeBadi** [comment]
Tu peux faire un ```$response->request->getUrl()```, et un ``` $mailjet->get(Resources::$Sender, $id) ``` pour voir si il existe bien ?

**Comment by Jysui** [comment]
J'ai mon adresse n’apparaît pas dans la liste mais justement je voudrais l'ajouter :).

**Comment by GuillaumeBadi** [comment]
Il faut deja ajouter le sender: http://dev.mailjet.com/guides/?shell#verify-a-sender avant de le validate :)

Guillaume.

**Comment by Jysui** [comment]
Super merci ça fonctionne.
Par contre, je n'arrive pas à comprendre comment marche les autres méthodes de validation (pas par email). Je voudrais valider l'adresse mais sans envoyé de mail. Comment peut-on modifier la ValidationMethod ?
J'ai essayé de passer par le params body mais ça ne fonctionne pas.

Merci pour tes lumières

**Comment by GuillaumeBadi** [comment]
Hey @Jysui ! :airplane: 

Je t'invite a lire [cette partie de la doc](http://dev.mailjet.com/guides/?shell#validate-sender-and-domain) pour mieux comprendre comment fonctionne cette resource. 

Toujours un plaisir,
Guillaume :)
