### ISSUE TITLE
v1.6.2 breaks Symfony 6.4 projects

### ISSUE THREAD

**Issue by arneee** [mailjet/mailjet-apiv3-php#284]
Hi,

you have added a hard versioned dependency  "symfony/validator": "6.3" in version 1.6.2, which basically downgrades all Symfony components to 6.3 if Mailjet is being used in a Symfony 6.4 project.

Please change it to ^6.3

Please see PR https://github.com/mailjet/mailjet-apiv3-php/pull/283

Thanks!

**Comment by arneee** [comment]
I would also suggest to check if everything works with symfony/validator 7, since this is the latest version and limiting it to 6.x would be probably make this library incompatible with any Symfony 7 project.

**Comment by oleksandr-mykhailenko** [comment]
Hello @arneee 
thank you for changes. Yes, we will make tests for Symfony 7
