### ISSUE TITLE
Campaigngraphstatistics no results

### ISSUE THREAD

**Issue by Jysui** [mailjet/mailjet-apiv3-php#30]
Bonjour,
J'utilise Campaigngraphstatistics et j'ai un retour 200 de l'API, mais je n'ai pas de donnée.
Pourtant je vais bien sur une newsletter qui a été envoyée.
``` PHP
$response = $mailjet->get(Resources::$Campaigngraphstatistics, ['filters' => ['Open' => true, 'IDS' => $id]]);
```

``` JSON
    [private] status => (int) 200
	[private] success => true
	[private] body => array(
		'Count' => (int) 0,
		'Data' => array(),
		'Total' => (int) 0
	)
```
Merci pour vos lumières

**Comment by GuillaumeBadi** [comment]
Hey @Jysui ! :airplane: 

Que ce passe-t-il si tu envoie la meme requete avec cUrl ?

``` bash
curl -s -X GET \
--user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
https://api.mailjet.com/v3/REST/campaigngraphstatistics?Open=1&IDS=<ids>
```

**Comment by Jysui** [comment]
Hello,

Merci pour ta réponse. J'ai le même résultat.

Merci

**Comment by Jysui** [comment]
Hello @GuillaumeBadi ,

Je me permet de te relancer :).

Merci

**Comment by GuillaumeBadi** [comment]
Hello ! @Jysui 

Qu'est ce que tu veux exactement comme data sur ta campagne ?

**Comment by Jysui** [comment]
Hello,

Je voudrais les mêmes stats que celles présentes dans mon compte une lorsque je vais sur une campagne déjà envoyée. 

Merci

**Comment by GuillaumeBadi** [comment]
Je te conseil d'utiliser campaignstatistics et graphstatistics, je pense que tu y trouvera beaucoup plus d'infos , et ca corresponds exactement a ce qu'il y a dans l'UI

**Comment by Jysui** [comment]
Justement j'utilise campaignstatistics et je n'ai pas d'info dans le retour.

**Comment by GuillaumeBadi** [comment]
Est ce que tu peux m'envoyer ton API key et l'identifiant de ta campagne a cette adresse pour qu'on puisse voir ca de plus pret ? devrel-team@mailjet.com
