### ISSUE TITLE
apitoken sur campaign et autres pages front

### ISSUE THREAD

**Issue by gbcogivea** [mailjet/mailjet-apiv3-php#37]
Bonjour,

Tout d'abord, ravi de voir que votre api s'enrichie rapidement.
J'ai malgré tout un problème pour charger la page "campaigns" avec un token qui ne semble plus valide depuis quelques semaines.

Code 
```
$mj = new \Mailjet\Client($cle, $mdp);
$response = $mj->get(Resources::$Apitoken);
$token="";
if($response->success()) {
  $data=$response->getData();
  foreach($data as $d) {
    if ($d['IsActive']) {
       $token=$d['Token'];
       break;
    }
  }
}
$url="https://www.mailjet.com/campaigns?t=".$token;
```
L'url génèrée est soumise à une  iframe dont voici le code retour ci-dessous (cela a été aussi testé en curl avec le même résultat).
```
**Sorry the page you are trying to view is not here.**
Here's what we received from the server: This token is invalid..
```
L'url a changée ou plus possible de le faire ? impossible de trouver des infos sur votre documentation, j'ai surement loupé quelque chose.
A noter que même résultat avec l'api php-mailjet-v3-simple.class.php.

A part ca, mes autres appels de votre API fonctionnent correctement mais nous souhaitons afficher vos interfaces comme nous le faisions auparavant sans devoir re-développer tout votre "front".

Dans l'attente de votre réponse.

**Comment by gbcogivea** [comment]
Bonjour,

On m'a remontée que la version 1 de l'api mailjet avec un compte en v1 donc permettait d'afficher les interface mailjet (comme campaigns) depuis une iframe, donc je suppose que dans ce cas le token est bon. Mais pas avec la version 3 de l'api et des comptes v3.

Si ca peut vous aider, merci.

**Comment by GuillaumeBadi** [comment]
Hey ,

desolé pour le retard, mais j'ai enfin trouvé la solution. Tu peux essayer de changer www.mailjet.com en app.mailjet.com ?

**Comment by GuillaumeBadi** [comment]
Hello, Ca marche du coup ? :airplane:

**Comment by gbcogivea** [comment]
Bonjour,

Désolé à mon tour du retard, mais c'était bien çà, merci de ton retour.

Je clos le ticket.
