### ISSUE TITLE
Create Contactlist

### ISSUE THREAD

**Issue by wfabian** [mailjet/mailjet-apiv3-php#38]
Hi,

I'm trying to create a contactlist over the API.
I'm always gettin a 400.

First I check if a list for a specific name already exist - That work's fine.
If a list doesn't exist, i want to create it.

That's how I try ist:

`        $params = ['Name' => $name];
        $response = $mailjet->post(Resources::$Contactslist,$params);`

EDIT: At the moment i try to create the list with name "Test-Test-Test"

`{ ["ErrorInfo"]=> string(69) "MJ08 Property Name is invalid: MJ04 Value must have at least length 1" ["ErrorMessage"]=> string(25) "Object properties invalid" ["StatusCode"]=> int(400) }`

Can anyone help?

**Comment by GuillaumeBadi** [comment]
Hey @wfabian 

`$params = ['body' => ['Name' => $name]];` should do the trick ;)

Let me know if it works for you! :airplane:

**Comment by wfabian** [comment]
Worked for me.

Thank you for the fast answer! :+1:  :100:

**Comment by wfabian** [comment]
Sorry, another question.

Shouldn't it work like this?

I'm trying to add contact to a list.

`        $params = ['id' => $listId, 'body' => ['Name' => $name, 'Email' => $mail, 'Action' => 'addforce']];
        $response = $mailjet->post(Resources::$ContactslistManagecontact,$params);`

**Comment by GuillaumeBadi** [comment]
Yep that's it

What is your output ?

**Comment by wfabian** [comment]
array(3) { ["ErrorInfo"]=> string(0) "" ["ErrorMessage"]=> string(61) "Can not execute the action - a required object ID is missing." ["StatusCode"]=> int(400) }

**Comment by GuillaumeBadi** [comment]
Strange.. 

Can you print out these values ? 
``` php
$response->request->getUrl()
$response->request->getFilters()
$response->request->getBody()
```

**Comment by wfabian** [comment]
Hey,
thank you for this.

There was no ID given in Body.
It could happen that the list-ID was empty.

Now I fixed something else and now it work's.

It was a not bug in the mailjet-API, it was my mistake, sorry.
