### ISSUE TITLE
Locale is invalid error

### ISSUE THREAD

**Issue by srggroup** [mailjet/mailjet-apiv3-php#39]
Hi!

I'm trying to send a hungarian newsletter through the API (with PHP wrapper).
When I call the `/newsletter` resource, I'm getting this error, when I set the `Locale` property to `hu` or `hu_HU`:

`MJ08 Property Locale is invalid: Invalid locale: "hu_HU"`

If I'm using for example `en` for the `Locale` property, it works.

Is this a bug, or I don't use this property well?

Thanks

**Comment by GuillaumeBadi** [comment]
Hey @srggroup !

the Local property is used to automatically insert the `Unsubscribe` and `View it online` when creating a template via the user interface. There is no hungarian version of these texts so you can use your own and provide `en` for the Local

Regards,
Guillaume

**Comment by GuillaumeBadi** [comment]
Hey ! Does it work for you ? :airplane:

**Comment by srggroup** [comment]
The `en` Locale is solved it, because we're using our own template-builder, so the Unsubscribe link is generated "here". 
But maybe you should set this feature configurable for all Locales, because for example in our CMS we have a multi-language Newsletter system, so I can't set hungarian text for `en` Local in your system.

**Comment by GuillaumeBadi** [comment]
Hey ! I am closing it for now as this cannot be added right now in the API. Supporting this would result in supporting the actual translations for the buttons. Can you figure out a way to store your local in some other way ?

**Comment by srggroup** [comment]
We can work without this parameter now. Thanks for the help!
