### ISSUE TITLE
Trying to find and delete a contact from list

### ISSUE THREAD

**Issue by wfabian** [mailjet/mailjet-apiv3-php#40]
Hi,
I'm trying to find a Listrecipient by contact-mail.
Then I will unsubscribe the contact from list.

My first problem:
Im trying to find the Listrecipient this way:

`        $params = ['body' => ['ContactALT' => $mail, 'ListID' => $listId]];
        $response = $mailjet->get(Resources::$Listrecipient,$params);`

But I'm getting following (hope this is readable):

```
`array(7) { ["ContactID"]=> int(1) ["ID"]=> int(6) ["IsActive"]=> bool(true) ["IsUnsubscribed"]=> bool(true) ["ListID"]=> int(3) ["ListName"]=> string(13) "ThisIsATest" ["UnsubscribedAt"]=> string(20) "2015-12-08T15:10:32Z" } 

array(7) { ["ContactID"]=> int(6) ["ID"]=> int(7) ["IsActive"]=> bool(true) ["IsUnsubscribed"]=> bool(false) ["ListID"]=> int(4) ["ListName"]=> string(4) "TEST" ["UnsubscribedAt"]=> string(0) "" } 

array(7) { ["ContactID"]=> int(7) ["ID"]=> int(8) ["IsActive"]=> bool(true) ["IsUnsubscribed"]=> bool(false) ["ListID"]=> int(4) ["ListName"]=> string(4) "TEST" ["UnsubscribedAt"]=> string(0) "" } 

array(7) { ["ContactID"]=> int(8) ["ID"]=> int(9) ["IsActive"]=> bool(true) ["IsUnsubscribed"]=> bool(false) ["ListID"]=> int(4) ["ListName"]=> string(4) "TEST" ["UnsubscribedAt"]=> string(0) "" } 

array(7) { ["ContactID"]=> int(9) ["ID"]=> int(10) ["IsActive"]=> bool(true) ["IsUnsubscribed"]=> bool(false) ["ListID"]=> int(4) ["ListName"]=> string(4) "TEST" ["UnsubscribedAt"]=> string(0) "" } 

array(7) { ["ContactID"]=> int(10) ["ID"]=> int(11) ["IsActive"]=> bool(true) ["IsUnsubscribed"]=> bool(false) ["ListID"]=> int(4) ["ListName"]=> string(4) "TEST" ["UnsubscribedAt"]=> string(0) "" } 

array(7) { ["ContactID"]=> int(11) ["ID"]=> int(12) ["IsActive"]=> bool(true) ["IsUnsubscribed"]=> bool(false) ["ListID"]=> int(4) ["ListName"]=> string(4) "TEST" ["UnsubscribedAt"]=> string(0) "" } 

array(7) { ["ContactID"]=> int(12) ["ID"]=> int(13) ["IsActive"]=> bool(true) ["IsUnsubscribed"]=> bool(false) ["ListID"]=> int(4) ["ListName"]=> string(4) "TEST" ["UnsubscribedAt"]=> string(0) "" } 

array(7) { ["ContactID"]=> int(13) ["ID"]=> int(14) ["IsActive"]=> bool(true) ["IsUnsubscribed"]=> bool(false) ["ListID"]=> int(4) ["ListName"]=> string(4) "TEST" ["UnsubscribedAt"]=> string(0) "" } 

array(7) { ["ContactID"]=> int(14) ["ID"]=> int(15) ["IsActive"]=> bool(true) ["IsUnsubscribed"]=> bool(false) ["ListID"]=> int(4) ["ListName"]=> string(4) "TEST" ["UnsubscribedAt"]=> string(0) "" } `
```

I have different ContactIDs for a given mail-address.
And no of the Lists belongs to the given ListID.

[I've changed the original list-names here.]

What is wrong with this request?

**Comment by GuillaumeBadi** [comment]
Hey @wfabian !

In a GET request, the parameters are passed in the `filters` prop, not body, to ensure they are considered as querystring parameters. Does it work for you ?

**Comment by wfabian** [comment]
Yes, of course,
Find it out myself short before your post - Thank you.

So, now I have the ListRecpientID.
Now i want to delete it.

```
        $params = ['body' =>['ID' => $mailjetListRecipientId]];
        $response = $mailjet->delete(Resources::$Listrecipient,$params);
```
Doesn't matter if i use "body" or not.

My Response:

`array(3) { ["ErrorInfo"]=> string(0) "" ["ErrorMessage"]=> string(18) "Method not allowed" ["StatusCode"]=> int(405) } `

**Comment by GuillaumeBadi** [comment]
The params can have 3 fields, `body`, `id` and `filters`
```
$response = $mailjet->delete(Resources::$Listrecipient, [ 'id' => $mailjetListRecipientId ]);
```
should works. You don't need the body when you just provide an ID

**Comment by wfabian** [comment]
I'm gettin the same response:

`array(3) { ["ErrorInfo"]=> string(0) "" ["ErrorMessage"]=> string(18) "Method not allowed" ["StatusCode"]=> int(405) }`

**Comment by GuillaumeBadi** [comment]
Can you print out these values ?
```
$response->request->getUrl()
$response->request->getFilters()
$response->request->getBody()
```

**Comment by wfabian** [comment]
Hi,
I've to check something else.

It seems to be working - But I don't know why.
My contacts where be deleted from Mailjet - So the API worked.
But I didn't recognized it ...

I will reply if i will find a bug or something else ...

**Comment by wfabian** [comment]
Let's close and reopen it, if i have another question :-)

Thank you very much, again!

**Comment by GuillaumeBadi** [comment]
Ok no problem! always happy to help!

**Comment by wfabian** [comment]
Here we go with another problem with adding contacts:

I've the same lists on my system like mailjet.
So i want to sync the lists.

I loop over all lists and contacts if needed.
The contact-add function works - But only if i do a "die()".

So i loop over contacts and add them to mailjet.

```
                $temp = $this->addMailjetRecipient($mailjet, $list[0]['ID'], $contactName, $address->getMail());
                if($temp[0]["Email"] == "last-address@mail.net") {
                    var_dump($temp);
                    die();
                }
```

But if there is no die(); the recipients will not be added in mailjet.
last-address@mail.net is the last mail address in list, so i check if it is added.

$temp has the value of the response from mailjet.

**Comment by GuillaumeBadi** [comment]
Are you using `$temp->getData()` ?

**Comment by wfabian** [comment]
The addMailjetRecipient-function returns :

```
        if($response->success()) {
            if($response->getData()) {
                return $response->getData();
```

**Comment by wfabian** [comment]
It seems to be working, if i don't add every single contact and use ManageManyContacts instead. (it is the better way, too)

But would be nice to know, why the die(); was needed.

**Comment by GuillaumeBadi** [comment]
I don't get what the die function do (?)

**Comment by wfabian** [comment]
http://php.net/manual/en/function.die.php

**Comment by GuillaumeBadi** [comment]
Ow my bad, yes indeed, strange then .. But anyway yes, to add multiple contacts, it is better to make one call instead of many.

Sorry I can't help you with the die problem, but I hope it's working well now

**Comment by wfabian** [comment]
At the moment everything seems to be working. 
Thank you!
