### ISSUE TITLE
api Mailjet ne fonctionne pas chez l'hebergeur

### ISSUE THREAD

**Issue by dl2015med** [mailjet/mailjet-apiv3-php#41]
bonjour,
dans quel repertoire copier les fichiers api mailjet (no composer v3) chez mon hebergeur?
en local ça fonctionne! mais pas quand je copie la meme arborescence dans httpdocs chez mon hebergeur!
merci pour votre aide.

**Comment by GuillaumeBadi** [comment]
Hey @dl2015med !

Tu aurais un peu plus de details sur ton probleme ? l'erreur géneree, ta version de php chez l'hebergeur ?

Thanks,
Guillaume

**Comment by GuillaumeBadi** [comment]
J'espere que tu as trouvé ta solution. Tu peux réouvrir l'issue dans le cas contraire
