### ISSUE TITLE
getting 400 error with any request

### ISSUE THREAD

**Issue by filipkotoucek** [mailjet/mailjet-apiv3-php#44]
Hello, Im having trouble getting new API working. For any request Im getting 400 error. My credentials are ok.

      //new mailjet API call
      $mj = new \Mailjet\Client($this->api_key,$this->api_secret);

      $response = $mj->get(Resources::$Myprofile);
      Debugger::dump($mj);
      Debugger::dump($response);
      die;

And getting this result:

```
(Mailjet\Client` #f6b5
      apikey private => "xxx" (32)
      apisecret private => "xxx" (32)
      version private => "v3/" (3)
      secure private => TRUE
      call private => TRUE
Mailjet\Response #dbef
      status private => 400
      success private => FALSE
      body private => NULL
      request => Mailjet\Request #45cd
      method private => "GET" (3)
      url private => "https://api.mailjet.com/v3/REST/myprofile" (41)
      filters private => array ()
            body private => "{}" (2)
            auth private => array (2)
                  0 => "xxx" (32)
                  1 => "xxx" (32)
            config private => array (8)
            type => "application/json" (16))

```

To be honest I didn't find much useful in documentation about new version of API. But really want to get it working:)

Im running it on localhost at the time. Do you thing this is the issue?
Thanks

**Comment by GuillaumeBadi** [comment]
I answered on the other one ;)

**Comment by harshalyeole-tudip** [comment]
Can you post the link to answer?
