### ISSUE TITLE
Mailjet\Response does not contain "reasonPhrase"

### ISSUE THREAD

**Issue by mrBulb** [mailjet/mailjet-apiv3-php#46]
This library does not delivery the reasonPhrase on a 400.

It is available in the guzzle via "$response->getReasonPhrase()"
Without this i have to guess whats the problem with my request: https://dev.mailjet.com/guides/?php#send-api-errors

**Comment by GuillaumeBadi** [comment]
The error message in case of a mailjet api error is stored in `$response->getData()`, have you tried to look into that ?

**Comment by GuillaumeBadi** [comment]
Can you paste your code here ?

**Comment by mrBulb** [comment]
Yep, its null.
In this case the 'Recipients' property is missing.

    $body = [
        'FromEmail' => "pilot@mailjet.com",
        'FromName' => "Mailjet Pilot",
        'Subject' => "Your email flight plan!",
        'Text-part' => "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
        'Html-part' => "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!"
    ];
    $response = $this->getProvider()->post(\Mailjet\Resources::$Email, ['body' => $body]);
    $response->success() && var_dump($response->getData());

**Comment by GuillaumeBadi** [comment]
The code is working perfectly fine for me:

``` php
<?php

require 'vendor/autoload.php';

$mailjet = new \Mailjet\Client(getenv('MJ_APIKEY_PUBLIC'), getenv('MJ_APIKEY_PRIVATE'));

$body = [
    'FromEmail' => "api@mailjet.com",
    'FromName' => "Mailjet Pilot",
    'Subject' => "Your email flight plan!",
    'Text-part' => "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
    'Html-part' => "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with yo
    'Recipients' => [[ 'Email' => 'api@mailjet.com' ]]
];
$response = $mailjet->post(\Mailjet\Resources::$Email, ['body' => $body]);
var_dump($response->getStatus());
$response->success() && var_dump($response->getData());
```

**Comment by mrBulb** [comment]
Since your code does contain a valid body i have to ask if you tried with an invalid body to trigger an error?

**Comment by GuillaumeBadi** [comment]
Sadly, the API does not provide an error message when a field like recipient is missing. Just sending back a 400 error ATM

**Comment by mrBulb** [comment]
Luckily it does:

    curl -s -v \
        -X POST \
        --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
        https://api.mailjet.com/v3/send \
        -H 'Content-Type: application/json' \
        -d '{
            "FromEmail":"pilot@mailjet.com",
            "FromName":"Mailjet Pilot",
            "Subject":"Your email flight plan!",
            "Text-part":"Dear passenger, welcome to Mailjet! May the delivery force be with you!",
            "Html-part":"<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!"
    }'

Part of the response:

    < HTTP/1.1 400 Missing "To" or "Recipients" property

**Comment by GuillaumeBadi** [comment]
I have added the raw response + getReasonPhrase method to the response : https://github.com/mailjet/mailjet-apiv3-php/releases/tag/v1.1.2

**Comment by mrBulb** [comment]
Thank you very much!
