### ISSUE TITLE
Erreur json_encode() expects at most 2 parameters, 3 given

### ISSUE THREAD

**Issue by polak25** [mailjet/mailjet-apiv3-php#47]
Bonjour,

j'ai cette erreur et je ne trouve pas de solution :

```
Warning:` json_encode() expects at most 2 parameters, 3 given in vendor/guzzlehttp/guzzle/src/functions.php on line 323

Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset() in guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78
```

Mon code est simple

```
<?php require 'vendor/autoload.php';

use \Mailjet\Resources;

$apikey = 'xxx';
$apisecret = 'xxx';

$mj = new \Mailjet\Client($apikey, $apisecret);

debug($mj);

$body = [
    'FromEmail' => "test@test.com",
    'FromName' => "Mailjet Pilot",
    'Subject' => "Your email flight plan!",
    'Text-part' => "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
    'Html-part' => "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
    'Recipients' => [['Email' => "test@gmail.com"]]
];

$response = $mj->post(Resources::$Email, ['body' => $body]);

debug($response);
```

**Comment by GuillaumeBadi** [comment]
Hey ! Tout marche bien pour moi avec ce code, est ce que la lib tourne sur la derniere version du wrapper ?

**Comment by polak25** [comment]
Oui normalement,

guzzlehttp/guzzle           6.2.0  Guzzle is a PHP HTTP client library
guzzlehttp/promises         1.1.0  Guzzle promises library
guzzlehttp/psr7             1.3.0  PSR-7 message implementation
mailjet/mailjet-apiv3-php   v1.1.2 PHP wrapper for the Mailjet API
mikehaertl/php-shellcommand 1.2.0  An object oriented interface to shell co...
mikehaertl/php-tmpfile      1.0.0  A convenience class for temporary files
mikehaertl/phpwkhtmltopdf   2.1.1  A slim PHP wrapper around wkhtmltopdf wi...
phpxmlrpc/phpxmlrpc         4.0.1  A php library for building xmlrpc client...
psr/http-message            1.0    Common interface for HTTP messages
setasign/fpdf               1.8.1  FPDF is a PHP class which allows to gene...
setasign/fpdi               1.6.1  FPDI is a collection of PHP classes faci...

**Comment by GuillaumeBadi** [comment]
Etrange.. Je n'arrive pas a reproduire l'erreur. Quelle version de PHP tourne sur ton environement ?

**Comment by polak25** [comment]
Hélas pour ce site je suis en 5.4.42

**Comment by polak25** [comment]
Tu m'a donné une idée, je suis passé en version inférieur de guzzlehttp/guzzle, de 6.2.0 à 5.3.0 et cela fonctionne.

Merci !

**Comment by GuillaumeBadi** [comment]
La version minimum, c'est PHP 5.4 donc ça c'est bon. C'est bizarre pour Guzzle, il devrait etre [supporté](https://github.com/mailjet/mailjet-apiv3-php/blob/master/composer.json#L16), mais content que ça ait pu t'aider

**Comment by polak25** [comment]
Normalement oui, il faudrait leur dire ;-)

Encore merci !
