### ISSUE TITLE
PHP Fatal error: Call to undefined function GuzzleHttp\\Handler\\curl_reset()

### ISSUE THREAD

**Issue by Coleim** [mailjet/mailjet-apiv3-php#49]
Hello,

I am trying to use mailjet with my PHP version 5.4.27

When I call `$mj->post(Resources::$Email, ['body' => $body]);`, the mail is well sent, but then the process is stopped and I got an error: 

`PHP Fatal error:  Call to undefined function GuzzleHttp\\Handler\\curl_reset() in C:\\Apache2.2\\htdocs\\mailjet\\mailjet-apiv3-php\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php on line 78`

According to [the doc](http://php.net/manual/fr/function.curl-reset.php), it seems that curl_reset is available only for php >= 5.5.0.

In your doc, requirements is set to PHP >= 5.4. 

Could you please check if a fix could be provided ?

Thanks a lot.
Cheers

**Comment by GuillaumeBadi** [comment]
Hey @Coleim !

Have you imported another version of guzzle in your project ?
It is know to create problems like that

**Comment by Coleim** [comment]
Hello,

I don't think so, I got the zipped version of the repo.
For now, I just comment the `curl_reset()` line, but I think it is not good :)

**Comment by GuillaumeBadi** [comment]
Can you try to change the guzzle version to 5.3.0 in you composer file and `composer install` again ?

**Comment by GuillaumeBadi** [comment]
Any news on this ? @Coleim

**Comment by Coleim** [comment]
Hello,

I cannot test it using composer, cause I am on a client windows machine, and I just download the tarball.
I just comment the call to `curl_reset() ` in the code and it works fine.

**Comment by GuillaumeBadi** [comment]
Glad it works for you! Thanks for using Mailjet.

By the way, you should really have a look at the community work around composer, which works fine on Windows :) https://github.com/composer/windows-setup

**Comment by Coleim** [comment]
Thanks, I'll take a look. :)
