### ISSUE TITLE
Packagist declaration

### ISSUE THREAD

**Issue by baptistedonaux** [mailjet/mailjet-apiv3-php#5]
I would use this lib for my PHP project but I see that only the lite version has been declared in Packagist.

It's possible to add it to use Composer.

**Comment by GuillaumeBadi** [comment]
Hey ! @baptistedonaux 

This repo was abandonned :(

We just released a new version of this wrapper and it is available right there 

https://packagist.org/packages/mailjet/mailjet-apiv3-php
