### ISSUE TITLE
Warning in logs: ErrorException [ 2 ]: json_decode(): option JSON_BIGINT_AS_STRING not implemented

### ISSUE THREAD

**Issue by weaverryan** [mailjet/mailjet-apiv3-php#50]
Hi guys!

Apparently, in some distributions of PHP, the `JSON_BIGINT_AS_STRING` ability is not implemented. This leads to the logs filling with:

> ErrorException [ 2 ]: json_decode(): option JSON_BIGINT_AS_STRING not implemented

This comes from the `Response::__construct()` method. 

There was actually an issue opened about this already on the old SDK: https://github.com/mailjet/mailjet-apiv3-php-simple/pull/126. So now I'm opening it on the new one :).

The php-jwt library has a work-around for this: https://github.com/firebase/php-jwt/blob/c35d52bd53fafd4a92c72c8e0b8489ebfc1a4306/src/JWT.php#L249 - perhaps that could be used... or maybe the `JSON_BIGINT_AS_STRING` constant isn't needed?

Thanks!

**Comment by GuillaumeBadi** [comment]
Hey @weaverryan ! This should fix it: https://github.com/mailjet/mailjet-apiv3-php/pull/48/files

**Comment by GuillaumeBadi** [comment]
Please make sure it works for you with the last release

**Comment by weaverryan** [comment]
It does! Thanks @GuillaumeBadi! I somehow missed that PR (#48) - you rock!
