### ISSUE TITLE
Make getApiUrl public or protected, to allow for CI testing

### ISSUE THREAD

**Issue by hilnius** [mailjet/mailjet-apiv3-php#53]
Hi

I'd like to create a subclass that overrides the api URL (getApiUrl function in Client.php), so I can use a server that I own to test my emails without having to have real email adresses and spam the world. :)

https://github.com/mailjet/mailjet-apiv3-php/blob/master/src/Mailjet/Client.php#L88

Is it possible ? Why is this method private in the first place ?

Thanks !

**Comment by GuillaumeBadi** [comment]
Interesting, I hadn't thought about that use case, so I made it private, but actually, you can instanciate the MailjetClient with the $call parameter set to false, to prevent the wrapper to actually trigger the call. (https://github.com/mailjet/mailjet-apiv3-php/blob/master/src/Mailjet/Client.php#L41)

Then, you can use the default methods such as `$response->request->getUrl` `$response->request->getBody` etc.. https://github.com/mailjet/mailjet-apiv3-php/blob/master/src/Mailjet/Request.php

But yes, If you need to make it public, you can open a Pull Request, and I would merge it quickly!

Thanks,
Guillaume

**Comment by GuillaumeBadi** [comment]
Any news here ? Have you managed to make it work ?

**Comment by hilnius** [comment]
Hey, sorry I'm really busy. The problem with the parameter set to false is that you're not sure that your call gets triggered once and only once. What I have is a server that mocks yours and I replace the getApiUrl with my local URL so that I can almost end-to-end test it. 
As I don't really have the time I've just copied and pasted the Client.php code in another file and I use this other copied client (instead of having proper inheritance).

I'll try to create the PR this weekend if I get the time to do so.

**Comment by Zhivko-Mailjet** [comment]
@hilnius 
We are preparing a release of new SendAPI v3.1
@aridjar will add the feature you suggested with the upcoming release. Will keep you posted!

**Comment by HankBrown** [comment]
ETA on the new release? I'm guessing this is an internal error from guzzle.
Or some issue with psr loading in a non-composer environment.
I find no errors in my logs, just this response.
Wish you could make this stand alone: guzzle is holding up more than one project lately.
If I had seen it listed as a requirement I would have started with a different approach...
KISS. Let the hard-core guys guzzle and psr and compose to their jet's content..
```
Mailjet\Response::__set_state(array(
   'status' => 500,
   'success' => false,
   'body' => NULL,
   'rawResponse' =>
  GuzzleHttp\Psr7\Response::__set_state(array(
     'reasonPhrase' => 'Access violation',
     'statusCode' => 500,
     'headers' =>
    array (
      'Server' =>
      array (
        0 => 'nginx',
      ),
      'Date' =>
      array (
        0 => 'Tue, 20 Dec 2016 19:55:25 GMT',
      ),
      'Content-Type' =>
      array (
        0 => 'text/html',
      ),
      'Content-Length' =>
      array (
        0 => '0',
      ),
      'Connection' =>
      array (
        0 => 'keep-alive',
      ),
      'Vary' =>
      array (
        0 => 'Accept-Encoding',
      ),
    ),
     'headerNames' =>
    array (
      'server' => 'Server',
      'date' => 'Date',
      'content-type' => 'Content-Type',
      'content-length' => 'Content-Length',
      'connection' => 'Connection',
      'vary' => 'Vary',
    ),
     'protocol' => '1.1',
     'stream' =>
    GuzzleHttp\Psr7\Stream::__set_state(array(
       'stream' => NULL,
       'size' => 0,
       'seekable' => true,
       'readable' => true,
       'writable' => true,
       'uri' => 'php://temp',
       'customMetadata' =>
      array (
      ),
    )),
  )),
   'request' =>
  Mailjet\Request::__set_state(array(
     'method' => 'POST',
     'url' => 'https://api.mailjet.com/v3/send',
     'filters' =>
    array (
    ),
     'body' =>
    array (
      'FromName' => 'REDACTED',
      'FromEmail' => 'xxx',
      'Subject' => 'xxx',
      'Text-part' => 'Plain body text here',
      'Recipients' =>
      array (
        0 => 'xxx@xxx.com',
      ),
    ),
     'auth' =>
    array (
      0 => 'KEY REDACTED',
      1 => 'KEY REDACTED',
    ),
     'type' => 'application/json',
     'config' =>
    array (
      'defaults' =>
      array (
        'headers' =>
        array (
          'user-agent' => 'mailjet-apiv3-php-no-composer/5.5.9-1ubuntu4.4/v1.1.8',
        ),
      ),
      'handler' =>
      GuzzleHttp\HandlerStack::__set_state(array(
         'handler' =>
        Closure::__set_state(array(
        )),
         'stack' =>
        array (
          0 =>
          array (
            0 =>
            Closure::__set_state(array(
            )),
            1 => 'http_errors',
          ),
          1 =>
          array (
            0 =>
            Closure::__set_state(array(
            )),
            1 => 'allow_redirects',
          ),
          2 =>
          array (
            0 =>
            Closure::__set_state(array(
            )),
            1 => 'cookies',
          ),
          3 =>
          array (
            0 =>
            Closure::__set_state(array(
            )),
            1 => 'prepare_body',
          ),
        ),
         'cached' =>
        Closure::__set_state(array(
        )),
      )),
      'allow_redirects' =>
      array (
        'max' => 5,
        'protocols' =>
        array (
          0 => 'http',
          1 => 'https',
        ),
        'strict' => false,
        'referer' => false,
        'track_redirects' => false,
      ),
      'http_errors' => true,
      'decode_content' => true,
      'verify' => true,
      'cookies' => false,
      'headers' =>
      array (
        'User-Agent' => 'GuzzleHttp/6.2.1 curl/7.35.0 PHP/5.5.9-1ubuntu4.4',
      ),
    ),
  )),
))

```

**Comment by latanasov** [comment]
[Send API v3.1 ](https://dev.mailjet.com/guides/#send-api-v3-1) is released .
