### ISSUE TITLE
Guzzle ServerException Uncaught

### ISSUE THREAD

**Issue by axi** [mailjet/mailjet-apiv3-php#55]
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ServerException' with message 'Server error: `POST https://api.mailjet.com/v3/send` resulted in a `502 Bad Gateway` response

**Comment by axi** [comment]
update Request.php should do the trick:
line 84

            catch (ClientException $e) {
                $response = $e->getResponse();
            }

=>

            catch (ClientException $e) {
                $response = $e->getResponse();
            }
            catch (ServerException $e) {
                $response = $e->getResponse();
            }

**Comment by GuillaumeBadi** [comment]
Hey ! Thanks for reporting ! Can you open a PR for this one to make your code work ? (or paste your code example for me to reproduce the error)
