### ISSUE TITLE
CustomID not persisted

### ISSUE THREAD

**Issue by rcontegni-ah** [mailjet/mailjet-apiv3-php#57]
Hello,
I've been trying to use the CustomID in the emails I send, so I can identify them when I parse them in the call to my webhook.
However, the Mj-CustomID doesn't seem to be saved.

Sent using
```
curl -s \
    -X POST \
    --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
    https://api.mailjet.com/v3/send \
    -H 'Content-Type: application/json' \
    -d '{
        "FromEmail":"pilot@mailjet.com",
        "FromName":"Mailjet Pilot",
        "Subject":"Your email flight plan!",
        "Text-part":"Dear passenger, welcome to Mailjet! May the delivery force be with you!",
        "Html-part":"<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
        "Recipients":[{"Email":"passenger@mailjet.com"}],
        "Mj-CustomID":"PassengerEticket1234"
    }' 
```

Returns
`{ "Sent" : [{ "Email" : "passenger@mailjet.com", "MessageID" : 18295938938421304 }] }`

Then
```
curl -s \
    -X GET \
    --user "$MJ_APIKEY_PUBLIC:$MJ_APIKEY_PRIVATE" \
    https://api.mailjet.com/v3/REST/messagesentstatistics?CustomID=PassengerEticket1234
```

Returns
`{ "Count" : 0, "Data" : [], "Total" : 0 }`

Am I missing anything?
Thanks!!

**Comment by GuillaumeBadi** [comment]
In order to get additional informations on your issue (which is not directly related to the PHP wrapper), can you open a Support Ticket on https://fr.mailjet.com/support ?

Guillaume
