### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by ejeanneaubc** [mailjet/mailjet-apiv3-php#58]
Hello,

Je ne comprends pas du tout comment fonctionnent les statistiques avec l'API V3.

Quelqu'un peut-il me donner un exemple concret de récupération de stats via un ID NEWSLETTER. (Ouvertures, Clics, Bounces).

J'ai beau tout retourner, rien ne fonctionne pour moi.

Exemple de code : 

```
$mj = new \Mailjet\Client(env('MAILJET_API_KEY', ''), env('MAILJET_PRIVATE_KEY', ''));

    	$customvalue = "mj.nl=17431";

	    $params = array(
	        "method" => "VIEW",
	        "unique" => $customvalue
	    );

			$response = $mj->get(\Mailjet\Resources::$Campaignstatistics, $params);
			
			$data = $response->getData();
```

Cela me retourne toutes les listes sauf celle que je veux, etc..

Merci beaucoup pour votre aide !

Emmanuel.

**Comment by GuillaumeBadi** [comment]
Hello @ejeanneaubc !

Je t'invite a poster un ticket sur [notre support](https://www.mailjet.com/support) comme ce n'est pas vraiment lié au client API, mais a l'API en elle meme.

Merci,
Guillaume

**Comment by ejeanneaubc** [comment]
Merci @GuillaumeBadi !

C'est chose faite !

Bonne journée,

Emmanuel.
