### ISSUE TITLE
Message ID différents

### ISSUE THREAD

**Issue by RobinAlex** [mailjet/mailjet-apiv3-php#59]
Hello,

J'utilise l'api de mailjet pour envoyer mes mails, l'envoi se passe bien. Le hic c'est quand je souhaite récupérer le statut d'un message (envoyé, bloqué etc ...).

Le retour de l'api me donne bien un ID, mais lorsque j'appel la fonction de récupération du message par cet ID, le message est introuvable. Mais si je remplace mon ID par le 2eme (voir screen) le message est bien trouvé

![api-mailjet](https://cloud.githubusercontent.com/assets/5709691/16583905/ece536c8-42b8-11e6-94c6-40dc7547ae0f.PNG)

Sur le screen on peut voir que les deux ID diffères, mais je ne parviens pas à récupérer le 2eme pour pouvoir afficher les informations relatives à un message.

J’espère que ma demande est assez claire
Merci, bonne journée

**Comment by GuillaumeBadi** [comment]
Hey @RobinAlex !

What version of the wrapper are you using ?
because I guess the MessageID is rounded (only the last digit is different)

Guillaume

**Comment by RobinAlex** [comment]
Hey @GuillaumeBadi !

Je viens de mettre à jour ma version, je suis donc en 1.1.5.

Petite précision, je ne sais pas si cela joue sur le comportement de l'api, mon soucis d'ID se présente lorsque je tente de récupérer l'ID d'un message que je viens de transmettre à l'API.

J'ai actuellement un bout de code ou j'utilise 'Messagesentstatistics' avec mes ID (MessageID) qui fonctionne. 
Comme ci après un certain délai l'API comprend finalement que mon ID existe bel et bien

**Comment by GuillaumeBadi** [comment]
Oui, en fait le message est enregistré apres un court instant dans l'API. Essayer de le recupérer direct apres l'envoie peut etre problématique dans la plupart des cas

**Comment by RobinAlex** [comment]
Ok, je me doutais bien qu'il y avait quelque chose du genre. Mais dans tout les cas l'ID que l'API me renvoi à la création du message semble bon puisque ma récupération de stats fonctionne.

J'ai également eu un soucis de long integer convertit en double, que j'ai résolu en mettant à jour le wrapper justement.

Merci de tes lumières @GuillaumeBadi !
