### ISSUE TITLE
Correct way to include an Emoji in the subject

### ISSUE THREAD

**Issue by Elexy** [mailjet/mailjet-apiv3-php#60]
I have tried to include an emoji in the subject line and I see them being sent into the library, but on the receiving end of the email, the emoji never arrives. It's seems like it is being stripped.

These are some variations of what I tried:
```
$emoji = json_decode('"\uD83D\uDCB8"');
$emoji = html_entity_decode('&#x1f4b8;');
```

**Comment by GuillaumeBadi** [comment]
Hey @Elexy !
It looks like a bug in the API. We are working on it as we talk. The only way to manage emoji is to use the SMTP server at the moment.

Guillaume
