### ISSUE TITLE
Mocking Responses

### ISSUE THREAD

**Issue by bretto36** [mailjet/mailjet-apiv3-php#62]
I'm trying to write some test cases for the Omnimail library - https://github.com/gabrielbull/omnimail

I need to pass in some mock responses to the Client to get it to return and process them. I've done a couple of the other gateways using Guzzle MockHandler (but your implementation doesn't use Guzzle)

Any chance you could build in some sort of Mock system? I'd be willing to do it if you could give some direction on how you'd like it to happen.

**Comment by bretto36** [comment]
Just realised you ARE using guzzle - i'll keep you posted with how i go getting mocks in there

**Comment by GuillaumeBadi** [comment]
Hey @bretto36 ! Amazing! We are definitely going to feature your work in our documentation!

I don't really get what you are looking for here. You want the client to prevent the Http call right ?
you just need to pass a third parameter to the constructor. https://github.com/mailjet/mailjet-apiv3-php/blob/master/src/Mailjet/Client.php#L41 . `false` will return a response without actual data/status

**Comment by bretto36** [comment]
I can prevent the actual call (using the flag), but what i'm hoping to achieve is to simulate a response. EG I have an app where i want to test that the mail is sent and handles valid responses. I want to be able to see what it will do if i provide it with an error response and with a success response so i can ensure it fails gracefully and provides a meaningful error

**Comment by Zhivko-Mailjet** [comment]
@bretto36 
We are about to release new version of our Send API v3.1. In there, we will have new mode called Sandbox mode. When set to true, the Send API processes the message as usual, validating the input payload but does not actually drop the message in the sending queue. When everything’s OK, it returns a 200 OK, using the success payload with fake IDs in it.
I believe this is similar to what you would like to achieve. The release of the new SendAPI is coming soon, stay tuned!

**Comment by wysow** [comment]
@Zhivko-Mailjet really great to hear that as this is exactly the feature I need right now ;), can you provide an approximate release date? (maybe an exact one... ;))

**Comment by Zhivko-Mailjet** [comment]
Hi @wysow , We are doing some final tests and we are preparing the release. I can not give you exact date yet but it will be in the coming days/weeks. We will keep you posted!

**Comment by wysow** [comment]
@Zhivko-Mailjet thanks for the feedback, really would like to be part of this beta if possible, what's the process to be in?

**Comment by Zhivko-Mailjet** [comment]
Hi @wysow,
I'm happy to hear you are interested in testing our new API. Please contact [our support](https://www.mailjet.com/support/ticket), selecting the API category, for details.

**Comment by wysow** [comment]
Done @Zhivko-Mailjet thanks.

**Comment by tentacode** [comment]
@wysow @Zhivko-Mailjet is 3.1 out now ? Can't find anywhere in the doc for a sanbox flag (or the 3.1 changelog)

**Comment by Zhivko-Mailjet** [comment]
@wysow @tentacode @bretto36 
The new SendAPI beta is live. It has the Sandbox mode, which allows you to simulate the sending, verifyting the payload. See more details here:
https://dev.mailjet.com/beta/#sandbox-mode

**Comment by dunglas** [comment]
Hi @Zhivko-Mailjet,

I've just tried this feature but even if I set the `SandBoxMode` flag, the mail is sent. The code is wrote:

```php
    public function send(int $templateId, array $toUsers, array $vars = []): bool
    {
        $recipients = [];
        foreach ($toUsers as $user) {
            $recipients[] = [
                'Email' => $user->getEmail(),
                'Name' => \sprintf('%s %s', $user->getFirstname(), $user->getLastname()),
                'Vars' => $vars,
            ];
        }

        $body = [
            'FromEmail' => $this->fromEmail,
            'MJ-TemplateID' => $templateId,
            'MJ-TemplateLanguage' => true,
            'Recipients' => $recipients,
        ];

        if ($this->sandbox) {
            $body['SandboxMode'] = true;
        }

        $response = $this->mailjet->post(Resources::$Email, ['body' => $body]);

        if ($response->success()) {
            return true;
        }

        $this->logger->critical('Mailjet error: {error}', ['error' => $response->getReasonPhrase()]);

        return false;
    }
```

Am I doing something wrong?

**Comment by Zhivko-Mailjet** [comment]
Hi @dunglas 

The Sandbox mode is new functionality, which works in our new SendAPI v3.1. In order to take advantage of it, you have to switch the API versions and adapt your code as per the new requirements. See sample code below:

`require 'vendor/autoload.php';
use \Mailjet\Resources;
$mj = new \Mailjet\Client(getenv('MJ_APIKEY_PUBLIC'), getenv('MJ_APIKEY_PRIVATE'),true,['version' => 'v3.1']);
$body = [
    'Messages' => [
        [
            'From' => [
                'Email' => "pilot@mailjet.com",
                'Name' => "Mailjet Pilot"
            ],
            'To' => [
                [
                    'Email' => "passenger1@mailjet.com",
                    'Name' => "passenger 1"
                ]
            ],
            'Subject' => "Your email flight plan!",
            'TextPart' => "Dear passenger 1, welcome to Mailjet! May the delivery force be with you!",
            'HTMLPart' => "<h3>Dear passenger 1, welcome to Mailjet!</h3><br />May the delivery force be with you!"
        ]
    ],
    'SandboxMode' => true
];
$response = $mj->post(Resources::$Email, ['body' => $body]);
$response->success() && var_dump($response->getData());`


Additional information you can find in our guides:
https://dev.mailjet.com/beta/?php#send-api-v3-to-v3-1

**Comment by dunglas** [comment]
Thanks, it works now. However there is an issue in the example in https://dev.mailjet.com/beta/?php#using-a-template:

`\Mailjet\Client(getenv('MJ_APIKEY_PUBLIC'), getenv('MJ_APIKEY_PRIVATE'),['version' => 'v3.1']);` the 3rd parameter (`true`)  is missing.

**Comment by Zhivko-Mailjet** [comment]
Thanks for reporting that. We have also spotted the error. It is now fixed.
