### ISSUE TITLE
MessageID in response is returned as a rounded number with exponant

### ISSUE THREAD

**Issue by Piriou** [mailjet/mailjet-apiv3-php#63]
Hi,

I run two version of the same program using the API.
- one on my local Apache server under PHP 5.6.10 : it works well ;
- one on a distant server, under PHP 5.4

With that second server, I have an issue. The response returned when i send an email gives me a MessageID as a rounded number like : 2.054774882955E16

With my local version, the MessageID is a complete number like 18014470552713635 

I think I misconfigured something but I don't know where I can find a solution. Any idea to help ?

Thank you !

**Comment by GuillaumeBadi** [comment]
Hey @Piriou !

What version of the wrapper are you using ?

**Comment by Piriou** [comment]
Oh, sorry, I am in the wrong section. I use mailjet-apiv3-php-no-composer. I didn't notice that there was a new and more easy to use mailjet-apiv3-php. Forget my question, I will run other test with this new wrapper. You can delete that thread, I'm sorry.

**Comment by GuillaumeBadi** [comment]
No problem!
