### ISSUE TITLE
noComposer

### ISSUE THREAD

**Issue by ariouche** [mailjet/mailjet-apiv3-php#65]
Hi,
I've dowloaded the nocomposer project and I get that:
`Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset() in /myfolders/libraries/MJ/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78`

Here is my code:

require "/myfolders/libraries/MJ/vendor/autoload.php";
$mj = new \Mailjet\Client($this->apiKey, $this->secretKey);
$body = [
    'FromEmail' => "support@domain.com",
    'FromName' => "Mailjet Pilot",
    'Subject' => "Your email flight plan!",
    'Text-part' => "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
    'Html-part' => "hello",
    'Recipients' => [['Email' => "support@domain.com"]]
];
$response = $mj->post(\Mailjet\Resources::$Email, ['body' => $body]);

Any ideas?
Thanks

**Comment by ariouche** [comment]
Hi, I've found a solution, I just comment the call to curl_reset() in the code and it works fine.

A small question, using that method https://dev.mailjet.com/guides/?php#sending-to-multiple-recipients, how many emails can we send over?

**Comment by arnaudbreton** [comment]
Hi @ariouche, sorry for the delay in our answer.

You're right, the no-composer version comes with a Guzzle version which is compatible only with PHP > 5.5. What PHP version are you using?

About your second question, you should limit to a 100 messages per call.
I'm closing this issue now since you say you've found a workaround.

**Comment by ariouche** [comment]
Hi, thanks
another question. Let's say I sent messages and deliberately the same email could be used. How could I get the different value of the `MessageID` variable for the same email?

**Comment by arnaudbreton** [comment]
Hi @ariouche, if you mean messages sent in the same call, our API will give back the collection of all the messages sent:

```
{ "Sent" : [{ "Email" : "passenger1@mailjet.com", "MessageID" : 20547757637575000 }, { "Email" : "passenger2@mailjet.com", "MessageID" : 20547757637575001 }] }
```

Hope it helps.

**Comment by ariouche** [comment]
Hi, but If i use the same email in the same call, I'd get that
`{ "Sent" : [{ "Email" : "passenger@mailjet.com", "MessageID" : 20547757637575000 }, { "Email" : "passenger@mailjet.com", "MessageID" : 20547757637575001 }] }`
and it would be impossible to distinguished which MessageID is attached to the 1st and the 2nd email. The reason I ask is because, in our process, each email sent should be logged  in our database for tracking opens/clicks and it's possible to deliver the same message to the same email multiple time.
So for ex, if i need to send a message to passenger@mailjet.com 10x, I need to be able to get the 10 MessageID in the correct order I've sent them. 

A way to do it should be: if I mark each message by adding a payload var, it could be thus possible to get the payloads in the response "Sent"?

Hope it's not confusing
