### ISSUE TITLE
Response always null 

### ISSUE THREAD

**Issue by KLeval** [mailjet/mailjet-apiv3-php#66]
Hi, 

I tried this project with composer, I created a contactlist  with this code 

`$body = [
        'Name' => 'mynewlist'
    ];
    $response = $this->_con->post(Resources::$Contactslist, ['body' => $body]);`

It worked, i can see my fresh list in mailjet, but the response is always "null", in fact, every request i do, the response is always null.

**Comment by arnaudbreton** [comment]
Hi @KLeval, sorry for the delay.

How do you print the `$response`? If you use the sample [here](https://github.com/mailjet/mailjet-apiv3-php#make-your-first-call), it doesn't work either?

**Comment by KLeval** [comment]
Yes, your sample below display always " null " 

if ($response->success())
  var_dump($response->getData());
else
  var_dump($response->getStatus());

**Comment by arnaudbreton** [comment]
Interesting. What PHP version / OS are you using?

**Comment by KLeval** [comment]
Windows 10, Wamp, PHP 5.5.12

**Comment by arnaudbreton** [comment]
Sounds like it should work but I have no Windows environment to test at the moment. 

Are you displaying PHP errors?
