### ISSUE TITLE
Invalid json input on Contactdata PUT

### ISSUE THREAD

**Issue by DelhiKTaisse** [mailjet/mailjet-apiv3-php#67]
Hi,
I'm trying to update a contact data via API user the wrapper. Thought, I have an error as response.
Here is what I send to the wrapper : 
`$this->mj->put(\Mailjet\Resources::$Contactdata, [ 'id' => 'mymail@test.com', 'body' => [['Name' => 'firstname', 'value' => 'John']] ]);`

Here is the error I get : 

> array(3) {
>     ["ErrorInfo"]=>
>     string(0) ""
>     ["ErrorMessage"]=>
>     string(88) "Invalid json input: expected "]", but found "{" at stream position 2 ...[{|"Name":"fi..."
>     ["StatusCode"]=>
>     int(400)
>   }

would there be a quick patch to apply there, or would I have better call the API without wrapper for that type of query please ?

**Comment by eboisgon** [comment]
Hello, 

Seems like you have an error in the format of your body here : 

`$this->mj->put(\Mailjet\Resources::$Contactdata, [ 'id' => 'mymail@test.com', 'body' => [['Name' => 'firstname', 'value' => 'John']] ]);
`

should be 

`$this->mj->put(\Mailjet\Resources::$Contactdata, [ 'id' => 'mymail@test.com', 'body' => ['Data' => [['Name' => 'firstname', 'value' => 'John']]] ]);
`

See [here](https://dev.mailjet.com/guides/?php#adding-custom-static-contact-data)
 for more details

**Comment by DelhiKTaisse** [comment]
thank you it works now !
