### ISSUE TITLE
ContactsListManageContact not update contact Properties

### ISSUE THREAD

**Issue by kappuccino** [mailjet/mailjet-apiv3-php#68]
Hello,

I try to figure out why i can't update or insert contact properties while subscribing to a list.
After the request, the contact is in the list, but any properties i gave are never updated. If i update one of them from the mailjet dashboard, i can see it in the response

```
$body = [
			'Email' => $email,
			'Action' => 'addforce',
			'Properties' => json_encode([
				"gamme_z" => "oui",
			])
		];
		
		$response = $this->mj->post(
			Resources::$ContactslistManagecontact, [
				'id' => $listId,
				'body' => $body
			]
		);
```

the response contains the ContactID, Email, Action, Name and some Properties, but not the one i gave in the request (the property exists, as i can see/update it when i edit a contact from my dashboard)

If i need to make an other request just for updating the properties, this is not a problem, but the document does not expose any endpoint for this.

Any idea ?
Thank you

**Comment by eboisgon** [comment]
Hello Kappuccino, 

The wrapper is taking care of encoding the body you are passing as a JSON. 
Here you are encoding part of the $body in JSON and this is probably causing your problem. 

`$body = [
            'Email' => $email,
            'Action' => 'addforce',
            'Properties' => json_encode([
                "gamme_z" => "oui",
            ])
        ];`
 
should be 

`$body = [
            'Email' => $email,
            'Action' => 'addforce',
            'Properties' => [
                "gamme_z" => "oui",
            ]
        ];`

hope it helps

eboisgon

**Comment by kappuccino** [comment]
If I try you solution the API error is "Property type does not match definition"
so I guess, this is up to me to encode the field on JSON right ?

**Comment by eboisgon** [comment]
What is the type you defined for this property 'gamme_z'  (boolean, string, integer) ? 

Here you are sending a string and the API resource doesn't seems to like it .

You can check your property definition in the UI [here](https://app.mailjet.com/contacts/lists/properties).

**Comment by kappuccino** [comment]
gamme_z is a simple string, i will try to test with a boolean property.
the api response is "Property type does not match definition" what does that mean ?

**Comment by kappuccino** [comment]
i made some tests.
every property I use, there is no updated

**Comment by kappuccino** [comment]
Hello again,
can you provide a full exemple maybe I am doing something wrong
thank you for your help & your support

**Comment by eboisgon** [comment]
Hello, 

We discovered a problem on the resource you are trying to use related to the update of properties. Our development team is already working on fixing it. 

I will let you know when the fix is available.

Regarding the error "Property type does not match definition" , do you still have this response from our API. I rechecked and did a test with a string in the payload to update a contact property of type Integer and received this exact error. 

Could you share with me the result of a GET on your contactmetadata to see the structure of your contact properties?

**Comment by kappuccino** [comment]
héhé 👍 that's good now. I can update my Properties
no more error, the result is the contact object with all the properties related to.

gammez is a Boolean, because you know, i change my mind about it :)
The result is:
```
[ContactID] => xxxxxxxxx
[Email] => yyyyy
[Action] => addforce
[Name] => 
[Properties] => Array(
   [prénom] => Ben
   [nom] => Mos
   [entreprise] => Kappuccino
   [codepostal] => 33290
   [gamme_z] => 1
)
```
thank very much you for your help
