### ISSUE TITLE
Laravel

### ISSUE THREAD

**Issue by szepeviktor** [mailjet/mailjet-apiv3-php#70]
Are you planning to release a proper Laravel Mail Transport implementation?

**Comment by arnaudbreton** [comment]
Hi @szepeviktor, apologies for the delay in our answer.

We plan to release such integration but I can't give you a clear ETA. Yet, we would love to review a contribution from you on the subject.

Best!

**Comment by szepeviktor** [comment]
I think it is less than 50 lines
https://github.com/laravel/framework/blob/5.3/src/Illuminate/Mail/Transport/MandrillTransport.php
and
http://laravel.io/forum/07-26-2015-adding-mail-transport

**Comment by Superanton** [comment]
Hey @arnaudbreton 

Any updates on this? I would like to use Mailjet in a project and an official Laravel driver would be very handy.

**Comment by Zhivko-Mailjet** [comment]
Hey @Superanton ,

Unfortunately, we haven't progressed on this yet. It still remains in our future plans, but at this point we can't provide an ETA.

**Comment by latanasov** [comment]
Hi @Superanton and @szepeviktor, we recently released a [SwiftMailer](https://github.com/mailjet/MailjetSwiftMailer)   transport implementation for Mailjet. We will very soon provide a proper Laravel release which uses it, so stay tuned :) . Apologies for the delay !

**Comment by Nightbr** [comment]
Here we go guys: https://github.com/mailjet/laravel-mailjet

**Comment by szepeviktor** [comment]
+1 for Events (mainly bounces)
