### ISSUE TITLE
Modify content-type to multipart/related instead of multipart/mixed

### ISSUE THREAD

**Issue by Aurelinho** [mailjet/mailjet-apiv3-php#71]
I try to overide content-type of my email

```php
$data=   json_encode([
'FromEmail' => key($message->getFrom()),
            'Recipients' => $recipients,
            'Subject' => $message->getSubject(),
            'Text-part' => $message->getBody(),
            'Html-part' => $message->getBody(),
 'Inline_attachments' => $pj,
            'Headers' => [
                'Content-type' => 'multipart/related;
 ] ,]);

$request = $this->client->post('/v3/send', ['Content-Type' => 'application/json'],$data);
```

REsult in my source email :-1: 
Content-type: multipart/mixed; boundary="=-cQh7nYG1al181j3dCjq6"

**Comment by Aridjar** [comment]
Hi @Aurelinho , apologies for the delay in our answer.

The issue you created appear to be linked to the API itself, not to the php wrapper. The feature you ask for (having a "multipart/related" content type) is not implemented yet. We need to investigate deeper to know and understand the impact of this change on other email clients. We don't have any ETA to communicate you about this feature.

Best !

**Comment by Benoit-amo** [comment]
We had this pb a few month ago, causing Thunderbird to not handle attachments correctly.
Try with the property 'Inline-attachments' (with minus not underscore). This was the official anwser from the support team.

**Comment by icsdevs** [comment]
This doesn't work with version 3.1 of the sending API, and suggestion by @Benoit-amo from 2016 unfortunately doesn't work on either v3.0 or 3.1.

Is there any word as to when this issue may be fixed?  Mozilla/Thunderbird team seem to not be willing to fix it on their end: https://bugzilla.mozilla.org/show_bug.cgi?id=61815
