### ISSUE TITLE
How to add Bcc aand cc

### ISSUE THREAD

**Issue by lynxfg** [mailjet/mailjet-apiv3-php#72]
Hello,

How can i add cc and Bcc option in my parameters to send email with Mailjet ?

Thanks

**Comment by Zhivko-Mailjet** [comment]
Hi @lynxfg 

You can find details here:
https://github.com/mailjet/mailjet-apiv3-php-simple/blob/master/doc/_send-api.md#send-api-json-properties

Please note that if you use the property "Recipients", you can not use "CC" and "BCC" and you need to add the main recipients using "To" property instead. 

Hope this helps.
