### ISSUE TITLE
Provide a way to get error details

### ISSUE THREAD

**Issue by flohw** [mailjet/mailjet-apiv3-php#73]
Hi,

I am using this lib for few hours and I can't find a way to get error details when a POST query has some error.
In my example, I am creating new contacts in a contacts list. After `$mj->get(Resources::$ContactslistManagemanycontacts, ['id' => $id, 'body' => $body])` I have my JobID then get the Job with the same resource and provide the job id with 'actionid' parameter instead of body. (`$mj->get(Resources::$ContactslistManagemanycontacts, ['id' => $id, 'actionid' => $jobID])`).
Then I get 'Status' state to 'Error' (in job data) with the 'ErrorFile' index but I can't find a way on how to use this data on an easy way. So I am "cheating" and use Guzzle library to be able to query the uri without constraints.

Is there a way to use this ErrorFile ? Or is it currently impossible ?

Note : I am using Symfony3.

**Comment by Zhivko-Mailjet** [comment]
Hi @flohw 
Unfortunately, at this point there is no way to access the error file with PHP. However, we will work on updating the wrapper to make it possible. 
As temporary workaround, you can use cURL to open it. You do GET on https://api.mailjet.com/v3/$error_file

**Comment by flohw** [comment]
Thank you for your quick answer.
That's what I do with guzzle the inconvenient is that I have two configurations : one for your library and another for guzzle. Not a big deal.

Thanks again.
