### ISSUE TITLE
mjml and templating langage

### ISSUE THREAD

**Issue by axi** [mailjet/mailjet-apiv3-php#79]
Hi,
I can't figure two things:
- What's the purpose of MJMLContent property (in template/:id/detailcontent endpoint) if html-part still need to be generated manually?
- Does it means that we can't use templating language (a for loop for example) within a MJML template and hope it to be compiled on mailjet side?
Thanks for explanations

**Comment by Zhivko-Mailjet** [comment]
@axi 

- At the moment, the MJMLContent property is only for internal purpose. Our online edit tool (Passport) is using the property to store both the MJML it outputs and the HTML it generates from it. Providing MJMLContent properly only is a feature we're working on and hopefully, we will have it by the end of the quarter. You can subscribe to our newsletter to get API release news https://dev.mailjet.com/#trust-us

- You are correct, at the moment you should translate first the MJML to HTML, using [MJML Engine library](https://mjml.io/).

**Comment by axi** [comment]
@Zhivko-Mailjet Ok thanks, this clarify everything. I'm looking forward to see that in action ;-)

**Comment by Zhivko-Mailjet** [comment]
@axi 
We’re actually working on an API to make it easier to use MJML inside apps, so you don’t have to deal with NodeJS. It’s in beta right now, but you can request access here: https://mjml.typeform.com/to/tW2U6K

**Comment by axi** [comment]
@Zhivko-Mailjet Any news on that feature (Providing MJMLContent properly only and mailjet side content generating) ?

**Comment by Zhivko-Mailjet** [comment]
@axi We are actively working on the new version of the SendAPI and we expect to release the beta version in couple of months. If you haven't requested the beta version, please fill in this [form](https://mjml.typeform.com/to/tW2U6K). 

Then, please contact us at api@mailjet.com with details about your Mailjet account and we will make sure you will be notified when we are ready to go!
Thanks again for your interest!

**Comment by axi** [comment]
Hi, any update on a date for MJML direct support? I just saw this blog post (https://www.mailjet.com/blog/news/meet-our-brand-new-send-api/) from may 2017 but can't find any specific date. I would love to get an approximate date of delivery in order to plan a development on our side.

**Comment by Zhivko-Mailjet** [comment]
Hi @axi ,

We do not have an exact ETA for the feature yet,  but it should come very soon. Please [subscribe to our newsletter](https://dev.mailjet.com/#newsletter) in order to stay up-to date with latest news in the API world of Mailjet.
Meanwhile, MJML API beta is available, if you would like to give it a try : https://mjml.io/api

**Comment by axi** [comment]
Hi, any news on that feature ?

**Comment by dsampaolo** [comment]
+1 : any news ?

**Comment by mathieumagalhaes** [comment]
I've build tooling around this feature, and experiencing the same issue in 2022.

I can pass MJML templates through the property MJMLContent.
The MJML is saved and visible if you open the Mailjet template builder in the UI.
But no HTML/Text is rebuild, I have to manually push the publish button for eacg template in the Mailjet UI.

Is this still restricted to internal use of the Passport builder from Mailjet?
Why even include it in the API docs then though?
Any ETA/Update on this feature?

Thanks
