### ISSUE TITLE
Add Template to campaigndraft

### ISSUE THREAD

**Issue by antoinedavid** [mailjet/mailjet-apiv3-php#81]
Hi,
i've the following issue :

`Invalid json input: expected ",", but found """ at stream position 242 ...emplate":"|96871"}...` 

my $body
```php
array:7 [▼
  "Locale" => "fr_FR"
  "Sender" => "A name"
  "SenderEmail" => "test@me.fr"
  "ContactsListID" => "1741094"
  "Title" => "a string"
  "Subject" => "an other string"
  "Template" => "96871"
]
````

my post :

```php
$response = $mj->post(Resources::$Campaigndraft, ['body' => $body]);
```
i don't understand the doc say for `Template`:  ID of the Template from which this CampaignDraft was generated, or as which it was last saved. Changing the template afterwards will not update the template in the CampaignDraft

So it's a bug or other ?

Best

**Comment by Zhivko-Mailjet** [comment]
@antoinedavid 
At this moment, templates can not be used to create campaigndrafts. The property is there for tracking and logging purposes, but it doesn't have real implementation.
The way to go here is to extract the HTML part of the template and add it in [/campaigndraft/$id/detailcontent](https://dev.mailjet.com/email-api/v3/campaigndraft-detailcontent/)

**Comment by antoinedavid** [comment]
hi,

Yes i see this route later, and i've already implemented with success.

The doc is not clear for the template, and for information with the api we can save the property `TemplateID` and not `Template` but this have no effect. And set `Template` generate an error, so why you don't delete that from the doc : https://dev.mailjet.com/email-api/v3/campaigndraft/ ?

Best

**Comment by Zhivko-Mailjet** [comment]
Thanks for the feedback! We will review again the behavior of the property.
