### ISSUE TITLE
Feature Request: Constants

### ISSUE THREAD

**Issue by donatj** [mailjet/mailjet-apiv3-php#82]
It would be wonderfully great if the string keys to be used in the API could be predefined as constants.  This would prevent the creeping fear that I've possibly typo-ed something because an undefined variable would show up in my error log.

```php
<?php

$body = [
    Request::FROM_EMAIL => "pilot@mailjet.com",
    Request::FROM_NAME => "Mailjet Pilot",
    Request::SUBJECT => "Your email flight plan!",
    Request::TEST_PART => "Dear passenger, welcome to Mailjet! May the delivery force be with you!",
    Request::HTML_PART=> "<h3>Dear passenger, welcome to Mailjet!</h3><br />May the delivery force be with you!",
    Request::RECIPIENTS => [[Request::RECIPENT_EMAIL => "passenger@mailjet.com"]]
];

$response = $mj->post(Resources::$Email, [Request::BODY => $body]);
```

**Comment by Zhivko-Mailjet** [comment]
@donatj 
Thnak you for the feedback! We will discuss your suggestion and consider it for future releases. I will let you know if we have any news.

**Comment by abambova** [comment]
Hi @donatj,
Your feedback was taken into consideration and a new release was made, I'll close the issue. Please feel free to open a new issue if needed.

**Comment by donatj** [comment]
Are the keys defined somewhere accessible now? I'm not seeing this mentioned in the docs, nor am I seeing this in the source…
