### ISSUE TITLE
Updating contact data has no effect

### ISSUE THREAD

**Issue by Laegel** [mailjet/mailjet-apiv3-php#83]
Greetings, 

I was trying to update a contact data with this code, according to the API doc:
```php
$client_response = $client->put(\Mailjet\Resources::$Contactdata, array(
    'Email' => $email,
    'body' => array(
	'Data' => array(
	    array(
		'Name' => 'inside_generale',
		'Value' => false
	    )
        )
    )
));
```
It returns a response with 200 status:
```
[status:Mailjet\Response:private] => 200
[success:Mailjet\Response:private] => 1
[body:Mailjet\Response:private] => Array
        (
            [Count] => 1
            [Data] => Array
                (
                    [0] => Array
                        (
                            [ContactID] => 1696196370
                            [Data] => Array
                                (
                                    [0] => Array
                                        (
                                            [Name] => inside_generale
                                            [Value] => false
                                        )

                                )

                            [ID] => 1696196370
                        )

                )

            [Total] => 1
        )
```

But when I check the corresponding user in the app:
![screenshot from 2017-04-28 13 14 10](https://cloud.githubusercontent.com/assets/3584791/25526668/e60f05b8-2c14-11e7-9c02-c050f0c14411.png)

Am I missing something ? Is there a difference between contact data and contact property ?
Thanks for reading.

**Comment by Zhivko-Mailjet** [comment]
@Laegel 

You are not missing anything. The boolean properties are stored correctly on our API, but are displayed always as `True` in the WebUI. We are aware of this issue and our Front End team is working on resolving it.

In the meantime, you should be able to use the contact properties normally through the API, as the real values are kept.

Thanks for reporting the problem and sorry for any inconvenience.

**Comment by Laegel** [comment]
Thanks a lot for your answer.
Should I close this issue or let it open ?

**Comment by Zhivko-Mailjet** [comment]
If you wish to follow the progress of the Web UI issue resolution, you can leave it open. Otherwise, if you are fine with the response, you are more than welcome to close it.

**Comment by Zhivko-Mailjet** [comment]
@Laegel 
I just wanted to inform you that the issue should be now resolved.
