### ISSUE TITLE
Pagination doesn't exist

### ISSUE THREAD

**Issue by GerardFernandes** [mailjet/mailjet-apiv3-php#84]
This API don't manage correctly the pagination as itself doesn't exist

**Comment by Zhivko-Mailjet** [comment]
Hi @GerardFernandes 

You can use `Limit` and `Offset` filter to make a pagination. See here -> https://dev.mailjet.com/guides/#navigation-through-results

Hope this helps.

**Comment by GerardFernandes** [comment]
Thank you, it helps a lot!
I can't find this because I was reading V3 docs!
Thank you so much, Zhivko!
