### ISSUE TITLE
Delete contactList

### ISSUE THREAD

**Issue by goutfeb** [mailjet/mailjet-apiv3-php#85]
Hi,

I trying to delete a contactList by doing : 

`$body = [
          'ID' => "XXXXXXX"
    ];`
`$MJResponse = $MailjetClient->delete(Resources::$Contactslist, ['body' => $body]);`

But it does not work.
I had error code 405 : `Method not allowed`

Have I forgotten anything ?
Thanks.

**Comment by Zhivko-Mailjet** [comment]
Hi @goutfeb 
When deleting an object, you do need to pass the ID in the body, but in the URL instead. In your case, the call should look like this:
`$MJResponse = $MailjetClient->delete(Resources::$Contactslist, ['id' => $ID]);`

No `$body` required. Hope it helps.

**Comment by goutfeb** [comment]
Oh thanks it works well !
Ben.
