### ISSUE TITLE
Wrong content type CSV import

### ISSUE THREAD

**Issue by goutfeb** [mailjet/mailjet-apiv3-php#86]
HI,

I have another problem with the MailJet API.
I'd like to upload a CSV but content type seems to be wrong.

`$CSVFile = file_get_contents("../../file.csv");`
`$MJResponse = $MJClient->post(Resources::$ContactslistCsvdata, ['body' =>$CSVFile]);`
 |
V
`400 - Data Content type "text/plain" does not match URL content type "".`

Where can this come from ?
Thanks

**Comment by Zhivko-Mailjet** [comment]
Hi @goutfeb 

In your API call, you are missing the ContactsListID. The call should be:
`$response = $mj->post(Resources::$ContactslistCsvdata, ['body' => $CSVContent, 'id' => $ID_CONTACTLIST]);`
See here -> https://dev.mailjet.com/guides/?php#uploading-of-the-data

I believe that the error message can be more explicit though and we will work on this. 

Hope I was able to help you.

**Comment by goutfeb** [comment]
Hmm... By this way I'd like to add CSV file using different methods ("addforce", "addnoforce", ...). So I'd  like to import first my CSV and after that use `ContactManagecontactslists` to put datas into a list. That right, isn't it ?

**Comment by goutfeb** [comment]
What is the parameter DataID in Csvimport method ? Because I'd like to use it with ContactslistCsvdata but you lost me... @Zhivko-Mailjet ;)

**Comment by Zhivko-Mailjet** [comment]
@goutfeb 
You can also include the contact data directly in the CSV file. The DataID is the ID, returned when the upload has been accepted -> https://dev.mailjet.com/guides/?php#uploading-of-the-data

If you have additional questions related to the API behavior, best practices or any other questions, please reach out to our [support ](https://eu.mailjet.com/support/ticket)who will be happy to help. Thanks!

**Comment by goutfeb** [comment]
Sure. No problem.
Thanks.
