### ISSUE TITLE
We sometimes get back: 411 Length Required

### ISSUE THREAD

**Issue by LosHawlos** [mailjet/mailjet-apiv3-php#87]
To fetch back the hardbounces into our database we use the apis /bouncestatistics and /messagesentstatistics

The code works most of the time, but sometimes we get back HTTP error 411 Length Required.

We have tried the code on 2 different servers that are connected by different internet providers so it seems not to be a problem with our machines. Both show the same effect that the same code and the same api call sometimes fail.

The code we use looks similiar to this:

>$mj = new MjClient( $this->mjKey, $this->mjSecret);
>$filters = array(
>    'Limit' => 100,
>    'Offset' => 0,
>    'Bounced'=>true,
>    'FromTS'=>$oldest,
>    'ToTS'=>$now
>);
>$response = $mj->get( MjResources::$Bouncestatistics, array( 'filters'=>$filters));
>if ($response->success()) {
>   ...
>}

**Comment by Zhivko-Mailjet** [comment]
Hi @LosHawlos 

We believe that this error is not exactly related to the wrapper, but to specific API behavior. Please submit a [support ticket](https://eu.mailjet.com/support/ticket) with details for your Mailjet account and we will do our best to investigate further. Thanks!

**Comment by Zhivko-Mailjet** [comment]
Hi @LosHawlos 

Actually, after further investigation, we found a problem in the wrapper. Looks like sending empty JSON body causes the problem. There was a [PR ](https://github.com/mailjet/mailjet-apiv3-php/pull/77) while ago, which was merged to the master, but not released yet. To resolve the problem, please download the latest version of the master branch -> https://github.com/mailjet/mailjet-apiv3-php/archive/master.zip

**Comment by LosHawlos** [comment]
Thanks for your support!

Updated from 1.1.8 to 1.1.9 and now our scripts run without errors.

Couldnt believe it was caused by the wrapper because it did work most of the time and only sometimes threw the error.

**Comment by axi** [comment]
1.1.9 fixed it for me too. Thanks

**Comment by JeffGreat** [comment]
I've having the same issue this week. I got crazy with it. I've update to 1.1.9 and do not have anymore content length error but an error 500 with "access violation" when sending email. What's happening with mailjet?!?!? We're in production please!

**Comment by Zhivko-Mailjet** [comment]
Hi @JeffGreat 

We would generate `500 Access violation` if you are sending empty or malformated JSON to our API. This problem shouldn't be related to the one described in this topic.

Please open a [support ticket](https://app.mailjet.com/support/ticket), providing us your full API call and API response and the support team will do it's best to help you as quickly as possible.

**Comment by JeffGreat** [comment]
I've opened a ticket in the sametime. Got my answer! Thx!
