### ISSUE TITLE
Wrong API version

### ISSUE THREAD

**Issue by pderouville** [mailjet/mailjet-apiv3-php#90]
Hie

Here is my problem .... : 

$mj = new \Mailjet\Client('xxxx', 'zzzz', true, ['url' => "www.mailjet.com", 'version' => 'v3', 'call' => false]);
$response = $mj->post(Resources::$Email, ['body' => $body], ['version' => 'v3']);

Answer : 

Response {#511 ▼
  -status: 400
  -success: false
  -body: null
  -rawResponse: Response {#509 ▼
    -reasonPhrase: "Wrong API version"
    -statusCode: 400
    -headers: array:6 [▶]
    -headerNames: array:6 [▶]
    -protocol: "1.1"
    -stream: Stream {#507 ▶}
  }
  +"request": Request {#33 ▶}
}

Any idea ?

**Comment by Zhivko-Mailjet** [comment]
HI @pderouville 

Your Mailjet account is running on the old API platform and has to be migrated. Please contact our [support ](https://www.mailjet.com/support/ticket)for details.

**Comment by pderouville** [comment]
Ok thanks a lot )
