### ISSUE TITLE
Problem occurs when i tried to send email using laravel mailables

### ISSUE THREAD

**Issue by Naveed-anwar123** [mailjet/mailjet-apiv3-php#93]
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required

**Comment by Zhivko-Mailjet** [comment]
Hi @Naveed-anwar123 ,

Do you use the PHP wrapper directly or with the [Laravel package](https://github.com/mailjet/laravel-mailjet) ?
Could you please share a sample of your code ?

**Comment by Naveed-anwar123** [comment]
Inside my Mailable class
public function build()
    {
		return $this->from('naveed@example.com')->view('email.template');
    }
when i return then this error happens to me.

**Comment by Naveed-anwar123** [comment]
I am using Laravel 5.4 and "guzzlehttp/guzzle": "^6.3" package.

**Comment by Zhivko-Mailjet** [comment]
@Naveed-anwar123 
Did you follow these configuration instructions  -> https://github.com/mailjet/laravel-mailjet#installation ?
Please show us the modifications you have done in order to implement Mailjet.

**Comment by latanasov** [comment]
Ticket closed due to user inactivity. Feel free to raise a new ticket if the issue still occurs.
