### ISSUE TITLE
Class 'Mailjet\Client' not found

### ISSUE THREAD

**Issue by lwebzem12** [mailjet/mailjet-apiv3-php#97]
I am having Fatal error: Class 'Mailjet\Client' not found in /home/mysite/App/Models/Mailj.php
It is working on local 127.0.0.1 site but when I move it to web host server it can not find Class 'Mailjet\Client'   The difference in local site and web site is php version, Local site is on php 7 and website is on php 5.5.  

Here is the beginning of script till the line which is failing:
<?php
use Mailjet\Resources;
require 'vendor/autoload.php';
class Mailj
{
   
    public static function send($to, $subject, $text, $html, $to_name)
    {
        $apiKey = "xxxxxx;     
        $secretKey = "xxxxxxxx"; 
        $apiKey = 'xxxxxxxx';     
        $secretKey = 'xxxxxxx';  
        $emailFrom="xxxxxx";
        $emailFromName="xxxxx"; 
              // the below line is failing:
		$mj = new Mailjet\Client( $apiKey, $secretKey,  true,['version' => 'v3.1']);

Can you please advise?
Thanks.
Leo.

**Comment by latanasov** [comment]
Hi @lwebzem12  could you share your code example .

**Comment by lwebzem12** [comment]
Hi Lyubomir,
Here is my code, the yellow line is failing.
Thanks.
Leo.

<?php


use Mailjet\Resources;
require 'vendor/autoload.php';

class Mailj
{

    public static function send($to, $subject, $text, $html, $to_name)
    {


        $apiKey = "xxxxxx;
        $secretKey = "xxxxxxxx";
        $apiKey = 'xxxxxxxx';
        $secretKey = 'xxxxxxx';
        $emailFrom="xxxxxx";
        $emailFromName="xxxxx";

              // the below line is failing:
                                $mj = new Mailjet\Client( $apiKey, $secretKey,  true,['version' => 'v3.1']);

                $body = [
                                'Messages' => [
        [
            'From' => [

                'Email' =>  $emailFrom,
                'Name' => $emailFromName
            ],
            'To' => [
                [
                    'Email' => $to,
                    'Name' => $to_name
                ]
            ],
            'Subject' => $subject,
            'TextPart' => $text,
            'HTMLPart' => $html
        ]
    ]
];

$response = $mj->post(Resources::$Email, ['body' => $body]);
$response->success() && var_dump($response->getData());


    }


}
?>

**Comment by latanasov** [comment]
Hi @lwebzem12 , could it be you are missing a `\`  before `Mailjet\Client`. 
Try with `$mj = new \Mailjet\Client(.....)` and let me know if it resolves your issue.

**Comment by lwebzem12** [comment]
Hi Lyubomir,
It did not help.  I still have same error
   Fatal error: Class 'Mailjet\Client' not found in /home/abstbtools/App/Models/Mailj.php on line 66

Also I am having error msg  Failed opening required ' /home/abstbtools/vendor/autoload.php     so I disabled this line, not sure if it is needed or not, on local server it is working without it.

Thanks.
Leo.

**Comment by lwebzem12** [comment]
I fixed     /home/abstbtools/vendor/autoload.php  line, it is now finding it, but still have
 Fatal error: Class 'Mailjet\Client' not found in /home/abstbtools/App/Models/Mailj.php on line 68

From: Leo Zyskind (Adaptive)
Sent: Tuesday, October 3, 2017 7:19 AM
To: 'mailjet/mailjet-apiv3-php' <reply@reply.github.com>; mailjet/mailjet-apiv3-php <mailjet-apiv3-php@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [mailjet/mailjet-apiv3-php] Class 'Mailjet\Client' not found (#97)

Hi Lyubomir,
It did not help.  I still have same error
   Fatal error: Class 'Mailjet\Client' not found in /home/abstbtools/App/Models/Mailj.php on line 66

Also I am having error msg  Failed opening required ' /home/abstbtools/vendor/autoload.php     so I disabled this line, not sure if it is needed or not, on local server it is working without it.

Thanks.
Leo.

**Comment by latanasov** [comment]
Hi @lwebzem12  did you first install the wrapper through composer using 
`composer require mailjet/mailjet-apiv3-php` ? Please do that followed by `composer dump-autoload` to regenerate your vendor/autoload.php . Your problems seems to be with the installation of the php wrapper itself.

**Comment by lwebzem12** [comment]
Is it something that I need to do on web server OR I can do on my local machine and then copy to web server?  If I need to do on web server can I run it within php script? Because I do not see that they provide shell to run commands?
Thanks

**Comment by latanasov** [comment]
Hi @lwebzem12, if you are unable to install _composer_ on your web server what you can do is set up an environment on your local machine that roughly matches your shared host, and do all of your management through the _composer_ command line locally. Then when everything is set (you've installed the dependencies etc.) you can upload it via FTP.

To sum-up use _composer_ locally as mentioned before, and upload your local files to the remote server when all dependencies have been resolved.

Regards,
Lyubomir

**Comment by lwebzem12** [comment]
Hi Lyubomir,
Yes it is working now. I copied autoload and composer folder files from local machine to web server and this resolved issue.
One more question – what is the last line of wrapper doing:
    $response->success() && var_dump($response->getData());

My understanding – this is just for printing information and I can disable it?   Because I am getting error msg “Cannot modify header information - headers already sent by …”

Thanks.
Leo.

**Comment by latanasov** [comment]
Hi @lwebzem12, yes $response->success() && var_dump($response->getData()); is just "printing" the result (used for example purposes). You can exclude it from your code.

**Comment by lwebzem12** [comment]
Hi Lyubomir,
Ok sounds good.  Thanks a lot for your help.  Emailing is working now.

Best Regards,
Leo.
