### ISSUE TITLE
How to remove contact?

### ISSUE THREAD

**Issue by zorian-motso** [mailjet/mailjet-apiv3-php#98]
I can't remove contact from Mailjet
I try 
`
$mailjet = new Client(
            env('MJ_APIKEY_PUBLIC'),
            env('MJ_APIKEY_PRIVATE')
        );
$mailjet->delete(Resources::$Contact, [ 'id' => 'some_email@gmail.com' ])`
My response
```
 [
  "ErrorInfo" => ""
  "ErrorMessage" => "Operation not allowed"
  "StatusCode" => 401
]
```

**Comment by latanasov** [comment]
Hi @zorian-motso  it is not possible to do a Delete on the `/contact` resource.
Regards,
Lyubomir

**Comment by pierrefaure** [comment]
Would like to know more about that as it's a GDPR related issue for us.
How to remove a contact from Mailjet if we can't send a delete to the /contact resource?

I checked in the API documentation and couldn't find anything

**Comment by kmanchikov** [comment]
Hi Pierre, 

We are currently working on such an functionality as per GDPR regulations, and will let you know once that is available. However until then, you do have the option to delete contacts through a request to our Support Team (support ticket) or send an email to privacy@mailjet.com.

Best, 

Krassimir

**Comment by Cyrille37** [comment]
This php framework does not implements contact deletion, but from the [api doc](https://dev.mailjet.com/email/guides/contact-management/#gdpr-delete-contacts) using the API v4 it's possible.

So u need to create a MjClient with `$version=>'v4'` then pass resource `['contacts', '']` to client delete command.
